### ISSUE TITLE
Felix errors in Kubernetes pod

### ISSUE THREAD

**Issue by codefx9** [projectcalico/calico#1005]
Hi,
I am experimenting with Calico. I see the following errors in Felix. Can you help me understand how to fix this? Thanks.

```
2016-04-04 11:10:11,985 [INFO][27617/4] calico.felix.frules 231: IPIP disabled or no tunnel address set: removing MASQUERADE rule.
2016-04-04 11:10:12,005 [INFO][27624/140607120456368] calico.etcddriver.hwm 105: Stopped tracking deletions
modprobe: can't change directory to '/lib/modules': No such file or directory
ip6tables-save v1.4.21: Cannot initialize: iptables who? (do you need to insmod?)

2016-04-04 11:10:12,009 [INFO][27624/140607120456368] calico.etcddriver.driver 578: First resync: skipping deletion scan
2016-04-04 11:10:12,010 [INFO][27624/140607120456368] calico.etcddriver.driver 728: Sending status to Felix: in-sync
2016-04-04 11:10:12,011 [INFO][27624/140607120456368] calico.etcddriver.driver 566: In sync, now processing events only...
2016-04-04 11:10:12,015 [INFO][27617/1] calico.felix.fetcd 531: etcd driver status changed to resync
modprobe: can't change directory to '/lib/modules': No such file or directory
ip6tables-save v1.4.21: Cannot initialize: iptables who? (do you need to insmod?)

modprobe: can't change directory to '/lib/modules': No such file or directory
ip6tables-save v1.4.21: Cannot initialize: iptables who? (do you need to insmod?)

2016-04-04 11:10:12,017 [ERROR][27617/5] calico.felix.actor 320: Exception processing M7b3239e146adb9a6 (_load_chain_names_from_iptables)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/calico/felix/actor.py", line 318, in _step
    result = msg.method()
  File "/usr/lib/python2.7/site-packages/calico/felix/fiptables.py", line 189, in _load_chain_names_from_iptables
    self.table])
  File "/usr/lib/python2.7/site-packages/gevent/subprocess.py", line 327, in check_output
    raise ex
CalledProcessError: Command '['ip6tables-save', '--table', 'raw']' returned non-zero exit status 1
2016-04-04 11:10:12,019 [INFO][27617/5] calico.felix.fiptables 485: IptablesUpdater<v6-raw,queue_len=0,live=True,msg=None> no updates in this batch.
```

**Comment by fasaxc** [comment]
@codefx9 what OS and version are you running on?  How are you running Felix?

**Comment by codefx9** [comment]
I am running on Debian 8.4. I am using calico/node:0.18 with Docker 1.9.1 . I am running calico node directly from Docker. Basically I noted down the command `calicoctl node` runs and running that directly .

**Comment by fasaxc** [comment]
@codefx9 I think the calicoctl node command also installs the correct kernel modules etc before starting calico/node.  You either need to set up your container so that /lib/modules is mounted and the container is allowed to install kernel modules, or you need to install the iptables kernel modules before starting calico/node.

What's your use-case for bypassing `calicoctl node`?

**Comment by codefx9** [comment]
Thanks a lot for answering my questions.

I am trying to use Calico with Kubernetes via static pod manifest files. On master node, I am running etcd and calico as two containers in a single pod. Other nodes are running just calico node. The benefit of this approach is that I can avoid the race between etcd and master calico node startup process. Also, docker gets started few times when kubelet starts in the beginning. 

Is it possible to run calico node successfully directly via docker? Can you please point me to the modules that need to installed first?

**Comment by fasaxc** [comment]
I _think_ someone on our public calico-users slack has managed to get Calico working in a pod.  I suggest you head over there and ask if they can share their config.

**Comment by fasaxc** [comment]
Here's a link to the slack sign-up page: https://calicousers-slackin.herokuapp.com/

**Comment by codefx9** [comment]
Thank you. I will look into that. Is there any plan to officially support a mode where calico can run with Docker directly? I saw something in that regard in the most recent changelog. GIven the fast pace Calico's release process, any custom setup will be a pain to maintain.

**Comment by fasaxc** [comment]
I'm not sure, @tomdee?

**Comment by tomdee** [comment]
@codefx9 Using the docker command that calicoctl node prints is supported. As @fasaxc says, you just need to be careful to load the required kernel modules.

**Comment by codefx9** [comment]
Thanks. I have figured out how to fix the modprobe issues.
