### ISSUE TITLE
When using Kubernetes Datastore, a IPv6 enabled K8s cluster causes a panic in calico-node

### ISSUE THREAD

**Issue by tmjd** [projectcalico/calico#1703]
## Description

Calico node crashes when using the Kubernetes Datastore with an IPv6 enabled Kubernetes cluster.  From the panic below and looking at the code, libcalico-go panics because it tries to generate an IPIP tunnel even when using IPv6.

## Expected Behavior
calico-node does not crash and it works with a K8s IPv6 cluster.

## Current Behavior
libcalico-go panics when the PodCIDR is not IPv4.

Here are the logs from the calico-node pod, the calico-node container.
```
2018-02-23 18:27:48.868 [INFO][7] startup.go 248: Early log level set to info
2018-02-23 18:27:48.869 [INFO][7] startup.go 278: Checking datastore connection
2018-02-23 18:27:48.878 [INFO][7] startup.go 302: Datastore connection verified
2018-02-23 18:27:48.878 [INFO][7] startup.go 99: Datastore is ready
2018-02-23 18:27:48.885 [INFO][7] customresource.go 217: Error getting resource Key=ClusterInformation(default) Name="default" Resource="ClusterInformations" Revision="" error=clusterinformations.crd.projectcalico.org "default" not found
2018-02-23 18:27:48.886 [INFO][7] customresource.go 100: Error getting resource Key=GlobalFelixConfig(name=CalicoVersion) Name="calicoversion" Resource="GlobalFelixConfigs" error=the server could not find the requested resource (get GlobalFelixConfigs.crd.projectcalico.org calicoversion)
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/projectcalico/calico/calico_node/vendor/github.com/projectcalico/libcalico-go/lib/backend/k8s/resources.getTunnelIp(0xc420334580, 0xc4202b8090, 0x165499f)
        /go/src/github.com/projectcalico/calico/calico_node/vendor/github.com/projectcalico/libcalico-go/lib/backend/k8s/resources/node.go:270 +0x1a8
github.com/projectcalico/calico/calico_node/vendor/github.com/projectcalico/libcalico-go/lib/backend/k8s/resources.K8sNodeToCalico(0xc420334580, 0xc420012249, 0xd, 0x0)
        /go/src/github.com/projectcalico/calico/calico_node/vendor/github.com/projectcalico/libcalico-go/lib/backend/k8s/resources/node.go:205 +0x49e
github.com/projectcalico/calico/calico_node/vendor/github.com/projectcalico/libcalico-go/lib/backend/k8s/resources.(*nodeClient).Get(0xc420464b88, 0x208b7a0, 0xc420016048, 0x208e380, 0xc4201fe9f0, 0x0, 0x0, 0xc4206079c0, 0x410657, 0xc4201fe9f0)
        /go/src/github.com/projectcalico/calico/calico_node/vendor/github.com/projectcalico/libcalico-go/lib/backend/k8s/resources/node.go:102 +0x22a
github.com/projectcalico/calico/calico_node/vendor/github.com/projectcalico/libcalico-go/lib/backend/k8s.(*KubeClient).Get(0xc4202816e0, 0x208b7a0, 0xc420016048, 0x208e380, 0xc4201fe9f0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/projectcalico/calico/calico_node/vendor/github.com/projectcalico/libcalico-go/lib/backend/k8s/k8s.go:434 +0x318
github.com/projectcalico/calico/calico_node/vendor/github.com/projectcalico/libcalico-go/lib/clientv3.(*resources).Get(0xc4203e0b00, 0x208b7a0, 0xc420016048, 0x0, 0x0, 0x163b25c, 0x4, 0x0, 0x0, 0xc420012249, ...)
        /go/src/github.com/projectcalico/calico/calico_node/vendor/github.com/projectcalico/libcalico-go/lib/clientv3/resources.go:193 +0x1b8
github.com/projectcalico/calico/calico_node/vendor/github.com/projectcalico/libcalico-go/lib/clientv3.nodes.Get(0x16468f1, 0xf, 0x164d08a, 0x14, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/projectcalico/calico/calico_node/vendor/github.com/projectcalico/libcalico-go/lib/clientv3/node.go:192 +0xb3
github.com/projectcalico/calico/calico_node/vendor/github.com/projectcalico/libcalico-go/lib/clientv3.(*nodes).Get(0xc42049a000, 0x208b7a0, 0xc420016048, 0xc420012249, 0xd, 0x0, 0x0, 0x16500a4, 0x17, 0x0)
        <autogenerated>:1 +0xcb
main.getNode(0x208b7a0, 0xc420016048, 0x2093280, 0xc42012e480, 0xc420012249, 0xd, 0x210b800)
        /go/src/github.com/projectcalico/calico/calico_node/startup/startup.go:323 +0xa3
main.main()
        /go/src/github.com/projectcalico/calico/calico_node/startup/startup.go:113 +0x185
```

## Possible Solution
If PodCIDR is not IPv4 then do not try to get a tunnel IP.

## Steps to Reproduce (for bugs)
1. Setup an IPv6 K8s cluster, with an IPv6 pod CIDR
2. Using the Calico networking KDD manifest (https://docs.projectcalico.org/v3.0/getting-started/kubernetes/installation/hosted/kubernetes-datastore/#option-1-calico-policy-with-calico-networking-beta).  Edit it to enable IPv6
3. Apply the manifest and check the logs from calico-node

## Context
I was trying to test out IPv6 with Calico backed by the Kubernetes datastore.

## Your Environment
* Calico version: v3.0.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): K8s
* Operating System and version: Container Linux 1632.3.0

**Comment by tmjd** [comment]
Fixed with https://github.com/projectcalico/libcalico-go/pull/797
