### ISSUE TITLE
Calico-node 3.2.1 does not apply iptables rules when `FELIX_IPTABLESLOCKTIMEOUTSECS` is used

### ISSUE THREAD

**Issue by juhtie01** [projectcalico/calico#2179]
## Expected Behavior
I'm upgrading our Canal from calico-node 3.1.3 to 3.2.1. We introduced the `FELIX_IPTABLESLOCKTIMEOUTSECS` environment variable with value of 5 seconds when we noticed that there is heavy iptables contention between calico-node, flannel and kube-proxy. The timeout helped reduce the contention quite a lot.

## Current Behavior
When using calico-node 3.2.1, network policies cannot be applied anymore. Logs are showing the following type of output:

```
canal-5wsjh calico-node 2018-09-07 08:02:59.942 [ERROR][15833] table.go 778: Failed to program iptables, loading diags before panic. error=exit status 4 ipVersion=0x4 table="mangle"
canal-5wsjh calico-node 2018-09-07 08:02:59.942 [ERROR][15833] table.go 784: Current state of iptables ipVersion=0x4 iptablesState="# Generated by iptables-save v1.6.2 on Fri Sep  7 08:02:59 2018\n*filter\n:INPUT ACCEPT [13339:14933000]\n:FORWARD ACCEPT [0:0]\n:OUTPUT ACCEPT [12314:14340285]\n:DOCKER - [0:0]\n:DOCKER-ISOLATION-STAGE-1 - [0:0]\n:DOCKER-ISOLATION-STAGE-2 - [0:0]\n:DOCKER-USER - [0:0]\n:KUBE-EXTERNAL-SERVICES - [0:0]\n:KUBE-FIREWALL - [0:0]\n:KUBE-FORWARD - [0:0]\n:KUBE-SERVICES - [0:0]\n-A INPUT -m conntrack --ctstate NEW -m comment --comment \"kubernetes externally-visible service portals\" -j KUBE-EXTERNAL-SERVICES\n-A INPUT -j KUBE-FIREWALL\n-A FORWARD -m comment --comment \"kubernetes forwarding rules\" -j KUBE-FORWARD\n-A FORWARD -j DOCKER-USER\n-A FORWARD -j DOCKER-ISOLATION-STAGE-1\n-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT\n-A FORWARD -o docker0 -j DOCKER\n-A FORWARD -i docker0 ! -o docker0 -j ACCEPT\n-A FORWARD -i docker0 -o docker0 -j ACCEPT\n-A FORWARD -s 10.1.0.0/16 -j ACCEPT\n-A FORWARD -d 10.1.0.0/16 -j ACCEPT\n-A OUTPUT -m conntrack --ctstate NEW -m comment --comment \"kubernetes service portals\" -j KUBE-SERVICES\n-A OUTPUT -j KUBE-FIREWALL\n-A DOCKER-ISOLATION-STAGE-1 -i docker0 ! -o docker0 -j DOCKER-ISOLATION-STAGE-2\n-A DOCKER-ISOLATION-STAGE-1 -j RETURN\n-A DOCKER-ISOLATION-STAGE-2 -o docker0 -j DROP\n-A DOCKER-ISOLATION-STAGE-2 -j RETURN\n-A DOCKER-USER -j RETURN\n-A KUBE-FIREWALL -m comment --comment \"kubernetes firewall for dropping marked packets\" -m mark --mark 0x8000/0x8000 -j DROP\n-A KUBE-FORWARD -m comment --comment \"kubernetes forwarding rules\" -m mark --mark 0x4000/0x4000 -j ACCEPT\n-A KUBE-FORWARD -s 10.1.0.0/16 -m comment --comment \"kubernetes forwarding conntrack pod source rule\" -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT\n-A KUBE-FORWARD -d 10.1.0.0/16 -m comment --comment \"kubernetes forwarding conntrack pod destination rule\" -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT\nCOMMIT\n# Completed on Fri Sep  7 08:02:59 2018\n" table="filter"
canal-5wsjh calico-node 2018-09-07 08:02:59.942 [PANIC][15833] table.go 786: Failed to program iptables, giving up after retries error=exit status 4 ipVersion=0x4 table="filter"
canal-5wsjh calico-node 2018-09-07 08:02:59.942 [WARNING][15833] table.go 978: Failed to execute ip(6)tables-restore command error=exit status 4 errorOutput="Another app is currently holding the xtables lock. Perhaps you want to use the -w option?\n" input="*nat\n:cali-fip-dnat - -\n:cali-fip-snat - -\n:cali-nat-outgoing - -\n:cali-PREROUTING - -\n:cali-POSTROUTING - -\n:cali-OUTPUT - -\n-A cali-nat-outgoing -m comment --comment \"cali:Dw4T8UWPnCLxRJiI\" -m set --match-set cali40masq-ipam-pools src -m set ! --match-set cali40all-ipam-pools dst --jump MASQUERADE\n-A cali-PREROUTING -m comment --comment \"cali:r6XmIziWUJsdOK6Z\" --jump cali-fip-dnat\n-A cali-POSTROUTING -m comment --comment \"cali:Z-c7XtVd2Bq7s_hA\" --jump cali-fip-snat\n-A cali-POSTROUTING -m comment --comment \"cali:nYKhEzDlr11Jccal\" --jump cali-nat-outgoing\n-A cali-OUTPUT -m comment --comment \"cali:GBTAv2p5CwevEyJm\" --jump cali-fip-dnat\n-I PREROUTING -m comment --comment \"cali:6gwbT8clXdHdC1b1\" --jump cali-PREROUTING\n-I OUTPUT -m comment --comment \"cali:tVnHkvAo15HuiPy0\" --jump cali-OUTPUT\n-I POSTROUTING -m comment --comment \"cali:O3lYWMrLQYEMJtB5\" --jump cali-POSTROUTING\nCOMMIT\n" ipVersion=0x4 output="" table="nat"
canal-5wsjh calico-node 2018-09-07 08:02:59.942 [ERROR][15833] table.go 778: Failed to program iptables, loading diags before panic. error=exit status 4 ipVersion=0x4 table="nat"
canal-5wsjh calico-node panic: (*logrus.Entry) (0x1887f40,0xc42009ed20)
canal-5wsjh calico-node
canal-5wsjh calico-node goroutine 164 [running]:
canal-5wsjh calico-node github.com/projectcalico/node/vendor/github.com/sirupsen/logrus.Entry.log(0xc42009e190, 0xc420759110, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
canal-5wsjh calico-node 	/go/src/github.com/projectcalico/node/vendor/github.com/sirupsen/logrus/entry.go:128 +0x59c
canal-5wsjh calico-node github.com/projectcalico/node/vendor/github.com/sirupsen/logrus.(*Entry).Panic(0xc42009ec30, 0xc42098bf00, 0x1, 0x1)
canal-5wsjh calico-node 	/go/src/github.com/projectcalico/node/vendor/github.com/sirupsen/logrus/entry.go:173 +0xaa
canal-5wsjh calico-node github.com/projectcalico/node/vendor/github.com/projectcalico/felix/iptables.(*Table).Apply(0xc420193600, 0xc93d59)
canal-5wsjh calico-node 	/go/src/github.com/projectcalico/node/vendor/github.com/projectcalico/felix/iptables/table.go:786 +0x651
canal-5wsjh calico-node github.com/projectcalico/node/vendor/github.com/projectcalico/felix/dataplane/linux.(*InternalDataplane).apply.func3(0xc4209da000, 0xc4209da008, 0xc4209da010, 0xc420193600)
canal-5wsjh calico-node 	/go/src/github.com/projectcalico/node/vendor/github.com/projectcalico/felix/dataplane/linux/int_dataplane.go:909 +0x2f
canal-5wsjh calico-node created by github.com/projectcalico/node/vendor/github.com/projectcalico/felix/dataplane/linux.(*InternalDataplane).apply
canal-5wsjh calico-node 	/go/src/github.com/projectcalico/node/vendor/github.com/projectcalico/felix/dataplane/linux/int_dataplane.go:908 +0x408
```

If I remove the environment variable from the daemonset, network policies can be applied again, though it seems with some iptables contention.

## Possible Solution
If I understood the code correctly, it looks like calico-node acquires the lock and then iptables-restore fails when it tries to acquire the lock, as it is already locked by calico-node.

## Steps to Reproduce (for bugs)
1. Take the RBAC and DS manifest from https://docs.projectcalico.org/v3.2/getting-started/kubernetes/installation/flannel
2. Add the environment variable and mount /run to the daemonset:
```
            - name: FELIX_IPTABLESLOCKTIMEOUTSECS
              value: "5"
...
            - name: run
              mountPath: /run
              readOnly: false
```
3. Apply the files with kubectl.
4. Errors such as above can be seen in calico-node logs.

## Context
We want to reduce iptables contention, which is a big problem in our larger environments where network policies or services may not be created correctly fast enough.

## Your Environment
* Calico version: 3.2.1 (works as expected with 3.1.3)
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes 1.10.7
* Operating System and version: Container Linux by CoreOS stable (1745.7.0)
* Link to your project (optional):

**Comment by fasaxc** [comment]
Looks like we've auto-revved to a version of `iptables-restore` that _honors_ the iptables lock.  Previously `iptables-restore` ignored the lock so we had our own implementation.

@juhtie01 Try disabling the iptables lock again; you've activated Calico's lock implementation, which will conflict with iptables' own.  

Now it's present, we should adjust Felix to take advantage of the new `-w` flag on `iptables-restore`

**Comment by caseydavenport** [comment]
We've merged these two:
- https://github.com/projectcalico/felix/pull/1907
- https://github.com/projectcalico/felix/pull/1903

which should address this issue.
