### ISSUE TITLE
Error in Pod Logs

### ISSUE THREAD

**Issue by iahmad-khan** [projectcalico/calico#3315]
I am Getting this error in calico pod logs on kubernetes 1.15.

```
2020-03-01 14:17:54.954 [ERROR][1] main.go 225: Failed to reach apiserver error=<nil>
2020-03-01 14:18:10.513 [ERROR][1] main.go 225: Failed to reach apiserver error=<nil>
2020-03-01 14:18:45.601 [ERROR][1] main.go 225: Failed to reach apiserver error=<nil>
2020-03-01 14:18:59.727 [ERROR][1] main.go 225: Failed to reach apiserver error=<nil>
2020-03-01 14:19:38.188 [ERROR][1] main.go 225: Failed to reach apiserver error=<nil>
2020-03-01 14:21:07.387 [ERROR][1] main.go 225: Failed to reach apiserver error=<nil>
2020-03-01 14:22:35.968 [ERROR][1] main.go 225: Failed to reach apiserver error=<nil>
2020-03-01 14:22:51.264 [ERROR][1] main.go 225: Failed to reach apiserver error=<nil>
2020-03-01 14:23:18.581 [ERROR][1] main.go 225: Failed to reach apiserver error=<nil>
2020-03-01 14:23:46.230 [ERROR][1] main.go 225: Failed to reach apiserver error=<nil>
2020-03-01 14:24:47.226 [ERROR][1] main.go 225: Failed to reach apiserver error=<nil>
2020-03-01 14:25:02.128 [ERROR][1] main.go 225: Failed to reach apiserver error=<nil>
2020-03-01 14:25:16.167 [ERROR][1] main.go 225: Failed to reach apiserver error=<nil>
2020-03-01 14:25:31.026 [ERROR][1] main.go 225: Failed to reach apiserver error=<nil>
2020-03-01 14:25:56.684 [ERROR][1] main.go 225: Failed to reach apiserver error=<nil>
2020-03-01 14:26:09.103 [ERROR][1] main.go 225: Failed to reach apiserver error=<nil>
2020-03-01 14:26:35.031 [ERROR][1] main.go 225: Failed to reach apiserver error=<nil>
2020-03-01 14:26:47.773 [ERROR][1] main.go 225: Failed to reach apiserver error=<nil>
2020-03-02 11:24:41.495 [ERROR][1] client.go 238: Error getting cluster information config ClusterInformation="default" error=Get https://10.252.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default: context deadline exceeded
2020-03-02 11:24:41.495 [ERROR][1] main.go 194: Failed to verify datastore error=Get https://10.252.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default: context deadline exceeded
2020-03-02 11:24:43.501 [ERROR][1] main.go 225: Failed to reach apiserver error=Get https://10.252.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default: context deadline exceeded
2020-03-02 11:25:03.508 [ERROR][1] client.go 238: Error getting cluster information config ClusterInformation="default" error=Get https://10.252.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default: context deadline exceeded
2020-03-02 11:25:03.508 [ERROR][1] main.go 194: Failed to verify datastore error=Get https://10.252.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default: context deadline exceeded
2020-03-03 01:12:41.201 [ERROR][1] main.go 225: Failed to reach apiserver error=<nil>
2020-03-04 19:39:26.062 [ERROR][1] main.go 225: Failed to reach apiserver error=<nil>
2020-03-05 15:47:12.675 [ERROR][1] main.go 225: Failed to reach apiserver error=<nil>


```

any idea what might be causing this.

**Comment by rafaelvanoni** [comment]
@iahmad-khan Can you reach your apiserver using the kubernetes service address from your nodes? This could also be a problem with kube-proxy, can you check its logs for any errors?

**Comment by kombiwagon** [comment]
@iahmad-khan tell me if you managed to deal with the described situation. I have similar situation. I have errors in 'calico-kube-controllers' pod:
[ERROR][1] main.go 234: Failed to reach apiserver error=<nil>
[ERROR][1] client.go 255: Error getting cluster information config ClusterInformation="default" error=Get https://10.43.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default: context deadline exceeded
ERROR][1] main.go 203: Failed to verify datastore error=Get https://10.43.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default: context deadline exceeded

I noticed that when these errors show up my kube-scheduler and kube-controller-manager change leadership.
I did not notice any errors in kube-proxy but i see errors in kube-apiserver:
 apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}

can anyone help me please

**Comment by caseydavenport** [comment]
> I noticed that when these errors show up my kube-scheduler and kube-controller-manager change leadership.

@kombiwagon could you explain in a bit more detail what you mean by change leadership? Is this during a rolling update of the API servers / control plan nodes?

**Comment by frendcarlo** [comment]
does anyone had a fix on this? i have the same error in microk8s cluster setup

**Comment by matlad** [comment]
I have same issue on microk8s too.
kube-scheduler and kube-controller-manager  keep restarting with errors like 

```
Jul 07 16:54:20 k8s-1 microk8s.daemon-scheduler[1125002]: k8s.io/kubernetes/cmd/kube-scheduler/app.Run.func3()
Jul 07 16:54:20 k8s-1 microk8s.daemon-scheduler[1125002]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1502
Jul 07 16:54:20 k8s-1 microk8s.daemon-scheduler[1125002]: k8s.io/kubernetes/vendor/k8s.io/klog/v2.Fatalf(...)
Jul 07 16:54:20 k8s-1 microk8s.daemon-scheduler[1125002]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:750 +0x191
Jul 07 16:54:20 k8s-1 microk8s.daemon-scheduler[1125002]: k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).printf(0x2dd3ac0, 0x3, 0x0, 0x0, 0x0, 0x0, 0x1d9a469, 0x13, 0x0, 0x0, ...)
Jul 07 16:54:20 k8s-1 microk8s.daemon-scheduler[1125002]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:975 +0x19b
Jul 07 16:54:20 k8s-1 microk8s.daemon-scheduler[1125002]: k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).output(0x2dd3ac0, 0xc000000003, 0x0, 0x0, 0xc0009181c0, 0x2cdd9be, 0x9, 0xcd, 0x0)
Jul 07 16:54:20 k8s-1 microk8s.daemon-scheduler[1125002]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1026 +0xb9
Jul 07 16:54:20 k8s-1 microk8s.daemon-scheduler[1125002]: k8s.io/kubernetes/vendor/k8s.io/klog/v2.stacks(0xc00000e001, 0xc000383400, 0x41, 0x280)
Jul 07 16:54:20 k8s-1 microk8s.daemon-scheduler[1125002]: goroutine 1 [running]:
Jul 07 16:54:20 k8s-1 microk8s.daemon-scheduler[1125002]: F0707 16:54:20.092477 1125002 server.go:205] leaderelection lost
Jul 07 16:54:20 k8s-1 microk8s.daemon-scheduler[1125002]: I0707 16:54:20.092469 1125002 leaderelection.go:278] failed to renew lease kube-system/kube-scheduler: timed out waiting for the condition
Jul 07 16:54:20 k8s-1 microk8s.daemon-scheduler[1125002]: E0707 16:54:20.092430 1125002 leaderelection.go:361] Failed to update lock: Put "https://127.0.0.1:16443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/kube-scheduler?timeout=10s": context deadline exceeded
Jul 07 16:52:37 k8s-1 microk8s.daemon-scheduler[1125002]: I0707 16:52:37.211113 1125002 leaderelection.go:253] successfully acquired lease kube-system/kube-scheduler
Jul 07 16:52:08 k8s-1 microk8s.daemon-scheduler[1125002]: E0707 16:52:08.308544 1125002 leaderelection.go:361] Failed to update lock: Operation cannot be fulfilled on leases.coordination.k8s.io "kube-scheduler": the object has been modified; please apply your changes to the latest version and try again
Jul 07 16:49:25 k8s-1 microk8s.daemon-scheduler[1125002]: I0707 16:49:25.154548 1125002 leaderelection.go:243] attempting to acquire leader lease kube-system/kube-scheduler...

```
k -n kube-system logs pod/calico-kube-controllers-847c8c99d-rbkt8 shows
```
2021-07-07 15:33:42.929 [ERROR][1] main.go 234: Failed to reach apiserver error=<nil>
2021-07-07 15:41:35.269 [ERROR][1] main.go 234: Failed to reach apiserver error=<nil>
2021-07-07 15:43:25.085 [ERROR][1] main.go 234: Failed to reach apiserver error=<nil>
2021-07-07 15:55:11.052 [ERROR][1] main.go 234: Failed to reach apiserver error=<nil>
2021-07-07 16:16:40.557 [ERROR][1] main.go 234: Failed to reach apiserver error=<nil>
```
k -n kube-system get events
```
7m15s       Warning   Unhealthy        pod/calico-kube-controllers-847c8c99d-rbkt8         Readiness probe failed: Error reaching apiserver: <nil> with http status code: 500
7m7s        Normal    LeaderElection   lease/kube-controller-manager                       k8s-3_00a859b1-619c-49d4-b440-8a1c3ffb9812 became leader
6m37s       Normal    LeaderElection   lease/kube-controller-manager                       k8s-2_8ecfb3be-3de7-48ab-af15-e22aba46b00b became leader
6m6s        Normal    LeaderElection   lease/kube-controller-manager                       k8s-3_5519c1ec-dd0a-4f9b-bdd4-b53a841c4cc7 became leader
5m36s       Normal    LeaderElection   lease/kube-controller-manager                       k8s-1_a0d9c4d0-d7e0-4eb6-a85d-1836bd322ab7 became leader
5m          Normal    LeaderElection   lease/kube-controller-manager                       k8s-2_a9e58fe9-93a3-42da-abed-df90acb99c9f became leader
4m36s       Normal    LeaderElection   lease/kube-scheduler                                k8s-1_77c46d59-e091-462a-bd1f-064242848d4b became leader
4m29s       Normal    LeaderElection   lease/kube-controller-manager                       k8s-3_5f3e4726-dd20-4ff7-9907-db0b9ee08391 became leader
3m56s       Normal    LeaderElection   lease/kube-controller-manager                       k8s-2_af79f7ae-a2cf-4e27-9e51-584b653e3a72 became leader
3m30s       Normal    LeaderElection   configmap/cert-manager-cainjector-leader-election   cert-manager-cainjector-86bc6dc648-2z7vl_1b302866-4ba1-4d29-8edb-5e613b3d2313 became leader
3m25s       Normal    LeaderElection   lease/kube-controller-manager                       k8s-1_876fdd90-5e2b-4642-9213-94e1e05fd141 became leader
2m48s       Normal    LeaderElection   lease/kube-controller-manager                       k8s-2_366fafb1-fb8c-4ca0-bf28-39008fefc435 became leader
2m50s       Normal    LeaderElection   lease/kube-scheduler                                k8s-3_7fa13fcc-d69a-4148-8645-12a4f755a031 became leader
2m12s       Normal    LeaderElection   lease/kube-controller-manager                       k8s-3_3dec2540-5099-4d4f-bcc5-fbbd1de77210 became leader
101s        Normal    LeaderElection   lease/kube-scheduler                                k8s-1_9d10ec28-254c-4b35-b34f-82c9bd26923a became leader
99s         Normal    LeaderElection   lease/kube-controller-manager                       k8s-2_13991ba0-0df5-4249-89cc-70cc91807ef6 became leader
67s         Normal    LeaderElection   lease/kube-controller-manager                       k8s-3_87d6d737-9b0c-489f-b1c9-06c10e02e8b2 became leader
36s         Normal    LeaderElection   lease/kube-controller-manager                       k8s-1_fc363c83-756e-4c35-b880-5491bc17b110 became leader
7s          Normal    LeaderElection   lease/kube-controller-manager                       k8s-3_7abb3b8b-35f1-4454-8005-bc60caac826a became leader
```
k -n kube-system logs calico-node-9pvnh 
```
2021-07-07 09:12:35.831 [INFO][9] startup.go 290: Early log level set to info
2021-07-07 09:12:35.831 [INFO][9] startup.go 306: Using NODENAME environment for node name
2021-07-07 09:12:35.831 [INFO][9] startup.go 318: Determined node name: k8s-1
2021-07-07 09:12:35.832 [INFO][9] startup.go 350: Checking datastore connection
2021-07-07 09:12:36.309 [INFO][9] startup.go 374: Datastore connection verified
2021-07-07 09:12:36.309 [INFO][9] startup.go 102: Datastore is ready
2021-07-07 09:12:37.723 [INFO][9] reachaddr.go 46: Auto-detected address by connecting to remote Destination="10.10.0.201" IP=10.10.0.201
2021-07-07 09:12:37.723 [INFO][9] reachaddr.go 55: Checking interface CIDRs Name="vmbr1"
2021-07-07 09:12:37.723 [INFO][9] reachaddr.go 57: Checking CIDR CIDR="10.10.0.201/24"
2021-07-07 09:12:37.723 [INFO][9] reachaddr.go 59: Found matching interface CIDR CIDR="10.10.0.201/24"
2021-07-07 09:12:37.723 [INFO][9] startup.go 678: Using autodetected IPv4 address 10.10.0.201/24, detected by connecting to 10.10.0.201
2021-07-07 09:12:37.723 [INFO][9] startup.go 715: No AS number configured on node resource, using global value
2021-07-07 09:12:37.723 [INFO][9] startup.go 171: Setting NetworkUnavailable to False
2021-07-07 09:12:39.724 [WARNING][9] startup.go 1176: Failed to set NetworkUnavailable to False; will retry error=Patch https://10.152.183.1:443/api/v1/nodes/k8s-1/status?timeout=2s: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
2021-07-07 09:12:41.724 [WARNING][9] startup.go 1176: Failed to set NetworkUnavailable to False; will retry error=Patch https://10.152.183.1:443/api/v1/nodes/k8s-1/status?timeout=2s: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
2021-07-07 09:12:43.724 [WARNING][9] startup.go 1176: Failed to set NetworkUnavailable to False; will retry error=Patch https://10.152.183.1:443/api/v1/nodes/k8s-1/status?timeout=2s: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
2021-07-07 09:12:45.725 [WARNING][9] startup.go 1176: Failed to set NetworkUnavailable to False; will retry error=Patch https://10.152.183.1:443/api/v1/nodes/k8s-1/status?timeout=2s: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
2021-07-07 09:12:47.725 [WARNING][9] startup.go 1176: Failed to set NetworkUnavailable to False; will retry error=Patch https://10.152.183.1:443/api/v1/nodes/k8s-1/status?timeout=2s: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
2021-07-07 09:12:49.725 [WARNING][9] startup.go 1176: Failed to set NetworkUnavailable to False; will retry error=Patch https://10.152.183.1:443/api/v1/nodes/k8s-1/status?timeout=2s: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
2021-07-07 09:12:51.726 [WARNING][9] startup.go 1176: Failed to set NetworkUnavailable to False; will retry error=Patch https://10.152.183.1:443/api/v1/nodes/k8s-1/status?timeout=2s: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
2021-07-07 09:12:53.726 [WARNING][9] startup.go 1176: Failed to set NetworkUnavailable to False; will retry error=Patch https://10.152.183.1:443/api/v1/nodes/k8s-1/status?timeout=2s: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
2021-07-07 09:12:55.726 [WARNING][9] startup.go 1176: Failed to set NetworkUnavailable to False; will retry error=Patch https://10.152.183.1:443/api/v1/nodes/k8s-1/status?timeout=2s: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
2021-07-07 09:12:57.727 [WARNING][9] startup.go 1176: Failed to set NetworkUnavailable to False; will retry error=Patch https://10.152.183.1:443/api/v1/nodes/k8s-1/status?timeout=2s: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
2021-07-07 09:12:59.727 [WARNING][9] startup.go 1176: Failed to set NetworkUnavailable to False; will retry error=Patch https://10.152.183.1:443/api/v1/nodes/k8s-1/status?timeout=2s: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
2021-07-07 09:13:01.727 [WARNING][9] startup.go 1176: Failed to set NetworkUnavailable to False; will retry error=Patch https://10.152.183.1:443/api/v1/nodes/k8s-1/status?timeout=2s: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
2021-07-07 09:13:03.728 [WARNING][9] startup.go 1176: Failed to set NetworkUnavailable to False; will retry error=Patch https://10.152.183.1:443/api/v1/nodes/k8s-1/status?timeout=2s: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
2021-07-07 09:13:05.728 [WARNING][9] startup.go 1176: Failed to set NetworkUnavailable to False; will retry error=Patch https://10.152.183.1:443/api/v1/nodes/k8s-1/status?timeout=2s: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
2021-07-07 09:13:07.728 [WARNING][9] startup.go 1176: Failed to set NetworkUnavailable to False; will retry error=Patch https://10.152.183.1:443/api/v1/nodes/k8s-1/status?timeout=2s: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
2021-07-07 09:13:07.728 [ERROR][9] startup.go 174: Unable to set NetworkUnavailable to False error=timed out patching node, last error was: Patch https://10.152.183.1:443/api/v1/nodes/k8s-1/status?timeout=2s: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
2021-07-07 09:13:08.529 [INFO][9] startup.go 764: found v6= in the kubeadm config map
2021-07-07 09:13:08.796 [INFO][9] startup.go 598: FELIX_IPV6SUPPORT is false through environment variable
2021-07-07 09:13:09.149 [INFO][9] startup.go 215: Using node name: k8s-1
2021-07-07 09:13:13.572 [INFO][145] allocateip.go 144: Current address is still valid, do nothing currentAddr="10.1.231.192" type="vxlanTunnelAddress"
CALICO_NETWORKING_BACKEND is vxlan - no need to run a BGP daemon
Calico node started successfully
```

**Comment by pinahar** [comment]
Seeing same issue as @matlad.
Any workaround or fix?
