### ISSUE TITLE
New Cluster Crashes After Adding Calico CNI

### ISSUE THREAD

**Issue by ThePieMonster** [projectcalico/calico#4336]
**What happened**:

Created a fresh Kubernetes cluster using `kubeadm init --config /home/kube/kubeadmn-config.yaml --upload-certs` and then joining the 2nd control plane node by running the below.

    kubeadm join VIP:6443 --token <token> \
        --discovery-token-ca-cert-hash sha256:<hash> \
        --control-plane --certificate-key <key> \
    	--v=5

After both control plane nodes were added to the cluster and in a Not Ready state the `kubectl apply -f https://docs.projectcalico.org/v3.17/manifests/calico.yaml` command was run.

Afterwards I could no longer reach the kube api on either of the control plane nodes.

Running `systemctl status kubelet.service` on the first node gives the following output.

```
● kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/lib/systemd/system/kubelet.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/kubelet.service.d
           └─10-kubeadm.conf
   Active: active (running) since Fri 2021-01-22 23:17:33 UTC; 1h 44min ago
     Docs: https://kubernetes.io/docs/home/
 Main PID: 29599 (kubelet)
    Tasks: 16 (limit: 2317)
   CGroup: /system.slice/kubelet.service
           └─29599 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --network-plugin=cni --pod-infra-container-image=k8s.gcr.io/pause:3.2

Jan 23 01:01:37 k8s-master-0 kubelet[29599]: E0123 01:01:37.091681   29599 event.go:273] Unable to write event: '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"etcd-k8s-master-0.165cb29ca2653951", GenerateName:"", Namespace:"kube-system", SelfLink:"", UID:"", ResourceVersion:"2598", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"etcd-k8s-master-0", UID:"a9f805c0eb22e024f35cb6a5e3768516", APIVersion:"v1", ResourceVersion:"", FieldPath:"spec.containers{etcd}"}, Reason:"Unhealthy", Message:"Liveness probe failed: HTTP probe failed with statuscode: 503", Source:v1.EventSource{Component:"kubelet", Host:"k8s-master-0"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:63746955952, loc:(*time.Location)(0x70c9020)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xbffaf9831ddd1b4b, ext:4479289933944, loc:(*time.Location)(0x70c9020)}}, Count:12, Type:"Warning", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'Patch "https://10.1.50.250:6443/api/v1/namespaces/kube-system/events/etcd-k8s-master-0.165cb29ca2653951": EOF'(may retry after sleeping)
Jan 23 01:01:39 k8s-master-0 kubelet[29599]: I0123 01:01:39.294013   29599 scope.go:95] [topologymanager] RemoveContainer - Container ID: 80e0b7be20c8bb383dd3f5c260530b5255e1a41ad31154a6577369d8a0688781
Jan 23 01:01:39 k8s-master-0 kubelet[29599]: E0123 01:01:39.296092   29599 pod_workers.go:191] Error syncing pod a9f805c0eb22e024f35cb6a5e3768516 ("etcd-k8s-master-0_kube-system(a9f805c0eb22e024f35cb6a5e3768516)"), skipping: failed to "StartContainer" for "etcd" with CrashLoopBackOff: "back-off 5m0s restarting failed container=etcd pod=etcd-k8s-master-0_kube-system(a9f805c0eb22e024f35cb6a5e3768516)"
Jan 23 01:01:40 k8s-master-0 kubelet[29599]: E0123 01:01:40.760385   29599 kubelet_node_status.go:447] Error updating node status, will retry: error getting node "k8s-master-0": Get "https://10.1.50.250:6443/api/v1/nodes/k8s-master-0?timeout=10s": context deadline exceeded
Jan 23 01:01:40 k8s-master-0 kubelet[29599]: E0123 01:01:40.761789   29599 kubelet_node_status.go:434] Unable to update node status: update node status exceeds retry count
Jan 23 01:01:41 k8s-master-0 kubelet[29599]: I0123 01:01:41.294078   29599 scope.go:95] [topologymanager] RemoveContainer - Container ID: fb17bf8aa74f9dfd7206fb077653f6792664ddd7c740eac695a93fb5226e72d0
Jan 23 01:01:41 k8s-master-0 kubelet[29599]: E0123 01:01:41.296260   29599 pod_workers.go:191] Error syncing pod 42b84c75652fa98ba1d7dc98a07912c9 ("kube-apiserver-k8s-master-0_kube-system(42b84c75652fa98ba1d7dc98a07912c9)"), skipping: failed to "StartContainer" for "kube-apiserver" with CrashLoopBackOff: "back-off 5m0s restarting failed container=kube-apiserver pod=kube-apiserver-k8s-master-0_kube-system(42b84c75652fa98ba1d7dc98a07912c9)"
Jan 23 01:01:42 k8s-master-0 kubelet[29599]: I0123 01:01:42.006319   29599 trace.go:205] Trace[184647399]: "Reflector ListAndWatch" name:object-"kube-system"/"kube-proxy-token-5fzkw" (23-Jan-2021 01:01:31.987) (total time: 10018ms):
Jan 23 01:01:42 k8s-master-0 kubelet[29599]: Trace[184647399]: [10.018725131s] [10.018725131s] END
Jan 23 01:01:42 k8s-master-0 kubelet[29599]: E0123 01:01:42.007748   29599 reflector.go:138] object-"kube-system"/"kube-proxy-token-5fzkw": Failed to watch *v1.Secret: failed to list *v1.Secret: an error on the server ("") has prevented the request from succeeding (get secrets)

```

Command on first control plane node `ls -l /etc/cni/net.d/`

```
10-calico.conflist
calico-kubeconfig
```

**What you expected to happen**:

CNI gets added and cluster still functional

**How to reproduce it (as minimally and precisely as possible)**:

1. Setup a new cluster
2. Add a second control plane node
3. Add the CNI

**Environment**:
- Kubernetes version (use `kubectl version`): 1.20.1
- Cloud provider or hardware configuration: VMWare
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04
- Kernel (e.g. `uname -a`): 4.15.0-130-generic

**Comment by JESWINKNINAN** [comment]
@ThePieMonster I can see from the status which you have shared for kube-api server is in CrashLoopBackOff state, can you please share the API server logs..

**Comment by ThePieMonster** [comment]
> @ThePieMonster I can see from the status which you have shared for kube-api server is in CrashLoopBackOff state, can you please share the API server logs..

How would you dump just the api server logs?

**Comment by ThePieMonster** [comment]
@JESWINKNINAN Any commands that use `kubectl` such as `kubectl get nodes` return the following.

> Error from server (InternalError): an error on the server ("") has prevented the request from succeeding (get nodes)

**Comment by ThePieMonster** [comment]
@JESWINKNINAN I used the below to attempt to get logs from the api server but didn't get any logs back.

`docker ps -a | grep k8s_kube-apiserver`
`2294c7012018        75c7f7112080                "kube-apiserver --ad…"   4 minutes ago       Exited (1) 4 minutes ago                        k8s_kube-apiserver_kube-apiserver-k8s-master-0_kube-syst`

`docker logs 2294c7012018`
_No output_

**Comment by JESWINKNINAN** [comment]
Please increase the verbosity in the Master Node Kubelet to trace the error.

What does the Kubelet says regarding the same?

`journctl -u kubelet.server `

also, check whether anything is in `/var/log/kube-apiserver.log`

**Comment by ThePieMonster** [comment]
@JESWINKNINAN 

journctl is not found
`root@k8s-master-0:~# journctl -u kubelet.server`
`journctl: command not found`

kube-apiserver.log does not exist. 
`root@k8s-master-0:~# ls -l /var/log/`
```
total 44448
-rw-r--r--  1 root      root               27592 Jan 23 18:20 alternatives.log
drwxr-xr-x  2 root      root                4096 Jan 23 18:42 apt
-rw-r-----  1 syslog    adm                14941 Jan 24 18:17 auth.log
-rw-r--r--  1 root      root               56751 Aug  6 22:36 bootstrap.log
-rw-rw----  1 root      utmp                 384 Jan 23 21:12 btmp
drwxr-xr-x  3 root      root                4096 Jan 23 20:59 calico
-rw-r--r--  1 syslog    adm               184813 Jan 23 18:35 cloud-init.log
-rw-r--r--  1 root      root               10345 Jan 23 18:35 cloud-init-output.log
drwxr-xr-x  2 root      root                4096 Jan 24 19:00 containers
drwxr-xr-x  2 root      root                4096 Jul  9  2020 dist-upgrade
-rw-r--r--  1 root      root              566739 Jan 23 18:42 dpkg.log
-rw-r--r--  1 root      root               32032 Jan 23 18:34 faillog
drwxr-xr-x  3 root      root                4096 Jan 23 18:21 installer
drwxr-sr-x+ 3 root      systemd-journal     4096 Jan 23 18:22 journal
-rw-r-----  1 syslog    adm               415484 Jan 24 11:19 kern.log
drwxr-xr-x  2 landscape landscape           4096 Jan 23 18:33 landscape
-rw-rw-r--  1 root      utmp              292292 Jan 23 18:37 lastlog
drwxr-xr-x  2 root      root                4096 Nov 23  2018 lxd
drwxr-xr-x  9 root      root                4096 Jan 23 20:59 pods
-rw-r-----  1 syslog    adm             44120110 Jan 24 19:01 syslog
-rw-------  1 root      root               64064 Jan 23 18:34 tallylog
drwxr-x---  2 root      adm                 4096 Jan 23 18:23 unattended-upgrades
-rw-------  1 root      root                 685 Jan 23 18:32 vmware-network.log
-rw-------  1 root      root                1719 Jan 23 18:35 vmware-vmsvc-root.1.log
-rw-------  1 root      root                2042 Jan 23 18:22 vmware-vmsvc-root.2.log
-rw-------  1 root      root                 986 Jan 23 18:35 vmware-vmsvc-root.log
-rw-------  1 root      root                 676 Jan 23 18:35 vmware-vmtoolsd-root.log
-rw-rw-r--  1 root      utmp                6528 Jan 23 18:37 wtmp
```

Since the Control Plane Nodes have a issue with the API Server the VIP at IP .250 won't send traffic. So I changed the .kube\config IP to the direct IP of .4. Then ran `kubectl get nodes --v=10`.


```
I0124 19:09:51.119307   22248 round_trippers.go:445] GET https://10.1.50.4:6443/api?timeout=32s  in 0 milliseconds
I0124 19:09:51.119572   22248 round_trippers.go:451] Response Headers:
I0124 19:09:51.119741   22248 cached_discovery.go:121] skipped caching discovery info due to Get "https://10.1.50.4:6443/api?timeout=32s": dial tcp 10.1.50.4:6443: connect: connection refused
I0124 19:09:51.119930   22248 helpers.go:234] Connection error: Get https://10.1.50.4:6443/api?timeout=32s: dial tcp 10.1.50.4:6443: connect: connection refused
F0124 19:09:51.123124   22248 helpers.go:115] The connection to the server 10.1.50.4:6443 was refused - did you specify the right host or port?
goroutine 1 [running]:
k8s.io/kubernetes/vendor/k8s.io/klog/v2.stacks(0xc0000b0001, 0xc00054f8c0, 0x90, 0x203)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1026 +0xb9
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).output(0x2a6c040, 0xc000000003, 0x0, 0x0, 0xc0003ce230, 0x284c16b, 0xa, 0x73, 0x40e200)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:975 +0x19b
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).printDepth(0x2a6c040, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x2, 0xc000464b00, 0x1, 0x1)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:732 +0x16f
k8s.io/kubernetes/vendor/k8s.io/klog/v2.FatalDepth(...)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1488
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util.fatal(0xc0007a2460, 0x61, 0x1)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:93 +0x26e
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util.checkErr(0x1ced9a0, 0xc0003d6b10, 0x1bb70f8)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:188 +0x945
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util.CheckErr(...)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:115
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/get.NewCmdGet.func1(0xc0004918c0, 0xc00032c7e0, 0x1, 0x2)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/get/get.go:167 +0x159
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc0004918c0, 0xc00032c7a0, 0x2, 0x2, 0xc0004918c0, 0xc00032c7a0)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:854 +0x2c2
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0000dcdc0, 0xc0000b2120, 0xc0000b6040, 0x4)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:958 +0x375
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:895
main.main()
        _output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:49 +0x21d

goroutine 18 [chan receive]:
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).flushDaemon(0x2a6c040)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1169 +0x8b
created by k8s.io/kubernetes/vendor/k8s.io/klog/v2.init.0
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:417 +0xdf

goroutine 6 [select]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x1bb7018, 0x1cec100, 0xc0003d6000, 0x1, 0xc00008ab40)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:167 +0x149
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x1bb7018, 0x12a05f200, 0x0, 0x1, 0xc00008ab40)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0x1bb7018, 0x12a05f200, 0xc00008ab40)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
created by k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/util/logs.InitLogs
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/util/logs/logs.go:51 +0x96
```

**Comment by song-jiang** [comment]
@ThePieMonster Do you still see same issue?

**Comment by ThePieMonster** [comment]
> @ThePieMonster Do you still see same issue?

Ended up switching over to a MicroK8S solution since this issue was not able to be resolved.
