### ISSUE TITLE
rktnetes + calico + flannel = Container not found

### ISSUE THREAD

**Issue by Promaethius** [projectcalico/calico#457]
I'm using a modified version of CoreOS's generic-controller.sh script to deploy rktnetes, calico, and flannel onto bare metal servers.

https://github.com/Promaethius/coreos-kubernetes/blob/master/multi-node/generic/controller-install.sh

The error that I continue to see is
```
2017-01-21 00:46:31,002 4235 [kube-system/heapster-v1.2.0-216693398-n5nrv] INFO Starting Calico CNI plugin execution
2017-01-21 00:46:31,012 4235 [kube-system/heapster-v1.2.0-216693398-n5nrv] ERROR Container `ed833216-df72-11e6-a1c0-0cc47ab58776` was not found.
2017-01-21 00:46:31,013 4235 [kube-system/heapster-v1.2.0-216693398-n5nrv] ERROR Unhandled Exception killed plugin
Traceback (most recent call last):
  File "<string>", line 773, in main
  File "<string>", line 181, in execute
  File "<string>", line 200, in add
  File "calico_cni/container_engines.py", line 52, in uses_host_networking
  File "calico_cni/container_engines.py", line 70, in _docker_inspect
KeyError: 'Unable to inspect container.'
2017-01-21 00:46:31,014 4235 [kube-system/heapster-v1.2.0-216693398-n5nrv] ERROR CNI Error:
{
  "msg": "Unhandled Exception killed plugin",
  "cniVersion": "0.1.0",
  "code": 100,
  "details": null
}
Traceback (most recent call last):
  File "<string>", line 773, in main
  File "<string>", line 181, in execute
  File "<string>", line 200, in add
  File "calico_cni/container_engines.py", line 52, in uses_host_networking
  File "calico_cni/container_engines.py", line 70, in _docker_inspect
KeyError: 'Unable to inspect container.'
2017-01-21 00:46:31,014 4235 [kube-system/heapster-v1.2.0-216693398-n5nrv] INFO Calico CNI execution complete, rc=100
```

You can view the yaml files I'm using for deployment in the controller script above.

I'm at the end of my rope trying to find the answer and I'm hoping anyone out there has an answer for me.

**Comment by caseydavenport** [comment]
@Promaethius that error message looks like it's coming from a pretty old version of the CNI plugin that didn't support rktnetes.

To use rktnetes you'll need to upgrade to a more recent release.

**Comment by Promaethius** [comment]
Ah ok I heard a similar response elsewhere since it's the python version. Could you point me to the latest docker image pushes? I've been pulling the latest from quay.io.

**Comment by djosborne** [comment]
@Promaethius latest from quay.io should give you v1.5.5 which is the latest golang build:
```
$ docker run  quay.io/calico/cni:latest calico -v
v1.5.5
```

But you can try manually setting to `quay.io/calico/cni:v1.5.5` just to be sure

**Comment by djosborne** [comment]
Also be certain that you are using the CNI binaries that `calico/cni` is installing. There's a few distribution methods for kubernetes which come pre-packaged with Calico's CNI binaries. If you're using a containerized kubernetes deployment, its possible the container is using the outdated, packaged cni binaries in the container, while the up-to-date ones are being installed but unused on the host.

**Comment by djosborne** [comment]
@Promaethius going to close since we haven't heard from you for some time. Do comment / reopen if this didn't resolve your issue.
