### ISSUE TITLE
kubectl server-side apply: Error from server: no serializer defined for application/yaml

### ISSUE THREAD

**Issue by ribbybibby** [projectcalico/calico#4959]
## Expected Behavior

I would expect to be able to apply Calico resources with `kubectl apply --server-side`.

## Current Behavior

I receive this error when trying to apply `projectcalico.org/v3` resources with `kubectl apply --server-side`:
```
Error from server: no serializer defined for application/yaml
```

And in the calico-apiserver logs:
```
calico-apiserver-67556cc6b6-mdtnk calico-apiserver E0923 12:20:44.176422       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"no serializer defined for application/yaml"}: no serializer defined for application/yaml
calico-apiserver-67556cc6b6-mdtnk calico-apiserver I0923 12:20:44.177129       1 httplog.go:89] "HTTP" verb="PATCH" URI="/apis/projectcalico.org/v3/bgpconfigurations/default?fieldManager=kubectl&force=true" latency="11.899416ms" userAgent="kubectl/v1.21.0 (linux/amd64) kubernetes/cb303e6" srcIP="10.4.4.1:22738" resp=500 statusStack="\ngoroutine 1250187 [running]:\nk8s.io/apiserver/pkg/server/httplog.(*respLogger).recordStatus(0xc00090caf0, 0x1f4)\n\t/go/pkg/mod/k8s.io/apiserver@v0.21.0-rc.0/pkg/server/httplog/httplog.go:237 +0xcf\nk8s.io/apiserver/pkg/server/httplog.(*respLogger).WriteHeader(0xc00090caf0, 0x1f4)\n\t/go/pkg/mod/k8s.io/apiserver@v0.21.0-rc.0/pkg/server/httplog/httplog.go:216 +0x35\nk8s.io/apiserver/pkg/server/filters.(*baseTimeoutWriter).WriteHeader(0xc000f502a0, 0x1f4)\n\t/go/pkg/mod/k8s.io/apiserver@v0.21.0-rc.0/pkg/server/filters/timeout.go:222 +0xb2\nk8s.io/apiserver/pkg/endpoints/metrics.(*ResponseWriterDelegator).WriteHeader(0xc0012ece10, 0x1f4)\n\t/go/pkg/mod/k8s.io/apiserver@v0.21.0-rc.0/pkg/endpoints/metrics/metrics.go:537 +0x45\nk8s.io/apiserver/pkg/endpoints/handlers/responsewriters.(*deferredResponseWriter).Write(0xc00131cc00, 0xc001530000, 0x87, 0x13912, 0x0, 0x0, 0x0)\n\t/go/pkg/mod/k8s.io/apiserver@v0.21.0-rc.0/pkg/endpoints/handlers/responsewriters/writers.go:228 +0x2fd\nencoding/json.(*Encoder).Encode(0xc000c892b8, 0x2305c80, 0xc00137cbe0, 0x0, 0x40f75b)\n\t/usr/local/go/src/encoding/json/stream.go:231 +0x1cb\nk8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).doEncode(0xc000a28f50, 0x2694c20, 0xc00137cbe0, 0x2681900, 0xc00131cc00, 0x0, 0x0)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.21.0-rc.0/pkg/runtime/serializer/json/json.go:327 +0x2e9\nk8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).Encode(0xc000a28f50, 0x2694c20, 0xc00137cbe0, 0x2681900, 0xc00131cc00, 0x1e0ce64, 0x6)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.21.0-rc.0/pkg/runtime/serializer/json/json.go:301 +0x169\nk8s.io/apimachinery/pkg/runtime/serializer/versioning.(*codec).doEncode(0xc00137cc80, 0x2694c20, 0xc00137cbe0, 0x2681900, 0xc00131cc00, 0x0, 0x0)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.21.0-rc.0/pkg/runtime/serializer/versioning/versioning.go:228 +0x396\nk8s.io/apimachinery/pkg/runtime/serializer/versioning.(*codec).Encode(0xc00137cc80, 0x2694c20, 0xc00137cbe0, 0x2681900, 0xc00131cc00, 0xc000b0fdc0, 0x269d0e0)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.21.0-rc.0/pkg/runtime/serializer/versioning/versioning.go:184 +0x170\nk8s.io/apiserver/pkg/endpoints/handlers/responsewriters.SerializeObject(0x237805d, 0x10, 0x7f0b884e7e40, 0xc00137cc80, 0x26d06e0, 0xc000680b88, 0xc00192b400, 0x1f4, 0x2694c20, 0xc00137cbe0)\n\t/go/pkg/mod/k8s.io/apiserver@v0.21.0-rc.0/pkg/endpoints/handlers/responsewriters/writers.go:106 +0x45a\nk8s.io/apiserver/pkg/endpoints/handlers/responsewriters.WriteObjectNegotiated(0x26bfe20, 0xc00043dca0, 0x26d2f20, 0x360a0f0, 0x237a2fd, 0x11, 0x2365f32, 0x2, 0x26d06e0, 0xc000680b88, ...)\n\t/go/pkg/mod/k8s.io/apiserver@v0.21.0-rc.0/pkg/endpoints/handlers/responsewriters/writers.go:275 +0x572\nk8s.io/apiserver/pkg/endpoints/handlers/responsewriters.ErrorNegotiated(0x267f9e0, 0xc000fd0530, 0x26bfe20, 0xc00043dca0, 0x237a2fd, 0x11, 0x2365f32, 0x2, 0x26d06e0, 0xc000680b88, ...)\n\t/go/pkg/mod/k8s.io/apiserver@v0.21.0-rc.0/pkg/endpoints/handlers/responsewriters/writers.go:294 +0x16f\nk8s.io/apiserver/pkg/endpoints/handlers.(*RequestScope).err(...)\n\t/go/pkg/mod/k8s.io/apiserver@v0.21.0-rc.0/pkg/endpoints/handlers/rest.go:106\nk8s.io/apiserver/pkg/endpoints/handlers.PatchResource.func1(0x26d06e0, 0xc000680b88, 0xc00192b400)\n\t/go/pkg/mod/k8s.io/apiserver@v0.21.0-rc.0/pkg/endpoints/handlers/patch.go:137 +0x264c\nk8s.io/apiserver/pkg/endpoints.restfulPatchResource.func1(0xc0012ecd80, 0xc00093a150)\n\t/go/pkg/mod/k8s.io/apiserver@v0.21.0-rc.0/pkg/endpoints/installer.go:1227 +0x99\nk8s.io/apiserver/pkg/endpoints/metrics.InstrumentRouteFunc.func1(0xc0012ecd80, 0xc00093a150)\n\t/go/pkg/mod/k8s.io/apiserver@v0.21.0-rc.0/pkg/endpoints/metrics/metrics.go:428 +0x2d5\ngithub.com/emicklei/go-restful.(*Container).dispatch(0xc0005df560, 0x7f0b884e7db0, 0xc001016850, 0xc00192b400)\n\t/go/pkg/mod/github.com/emicklei/go-restful@v2.11.2-0.20200112161605-a7c079c43d51+incompatible/container.go:285 +0x9fa\ngithub.com/emicklei/go-restful.(*Container).Dispatch(...)\n\t/go/pkg/mod/github.com/emicklei/go-restful@v2.11.2-0.20200112161605-a7c079c43d51+incompatible/container.go:199\nk8s.io/apiserver/pkg/server.director.ServeHTTP(0x236d556, 0x9, 0xc0005df560, 0xc000177730, 0x7f0b884e7db0, 0xc001016850, 0xc00192b400)\n\t/go/pkg/mod/k8s.io/apiserver@v0.21.0-rc.0/pkg/server/handler.go:146 +0x5de\nk8s.io/apiserver/pkg/endpoints/filterlatency.trackCompleted.func1(0x7f0b884e7db0, 0xc001016850, 0xc00192b400)\n\t/go/pkg/mod/k8s.io/apiserver@v0.21.0-rc.0/pkg/endpoints/filterlatency/filterlatency.go:95 +0x193\nnet/http.HandlerFunc.ServeHTTP(0xc0005f1320, 0x7f0b884e7db0, 0xc001016850, 0xc00192b400)\n\t/usr/local/go/src/net/http/server.go:2042 +0x44\nk8s.io/apiserver/pkg/endpoints/filters.WithAuthorization.func1(0x7f0b884e7db0, 0xc001016850, 0xc00192b400)\n\t/go/pkg/mod/k8s.io/apiserver@v0.21.0-rc.0/pkg/endpoints/filters/authorization.go:64 +0x5ba\nnet/http.HandlerFunc.ServeHTTP(0xc0004ba1c0, 0x7f0b884e7db0, 0xc001016850, 0xc00192b400)\n\t/usr/local/go/src/net/http/server.go:2042 +0x44\nk8s.io/apiserver/pkg/endpoints/filterlatency.trackStarted.func1(0x7f0b884e7db0, 0xc001016850, 0xc00192b400)\n\t/go/pkg/mod/k8s.io/apiserver@v0.21.0-rc.0/pkg/endpoints/filterlatency/filterlatency.go:71 +0x186\nnet/http.HandlerFunc.ServeHTTP(0xc0004ba200, 0x7f0b884e7db0, 0xc001016850, 0xc00192b400)\n\t/usr/local/go/src/net/http/server.go:2042 +0x44\nk8s.io/apiserver/pkg/server/filters.WithMaxInFlightLimit.func1(0x7f0b884e7db0, 0xc001016850, 0xc00192b400)\n\t/go/pkg/mod/k8s.io/apiserver@v0.21.0-rc.0/pkg/server/filters/maxinflight.go:184 +0x676\nnet/http.HandlerFunc.ServeHTTP(0xc0005f1350, 0x7f0b884e7db0, 0xc001016850, 0xc00192b400)\n\t/usr/local/go/src/net/http/server.go:2042 +0x44\nk8s.io/apiserver/pkg/endpoints/filterlatency.trackCompleted.func1(0x7f0b884e7db0, 0xc001016850, 0xc00192b400)\n\t/go/pkg/mod/k8s.io/apiserver@v0.21.0-rc.0/pkg/endpoints/filterlatency/filterlatency.go:95 +0x193\nnet/http.HandlerFunc.ServeHTTP(0xc0005f1380, 0x7f0b884e7db0, 0xc001016850, 0xc00192b400)\n\t/usr/local/go/src/net/http/server.go:2042 +0x44\nk8s.io/apiserver/pkg/endpoints/filters.WithImpersonation.func1(0x7f0b884e7db0, 0xc001016850, 0xc00192b400)\n\t/go/pkg/mod/k8s.io/apiserver@v0.21.0-rc.0/pkg/endpoints/filters/impersonation.go:50 +0x2446\nnet/http.HandlerFunc.ServeHTTP(0xc0004ba540, 0x7f0b884e7db0, 0xc001016850, 0xc00192b400)\n\t/usr/local/go/src/net/http/server.go:2042 +0x44\nk8s.io/apiserver/pkg/endpoints/filterlatency.trackStarted.func1(0x7f0b884e7db0, 0xc001016850, 0xc00192b400)\n\t/go/pkg/mod/k8s.io/apiserver@v0.21.0-rc.0/pkg/endpoints/filterlatency/filterlatency.go:71 +0x186\nnet/http.HandlerFunc.ServeHTTP(0xc0004ba580, 0x7f0b884e7db0, 0xc001016850, 0xc00192b400)\n\t/usr/local/go/src/net/http/server.go:2042 +0x44\nk8s.io/apiserver/pkg/endpoints/filterlatency.trackCompleted.func1(0x7f0b884e7db0, 0xc001016850, 0xc00192b400)\n\t/go/pkg/mod/k8s.io/apiserver@v0.21.0-rc.0/pkg/endpoints/filterlatency/filterlatency.go:95 +0x193\nnet/http.HandlerFunc.ServeHTTP(0xc0005f13b0, 0x7f0b884e7db0, 0xc001016850, 0xc00192b400)\n\t/usr/local/go/src/net/http/server.go:2042 +0x44\nk8s.io/apiserver/pkg/endpoints/filterlatency.trackStarted.func1(0x7f0b884e7db0, 0xc001016850, 0xc00192b400)\n\t/go/pkg/mod/k8s.io/apiserver@v0.21.0-rc.0/pkg/endpoints/filterlatency/filterlatency.go:71 +0x186\nnet/http.HandlerFunc.ServeHTTP(0xc0004ba5c0, 0x7f0b884e7db0, 0xc001016850, 0xc00192b400)\n\t/usr/local/go/src/net/http/server.go:2042 +0x44\nk8s.io/apiserver/pkg/endpoints/filterlatency.trackCompleted.func1(0x7f0b884e7db0, 0xc001016850, 0xc00192b400)\n\t/go/pkg/mod/k8s.io/apiserver@v0.21.0-rc.0/pkg/endpoints/filterlatency/filterlatency.go:95 +0x193\nnet/http.HandlerFunc.ServeHTTP(0xc0005f1410, 0x7f0b884e7db0, 0xc001016850, 0xc00192b400)\n\t/usr/local/go/src/net/http/server.go:2042 +0x44\nk8s.io/apiserver/pkg/endpoints/filters.withAuthentication.func1(0x7f0b884e7db0, 0xc001016850, 0xc00192b400)\n\t/go/pkg/mod/k8s.io/apiserver@v0.21.0-rc.0/pkg/endpoints/filters/authentication.go:80 +0x748\nnet/http.HandlerFunc.ServeHTTP(0xc0001b77a0, 0x7f0b884e7db0, 0xc001016850, 0xc00192b300)\n\t/usr/local/go/src/net/http/server.go:2042 +0x44\nk8s.io/apiserver/pkg/endpoints/filterlatency.trackStarted.func1(0x7f0b884e7db0, 0xc001016850, 0xc00192b200)\n\t/go/pkg/mod/k8s.io/apiserver@v0.21.0-rc.0/pkg/endpoints/filterlatency/filterlatency.go:80 +0x38a\nnet/http.HandlerFunc.ServeHTTP(0xc0004ba600, 0x7f0b884e7db0, 0xc001016850, 0xc00192b200)\n\t/usr/local/go/src/net/http/server.go:2042 +0x44\nk8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1(0xc000c5ad80, 0xc00000d200, 0x26d77a0, 0xc001016850, 0xc00192b200)\n\t/go/pkg/mod/k8s.io/apiserver@v0.21.0-rc.0/pkg/server/filters/timeout.go:107 +0xb8\ncreated by k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP\n\t/go/pkg/mod/k8s.io/apiserver@v0.21.0-rc.0/pkg/server/filters/timeout.go:93 +0x1ec\n" addedInfo="\nlogging error output: \"{\\\"kind\\\":\\\"Status\\\",\\\"apiVersion\\\":\\\"v1\\\",\\\"metadata\\\":{},\\\"status\\\":\\\"Failure\\\",\\\"message\\\":\\\"no serializer defined for application/yaml\\\",\\\"code\\\":500}\\n\"\n"
```

It works fine without the `--server-side` flag:
```
$ kubectl apply -f bgp.yaml
bgpconfiguration.projectcalico.org/default unchanged
```

## Steps to Reproduce
With `bgp.yaml`:
```
apiVersion: projectcalico.org/v3
kind: BGPConfiguration
metadata:
  name: default
spec:
  logSeverityScreen: Error
  nodeToNodeMeshEnabled: false
  asNumber: 64513
```
Run:
```
$ kubectl apply --server-side -f bgp.yaml
Error from server: no serializer defined for application/yaml
```

## Context

We would like to try server-side apply but this is blocking us.

## Your Environment

* Calico version: v3.20.0
* Kubernetes version:
  ```
  $ kubectl version
  Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-16T02:41:51Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:04:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
  ```

**Comment by song-jiang** [comment]
First issue: server-side apply returns `no serializer defined for application/yaml`

This is because calico-apiserver only supports application/json codec right now.
https://github.com/projectcalico/apiserver/blob/master/pkg/apiserver/protocalshield.go#L25

We should update the code to support application/yaml codec.

**Comment by song-jiang** [comment]
However, after code changes to support application/yaml, I've been hitting another issue that calico-apiserver received `PATCH` command for object which did not exists. kubectl returned error `key not found`. 

```
song@song-dev5:~/semaphore/server-side-apply$ kubectl apply -f status.yaml --server-side -v 6
I1127 21:22:47.801656 2226113 loader.go:372] Config loaded from file:  /home/song/.kube/config
I1127 21:22:47.852200 2226113 round_trippers.go:454] GET https://127.0.0.1:44753/openapi/v2?timeout=32s 200 OK in 48 milliseconds
I1127 21:22:48.151348 2226113 round_trippers.go:454] PATCH https://127.0.0.1:44753/apis/projectcalico.org/v3/caliconodestatuses/elm?fieldManager=kubectl&force=false 500 Internal Server Error in 63 milliseconds
I1127 21:22:48.151786 2226113 helpers.go:216] server response object: [{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "StorageError: key not found, Code: 1, Key: projectcalico.org/caliconodestatuses/elm, ResourceVersion: 0, AdditionalErrorMsg: ",
  "code": 500
}]
F1127 21:22:48.151880 2226113 helpers.go:115] Error from server: StorageError: key not found, Code: 1, Key: projectcalico.org/caliconodestatuses/elm, ResourceVersion: 0, AdditionalErrorMsg: 
```

**Comment by song-jiang** [comment]
My understanding is calico-apiserver should get `PUT` instead of `PATCH` from kube-apiserver if `GET` returns `key not found`. Not sure why it is not the case now, I'm still working on it. Any help from the community is greatly appreciated. 

calico-apiserver log
```
I1126 16:49:37.210582       1 handler.go:143] apiserver: PATCH "/apis/projectcalico.org/v3/caliconodestatuses/elm" satisfied by gorestful with webservice /apis/projectcalico.org/v3
I1126 16:49:37.216550       1 resource.go:235] Get called with key: projectcalico.org/caliconodestatuses/elm on resource CalicoNodeStatus
time="2021-11-26T16:49:37Z" level=error msg="Error updating resource" Key="CalicoNodeStatus(elm)" Name=elm Resource=CalicoNodeStatuses Value="&{{CalicoNodeStatus projectcalico.org/v3} {elm    28f5fbd7-98e9-4f00-a142-434deba67816 0 0 2021-11-26 16:49:37.224238621 +0000 UTC m=+23.262499348 <nil> <nil> map[] map[] [] []  [{kubectl Apply projectcalico.org/v3 2021-11-26 16:49:37.224110372 +0000 UTC FieldsV1 {\"f:spec\":{\"f:classes\":{},\"f:node\":{},\"f:updatePeriodSeconds\":{}}}}]} {kind-worker [Agent BGP Routes] 0xc001058b98} {0001-01-01 00:00:00 +0000 UTC {{    } {    }} {0 0 0 0 [] []} {[] []}}}" error="Operation cannot be fulfilled on caliconodestatuses.crd.projectcalico.org \"elm\": StorageError: invalid object, Code: 4, Key: /registry/crd.projectcalico.org/caliconodestatuses/elm, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 28f5fbd7-98e9-4f00-a142-434deba67816, UID in object meta: "
E1126 16:49:37.232323       1 status.go:71] apiserver received an error that is not an metav1.Status: &storage.StorageError{Code:1, Key:"projectcalico.org/caliconodestatuses/elm", ResourceVersion:0, AdditionalErrorMsg:""}: StorageError: key not found, Code: 1, Key: projectcalico.org/caliconodestatuses/elm, ResourceVersion: 0, AdditionalErrorMsg:
```

**Comment by song-jiang** [comment]
It seems both `kube-apiserver` and `apiextensions-apiserver` support object creation on PATCH, on the condition that either store's UpdateStrategy.AllowCreateOnUpdate() is true or request is server side apply (forceAllowCreate is true if request content type is `types.ApplyPatchType`). 

https://github.com/kubernetes/kubernetes/blob/v1.22.1/staging/src/k8s.io/apiserver/pkg/registry/generic/registry/store.go#L519

**Comment by song-jiang** [comment]
My guess is calico-apiserver uses `genericregistry.Store` as rest.Storage to serve restful requests. `genericregistry.Store` can handle server-side apply by checking request content type via `Patcher` and ignore errors for `object no found`.

However, when `Patcher` is calling ``genericregistry.Store`'s Update function, which in turn calling `GuaranteedUpdate` of calico-apiserver's resourceStore, it doesn't have code to handle `object not found`, because it just calling libcalico-go's update function.

**Comment by ahmet2mir** [comment]
Hello,

I got the same issue with Calico 3.21.4 when I try to use it with terraform (which use server side apply)

```
resource "kubernetes_manifest" "ipam" {
  manifest = {
    apiVersion = "projectcalico.org/v3"
    kind       = "IPPool"
    metadata = {
      name = "${var.namespace}-pool"
    }
    spec = {
      cidr = "10.1.2.0/24"
    }
  }
}
```

The plan is fine but once applying

```
│ Error: API response status: Failure
│ no serializer defined for application/yaml
```

To bypass this issue, I have to use a configmap and had an internal tool which convert to ippol (which is very ugly).

Not sure if https://github.com/projectcalico/apiserver/pull/100 fixes this issue or if deployed on 3.21.4.

**Comment by caseydavenport** [comment]
> EDIT2: using apiVersion = "crd.projectcalico.org/v1" works \o/, example

For the record, you should NOT do this. It bypasses validation and defaulting and is not supported.

Looks like the server side apply fix should be in v3.21.0, though: https://github.com/projectcalico/apiserver/pull/100

So maybe something else going on here.

**Comment by rwunderer** [comment]
@caseydavenport It seems the files from `v3.21.4` do not contain the changes made in https://github.com/projectcalico/apiserver/pull/100

https://github.com/projectcalico/calico/blob/v3.21.4/apiserver/pkg/apiserver/protocalshield.go
https://github.com/projectcalico/calico/blame/v3.21.4/apiserver/pkg/storage/calico/resource.go

`master` is up to date though.
https://github.com/projectcalico/calico/blob/d930ed33559d2c2f5d2588bfb79ee9ac672d101c/apiserver/pkg/apiserver/protocalshield.go#L25

Maybe a result from switching repositories?

**Comment by caseydavenport** [comment]
Hm, yeah perhaps this got lost in the repo switch although I'm not sure how that could have happened. 

It does look like the changes are present in v3.22 though - have you tried on v3.22 at all?

**Comment by rwunderer** [comment]
Yes, 3.22 looks good from the source code. I will try and test it later this week.
