### ISSUE TITLE
calico-node pods crash when VXLAN backend is used on IPv6 clusters with IPv6 Calico pools

### ISSUE THREAD

**Issue by rsparulek** [projectcalico/calico#5200]
calico-node pods crash when VXLAN backend is used on IPv6 clusters with IPv6 Calico pools

## Expected Behavior
There should be a friendly warning for such issue. Calico pods should not enter into crash state.

## Current Behavior
calico-node pods crash when VXLAN backend is used on IPv6 clusters with IPv6 Calico pools

## Steps to Reproduce (for bugs)
Install K8S 1.21 multi node cluster and use Calico as the default CNI for the cluster. This issue was seen on IPv6 clusters where IPv6 calico IP pools were configured. Calico version used is v3.12.3.

This is the panic trace that is seen in docker logs for calico-node pods in the cluster
```
2021-05-13 23:31:41.284 [INFO][3709] config_params.go 372: Skipping config value for LogSeverityScreen from datastore (global); already have a value from environment variable
2021-05-13 23:31:41.284 [INFO][3709] async_calc_graph.go 209: First flush after becoming in sync, sending InSync message.
2021-05-13 23:31:41.284 [INFO][3709] daemon.go 947: Datastore now in sync.
2021-05-13 23:31:41.284 [INFO][3709] daemon.go 949: Datastore in sync for first time, sending message to status reporter.
2021-05-13 23:31:41.284 [INFO][3709] int_dataplane.go 825: Received *proto.ActiveProfileUpdate update from calculation graph msg=id:<name:"kns.kube-system" > profile:<inbound_rules:<action:"allow" rule_id:"YlN-KJA93B7Fe2ih" > outbound_rules:<action:"allow" rule_id:"GUM3x2IgYhIM5cBY" > > 
2021-05-13 23:31:41.285 [INFO][3709] table.go 443: Queueing update of chain. chainName="cali-pri-kns.kube-system" ipVersion=0x4 table="filter"
2021-05-13 23:31:41.285 [INFO][3709] table.go 443: Queueing update of chain. chainName="cali-pro-kns.kube-system" ipVersion=0x4 table="filter"
2021-05-13 23:31:41.285 [INFO][3709] table.go 443: Queueing update of chain. chainName="cali-pri-kns.kube-system" ipVersion=0x6 table="filter"
2021-05-13 23:31:41.285 [INFO][3709] table.go 443: Queueing update of chain. chainName="cali-pro-kns.kube-system" ipVersion=0x6 table="filter"
2021-05-13 23:31:41.285 [INFO][3709] int_dataplane.go 825: Received *proto.ActiveProfileUpdate update from calculation graph msg=id:<name:"ksa.kube-system.coredns" > profile:<> 
2021-05-13 23:31:41.285 [INFO][3709] table.go 443: Queueing update of chain. chainName="cali-pri-_u2Tn2rSoAPffvE7JO6" ipVersion=0x4 table="filter"
2021-05-13 23:31:41.285 [INFO][3709] table.go 443: Queueing update of chain. chainName="cali-pro-_u2Tn2rSoAPffvE7JO6" ipVersion=0x4 table="filter"
2021-05-13 23:31:41.285 [INFO][3709] table.go 443: Queueing update of chain. chainName="cali-pri-_u2Tn2rSoAPffvE7JO6" ipVersion=0x6 table="filter"
2021-05-13 23:31:41.285 [INFO][3709] table.go 443: Queueing update of chain. chainName="cali-pro-_u2Tn2rSoAPffvE7JO6" ipVersion=0x6 table="filter"
2021-05-13 23:31:41.285 [INFO][3709] int_dataplane.go 825: Received *proto.WorkloadEndpointUpdate update from calculation graph msg=id:<orchestrator_id:"k8s" workload_id:"kube-system/coredns-7f75648fb8-ml8h8" endpoint_id:"eth0" > endpoint:<state:"active" name:"cali1405e1e3e80" profile_ids:"kns.kube-system" profile_ids:"ksa.kube-system.coredns" ipv6_nets:"fd74:ca9b:3a09:868c:172:40:0:3e00/128" > 
2021-05-13 23:31:41.287 [INFO][3709] int_dataplane.go 825: Received *proto.InSync update from calculation graph msg=
2021-05-13 23:31:41.287 [INFO][3709] int_dataplane.go 833: Datastore in sync, flushing the dataplane for the first time... timeSinceStart=127.0562ms
2021-05-13 23:31:41.287 [INFO][3709] int_dataplane.go 953: Applying dataplane updates
2021-05-13 23:31:41.287 [INFO][3709] ipsets.go 119: Queueing IP set for creation family="inet" setID="all-vxlan-net" setType="hash:net"
2021-05-13 23:31:41.288 [PANIC][3709] ip_addr.go 222: Failed to parse CIDR cidr="<nil>" error=Failed to parse IP address
panic: (*logrus.Entry) (0x1c13800,0xc0006e8d70)

goroutine 154 [running]:
github.com/sirupsen/logrus.Entry.log(0xc00011c050, 0xc000a1e120, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/projectcalico/logrus@v1.0.4-calico/entry.go:128 +0x651
github.com/sirupsen/logrus.(*Entry).Panic(0xc0006e8d20, 0xc0005289e8, 0x1, 0x1)
	/go/pkg/mod/github.com/projectcalico/logrus@v1.0.4-calico/entry.go:173 +0x103
github.com/projectcalico/felix/ip.MustParseCIDROrIP(0x1c582ae, 0x5, 0x0, 0xffffffffffffffff)
	/go/pkg/mod/github.com/projectcalico/felix@v0.0.0-20200522191727-849881594f80/ip/ip_addr.go:222 +0x1e6
github.com/projectcalico/felix/ipsets.IPSetType.CanonicaliseMember(0x1c5d0ec, 0x8, 0x1c582ae, 0x5, 0xc00053bd00, 0x0)
	/go/pkg/mod/github.com/projectcalico/felix@v0.0.0-20200522191727-849881594f80/ipsets/ipset_defs.go:174 +0x90b
github.com/projectcalico/felix/ipsets.(*IPSets).filterAndCanonicaliseMembers(0xc0001217a0, 0x1c5d0ec, 0x8, 0xc000a9a240, 0x1, 0x1, 0xc000100e60, 0x38)
	/go/pkg/mod/github.com/projectcalico/felix@v0.0.0-20200522191727-849881594f80/ipsets/ipsets.go:260 +0x137
github.com/projectcalico/felix/ipsets.(*IPSets).AddOrReplaceIPSet(0xc0001217a0, 0x1c6404c, 0xd, 0x1c5d0ec, 0x8, 0x100000, 0xc000a9a240, 0x1, 0x1)
	/go/pkg/mod/github.com/projectcalico/felix@v0.0.0-20200522191727-849881594f80/ipsets/ipsets.go:120 +0x262
github.com/projectcalico/felix/dataplane/linux.(*vxlanManager).CompleteDeferredWork(0xc000700000, 0x0, 0xffffffffffffffff)
	/go/pkg/mod/github.com/projectcalico/felix@v0.0.0-20200522191727-849881594f80/dataplane/linux/vxlan_mgr.go:252 +0x1740
github.com/projectcalico/felix/dataplane/linux.(*InternalDataplane).apply(0xc00040a000)
	/go/pkg/mod/github.com/projectcalico/felix@v0.0.0-20200522191727-849881594f80/dataplane/linux/int_dataplane.go:1018 +0x9a
github.com/projectcalico/felix/dataplane/linux.(*InternalDataplane).loopUpdatingDataplane(0xc00040a000)
	/go/pkg/mod/github.com/projectcalico/felix@v0.0.0-20200522191727-849881594f80/dataplane/linux/int_dataplane.go:957 +0x59b
created by github.com/projectcalico/felix/dataplane/linux.(*InternalDataplane).Start
	/go/pkg/mod/github.com/projectcalico/felix@v0.0.0-20200522191727-849881594f80/dataplane/linux/int_dataplane.go:584 +0x51
```

## Your Environment
- Calico v3.12.3 
- IPv6 hosts in the cluster
- Centos 7 OS
- Kernel : 3.10.0-1127.18.2.el7.x86_64

* libcalico-go version:
```
calico/node                                        v3.12.3             749f012a9139        7 months ago        259MB
calico/cni                                         v3.12.3             a6b30a97efd9        10 months ago       298MB
calico/kube-controllers                            v3.12.3             77efab4f775c        10 months ago       56.6MB
calico/typha                                       v3.12.3             12d8d37ff735        10 months ago       56MB
calico/pod2daemon-flexvol                          v3.12.3             bfa72d71ec58        10 months ago       22.8MB
```
* Operating System and version: Centos 7 OS
* Link to your project: kubernetes 1.21

**Comment by caseydavenport** [comment]
Closing this for now as it's quite old.
