### ISSUE TITLE
netlink socket overflow: "No buffer space available" (1000 endpoints on single host)

### ISSUE THREAD

**Issue by alexwlchan** [projectcalico/calico#595]
Spotted during scalability testing. Felix falls over three times within the course of a second, and then seems to recover (no more logs are dropped after this). Felix seems to continue running (or at least upstart brings it back).

I was attempting to spin up 1000 endpoints on the same host as part of the scalability testing. Memory consumption then goes to ~300MiB and sits there. No obvious other errors in the logs or in the test output.

    2015-05-28 10:02:11,225 [ERROR][15031/1] calico.felix.actor 227: Exception processing 8c91a0d16cb9 (watch_interfaces)
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/calico/felix/actor.py", line 225, in _step
        result = msg.method()
      File "/usr/lib/python2.7/dist-packages/calico/felix/devices.py", line 257, in watch_interfaces
        data = s.recv(65535)
      File "/usr/lib/python2.7/dist-packages/gevent/socket.py", line 385, in recv
        return sock.recv(*args)
    error: [Errno 105] No buffer space available

    2015-05-28 10:02:11,227 [ERROR][15031/2] calico.felix.felix 152: Greenlet failed: <TrackedAsyncResult value=None exception=error(105, 'No buffer space available')  _links[0]>
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/calico/felix/felix.py", line 150, in _main_greenlet
        stopped_greenlet.get()
      File "/usr/lib/python2.7/dist-packages/calico/felix/actor.py", line 552, in get
        timeout=timeout)
      File "/usr/lib/python2.7/dist-packages/gevent/event.py", line 219, in get
        raise self._exception
    error: [Errno 105] No buffer space available

    2015-05-28 10:02:11,228 [ERROR][15031/2] calico.felix.felix 158: Exception killing main greenlet
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/calico/felix/felix.py", line 150, in _main_greenlet
        stopped_greenlet.get()
      File "/usr/lib/python2.7/dist-packages/calico/felix/actor.py", line 552, in get
        timeout=timeout)
      File "/usr/lib/python2.7/dist-packages/gevent/event.py", line 219, in get
        raise self._exception
    error: [Errno 105] No buffer space available
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
        result = self._run(*self.args, **self.kwargs)
      File "/usr/lib/python2.7/dist-packages/calico/felix/felix.py", line 150, in _main_greenlet
        stopped_greenlet.get()
      File "/usr/lib/python2.7/dist-packages/calico/felix/actor.py", line 552, in get
        timeout=timeout)
      File "/usr/lib/python2.7/dist-packages/gevent/event.py", line 219, in get
        raise self._exception
    error: [Errno 105] No buffer space available
    <Greenlet at 0x7f179b0fb910: _main_greenlet(<calico.felix.config.Config object at 0x7f179ae3ca)> failed with error

Diags on calico23 in `/usr/bin/2015-05-28_15-26-57.tar.xz` (but the file is a bit big to upload, 200MB).

It's probably worth repeating this test to see a) if this problem repeats itself, and b) monitoring the performance of Felix more closely. But I'd like some pointers for what to monitor before I do this again.

**Comment by matthewdupre** [comment]
If I had to guess, I'd say that the following part of that traceback:

`File "/usr/lib/python2.7/dist-packages/calico/felix/devices.py", line 257, in watch_interfaces
    data = s.recv(65535)
  File "/usr/lib/python2.7/dist-packages/gevent/socket.py", line 385, in recv
    return sock.recv(*args)
error: [Errno 105] No buffer space available`

and the fact that you had 1000 interfaces on your box might suggest that the interface list no longer fits in 65535 bytes, so it might be interesting to try changing that number and seeing if it moves the failure point correspondingly (I suggest downwards, for quicker repro).

If the above hypothesis is true, we could increase the buffer size, or catch the exception and increase the limit dynamically.

**Comment by plwhite** [comment]
@matthewdupre is surely right. Worth seeing what we find there.

**Comment by alexwlchan** [comment]
Decreasing that limit definitely gives Felix a headache, but it's a different exception.

I tried to create 100 endpoints on the same host, with `s.recv(256)`. Felix was definitely unhappy:

* I saw the weird memory behaviour again (RES jumped by about 7000 kiB and VIRT doubled; neither changed after that).
* I saw this exception in the logs:

        2015-06-01 13:35:56,153 [ERROR][28248/1] calico.felix.actor 227: Exception processing 96835c20c833 (watch_interfaces)
        Traceback (most recent call last):
          File "/usr/lib/python2.7/dist-packages/calico/felix/actor.py", line 225, in _step
            result = msg.method()
          File "/usr/lib/python2.7/dist-packages/calico/felix/devices.py", line 286, in watch_interfaces
            rta_len, rta_type = struct.unpack("=HH", data[:4])
        error: unpack requires a string argument of length 4

        2015-06-01 13:35:56,155 [ERROR][28248/2] calico.felix.felix 152: Greenlet failed: <TrackedAsyncResult value=None exception=error('unpack requires a string ar
        gument of length 4',)  _links[0]>
        Traceback (most recent call last):
          File "/usr/lib/python2.7/dist-packages/calico/felix/felix.py", line 150, in _main_greenlet
            stopped_greenlet.get()
          File "/usr/lib/python2.7/dist-packages/calico/felix/actor.py", line 552, in get
            timeout=timeout)
          File "/usr/lib/python2.7/dist-packages/gevent/event.py", line 219, in get
            raise self._exception
        error: unpack requires a string argument of length 4

        2015-06-01 13:35:56,156 [ERROR][28248/2] calico.felix.felix 158: Exception killing main greenlet
        Traceback (most recent call last):
          File "/usr/lib/python2.7/dist-packages/calico/felix/felix.py", line 150, in _main_greenlet
            stopped_greenlet.get()
          File "/usr/lib/python2.7/dist-packages/calico/felix/actor.py", line 552, in get
            timeout=timeout)
          File "/usr/lib/python2.7/dist-packages/gevent/event.py", line 219, in get
            raise self._exception
        error: unpack requires a string argument of length 4
        Traceback (most recent call last):
          File "/usr/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
            result = self._run(*self.args, **self.kwargs)
          File "/usr/lib/python2.7/dist-packages/calico/felix/felix.py", line 150, in _main_greenlet
            stopped_greenlet.get()
          File "/usr/lib/python2.7/dist-packages/calico/felix/actor.py", line 552, in get
            timeout=timeout)
          File "/usr/lib/python2.7/dist-packages/gevent/event.py", line 219, in get
            raise self._exception
        error: unpack requires a string argument of length 4
        <Greenlet at 0x7f339b103910: _main_greenlet(<calico.felix.config.Config object at 0x7f339ae44a)> failed with error

    This comes from the same part of the Felix codebase, just a little bit further down. The structure of the errors is broadly similar, but we don't see the "No buffer space" available message.

Doing a [bit of searching](https://duckduckgo.com/?q=No+buffer+space+available+maximum+connections+reached&ref=opensearch), I don't think this is (just) a problem with our code. The phrase "No buffer space" seems to appear a lot with "maximum connections reached", which makes me think we may be hitting some limit on the number of interfaces that a Linux box can maintain. (I'm guessing there; I have no idea.)

Follow-on thoughts:

* Even if the problem is arising in Linux, Felix shouldn't misbehave when handed this problem arises. (I am assuming the memory weirdness is misbehaving, anyway.)
* I'm going to try spinning up a lot of interfaces to see what happens. Find out if my test kit does have some limit.

**Comment by alexwlchan** [comment]
We can definitely create >1000 interfaces on the same host, no problem. (Unsurprisingly, really.) So the problem lies elsewhere.

**Comment by matthewdupre** [comment]
That unpack problem isn't all that different to not having enough buffer space - it could suggest that the message has been truncated due to insufficient space.  Having two different exceptions is definitely a bit odd, but I'd still expect increasing the limit to fix it (if we decide it's worth it), so I don't think this changes anything.

**Comment by alexwlchan** [comment]
@matthewdupre I will be running another test with 1000 endpoints (probably) tomorrow, so I'm going to try increasing the limit and see what happens.

**Comment by fasaxc** [comment]
e're not using pyroute2 but it looks like this is what we're hitting:

http://docs.pyroute2.org/nlsocket.html#enobuf-and-async-i-o

"When Netlink messages arrive faster than a program reads then from the socket, the messages overflow the socket buffer and one gets ENOBUF on recv():"

**Comment by fasaxc** [comment]
I.e. it's not the recv buffer, it's the socket's buffer.  Increasing the size of either buffer won't help if we can't keep up in the long run.  It's likely that the reading greenlet is being starved and can't keep up, which is going to be awkward to fix because gevent doesn't have thread priorities.

OTOH, it's the rate of change that's likely to be important here.  @alexwlchan how many endpoints were you adding per second?

**Comment by alexwlchan** [comment]
@fasaxc No faster than one endpoint per second, iirc. There’s an `eventlet.sleep(1)` between each endpoint being added in the test script.

**Comment by fasaxc** [comment]
@alexwlchan I think the posix_spawn work should improve this a lot.  Worth a retest?

**Comment by alexwlchan** [comment]
@fasaxc Seems sensible. I probably don't have time to get to it before Friday, but I'll try to get to it next week.

**Comment by fasaxc** [comment]
@alexwlchan Are you going to retest this, can we close it?

**Comment by fasaxc** [comment]
I was able to hit this reliably (even) on the concurrent resync branch by creating as many interfaces as possible (in etcd and creating a matching linux device) in a tight loop.  Felix recovered after restart as long as the load was removed.  I think it's simply felix not being able to read the messages fast enough from the netlink socket because the device watching thread gets starved by all the endpoint setup threads.  We also have no way to resync that data right now so all we can do is die.

The right fix is to implement resync of the interface list via the netlink API (and possibly to improve the starvation issue too).  That would also remove the need for the various shell-outs that we make to check interface state.

**Comment by svinota** [comment]
Excuse me for interrupting, but maybe this would help a bit. As it was done in pyroute2.IPDB: 

1. start a separate async thread that only reads packets and enqueues them for processing, and does nothing else
2. on every incoming packet check the queue size, and if it is higher than a threshold, suspend the main thread by calling the `sleep()` — the `recv()` doesn't return before a timeout — the main process starts to respond with high delays, but the reader thread [1] get the highest priority by the Python scheduler to receive packets and store them in the user space memory (no parsing still) [2]
3. if it doesn't help and the reader thread receives an exception, restart DB [3]
4. when restarting while the netlink traffic is higher, than we can handle, the interface/route/address `dump` requests will not return full listings — but it doesn't matter much,  since netlink notifications continue to arrive and the state will be synced in time, or the DB will be restarted again.

This allows to handle really bad netlink bursts, like hundreds of thousands new addresses/routes etc. Though, while in the burst, the DB is not able to apply changes in a short time. 

[1] https://github.com/svinota/pyroute2/blob/master/pyroute2/netlink/nlsocket.py#L472
[2] https://github.com/svinota/pyroute2/blob/master/pyroute2/netlink/nlsocket.py#L676
[3] https://github.com/svinota/pyroute2/blob/master/pyroute2/ipdb/__init__.py#L1130

**Comment by fasaxc** [comment]
Not at all, thanks for stopping by, @svinota.  I think we'd be thwarted by our use of gevent; since we don't have a real OS-level thread we can be starved for too long.  We're already working on pushing the etcd watching function into a second process (to bypass gevent and the GIL), maybe we should do the same for netlink...

**Comment by svinota** [comment]
Yep, probably. Any delay while receiving the packets can kick off the netlink socket, and in the worst case the Python performance is not enough to handle the parsing while receiving (due to GIL), it's enough only to do the underlying `recv()` + store the packet in the user space buffer. If it's incompatible with your architecture, a standalone process-receiver or a C module with a system (not Python) thread would help indeed. A standalone process is better also 'cause in the case of insufficient memory it's better to drop a simple standalone process than to completely restart the main one.

Just keep in mind, any `dump` you do after the restart can happen while the netlink burst is still going. For such cases one should not rely only on dumps, for they will be inconsistent, but collect also relevant netlink notifications — they will work as a «diff» between the dump and the actual state.

**Comment by fasaxc** [comment]
@svinota thanks for the tips.

**Comment by fasaxc** [comment]
Reducing the priority. With current felix, we can handle a pretty high churn rate before we get behind.

**Comment by fasaxc** [comment]
Closing this until we have a requirement to deal with extremely high per-host churn.
