### ISSUE TITLE
Calico Node container issues when FIPS mode is enabled

### ISSUE THREAD

**Issue by gabrielericciardi** [projectcalico/calico#6180]
In our system there is an InitContainer requiring a kubectl exec on the Calico node container. This worked until we decided to upgrade runc from runc-1.0.0-70.rc92.module+el8.4.0+10607+f4da7515.x86_64 to runc-1.1.0-1.rhaos4.10.el8.x86_64: after that, the kubectl exec fails reporting FIPS violations in the system log.
Contacted the Red Hat support, and their analysis points to the Calico Node container as the issue: they provided a code snippet to execute a FIPS self-test from inside the container, and they proved that, on a node with FIPS mode enabled, the self-test passes from within a RedHat 8.6 UBI container but it fails from within the Calico Node container.

## Expected Behavior

The kubectl exec command executed in the Calico Node container succeeds on nodes with FIPS enabled.
The provided FIPS self-test passes within the Calico Node container.

## Current Behavior

The kubectl exec command executed in the Calico Node container fails on nodes with FIPS enabled.
The provided FIPS self-test fails within the Calico Node container.

## Possible Solution

The analysis seems to point to the lack of the libssl library and both the .hmac files for libssl and libcrypto library, which are required by FIPS. RedHat proved that by injecting into the Calico Node container the missing parts the FIPS self-test passes (see Context). 
The UBI container which succeeds in the test has indeed indicated libraries and .hmac files.
Here's the code snippet provided by Red Hat:
```c
//check-fips.c
#include <stdio.h>
#include <openssl/ssl.h>
#include <openssl/fips.h>
#include <openssl/err.h>
int main(int argc, char *argv[])
{
   fprintf(stderr,"Startup\n");
   fprintf(stderr,"all algos added\n");
   if(FIPS_mode())
      fprintf(stderr,"FIPS mode already set.\n");
   else {
      fprintf(stderr,"Not to set FIPS mode...\n");
   }
   fprintf(stderr,"Attempt FIPS self tests...\n");
   if (FIPS_selftest()) {
      fprintf(stderr,"FIPS self tests succeeded.\n");
   }
   else {
      fprintf(stderr,"ERROR: FIPS self tests failed.\n");
      ERR_print_errors_fp(stderr);
   }
   return 0;
}
```

## Steps to Reproduce (for bugs)

1. Compile the provided code snippet on a Red Hat 8.6 machine with ```gcc -o check-fips check-fips.c -lssl -lcrypto ```
2. Execute the steps described in the Context section

## Context

Update runc

Here are the tests performed by the Red Hat support:

```
Please find the test results and our observation. We updated the runc to a version which is considered as problematic.

Verifying FIPS on the host system
--------------------------

[root@atomic-test ~]# rpm -q runc
runc-1.1.0-1.rhaos4.10.el8.x86_64
[root@atomic-test ~]# fips-mode-setup --check
FIPS mode is enabled.

Used a UBI8 container image 
-----------------------------

Starting the container, copying the test binary and checking for fips. We can see FIPS self test passed

[root@atomic-test ~]# podman run -d -t --name fipscheck registry.access.redhat.com/ubi8/ubi
4bb0a1c0a9e136c018dd14d76dd65f6864bf3900e1f0be5080cfbc7eb744eae3
[root@atomic-test ~]# podman cp check-fips fipscheck:/tmp/
[root@atomic-test ~]# podman exec -it fipscheck /tmp/check-fips
Startup
all algos added
FIPS mode already set.
Attempt FIPS self tests...
FIPS self tests succeeded.

If runc or the host was causing an issue, FIPS self test won't pass. Hope you agree at this point

3. Using Calico container image

Same node, same runc package but with calico image we fail

[root@atomic-test ~]# rpm -q runc
runc-1.1.0-1.rhaos4.10.el8.x86_64
[root@atomic-test ~]# fips-mode-setup --check
FIPS mode is enabled.

We used the latest calico image

[root@atomic-test ~]# podman run -it --name calico-test --entrypoint=/bin/bash docker.io/calico/node:v3.23.1
[root@ab4d0248d967 /]# 

From another terminal, we copied the "check-fips" binary

[root@atomic-test ~]# podman cp check-fips calico-test:/tmp/

FIPS self test failed. 

[root@ab4d0248d967 /]# /tmp/check-fips 
crypto/fips/fips.c:154: OpenSSL internal error: FATAL FIPS SELFTEST FAILURE
Aborted (core dumped)


Note:

On the same host with the same runc, FIPS self test passes with UBI8 container image and fails with Calico. It was clear the problem was not due to runc package.

Purely from a Commercially Reasonable Support, we tried to investigate what was wrong. We were able to get the FIPS Self test to pass, when we performed the following steps

1. Copied the libraries and required files to the image

[root@atomic-test ~]# podman cp /lib64/.libssl.so.1.1.hmac calico-test:/usr/lib64/
[root@atomic-test ~]# podman cp /lib64/.libcrypto.so.1.1.hmac calico-test:/usr/lib64/
[root@atomic-test ~]# podman cp /lib64/libssl.so.1.1.1k calico-test:/usr/lib64/

Within the container, we made a symlink

[root@2dda1ca0c5ec /]# ln -s /usr/lib64/libssl.so.1.1.1k /usr/lib64/libssl.so.1.1

After making all these changes, FIPS Self test passed on the calico image

From the container

[root@ab4d0248d967 tmp]# /tmp/check-fips 
Startup
all algos added
FIPS mode already set.
Attempt FIPS self tests...
FIPS self tests succeeded.


According to the above test, with the same runc and after making few changes to the container, FIPS self test passed.


We downgraded the runc to the version that you mentioned as working. We noticed the same isue

With older runc and Calico image

[root@atomic-test ~]# rpm -q runc
runc-1.0.1-3.rhaos4.9.git4144b63.el8.x86_64

[root@atomic-test ~]# podman run -it --name calico-test --entrypoint=/bin/bash docker.io/calico/node:v3.23.1 
[root@899083dfae7b /]# /tmp/check-fips 
crypto/fips/fips.c:154: OpenSSL internal error: FATAL FIPS SELFTEST FAILURE
Aborted (core dumped)

The above information once again points the issue towards calico image. We are not sure why calico worked with the previous version of runc as mentioned in your update. The above test points to the container image.

```

## Your Environment

* Calico version --> v3.20.5, but also the latest v3.23.1 seems to be affected
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes, version 1.23.6
* Operating System and version: Red Hat Linux Enterprise 8.4 with runc-1.1.0-1.rhaos4.10.el8.x86_64 and FIPS mode enabled
* Link to your project (optional):

**Comment by caseydavenport** [comment]
Calico leverages BoringSSL as its TLS implementation, which I suspect is part of the incompatibility here since from what I can tell all of the above steps are assuming that OpenSSL in FIPS mode is being used. We're not including those libraries because they aren't called from within the Calico code itself and so would be dead code within the calico/node container.

That said, I'm not entirely sure why a `runc` upgrade would impact this, so perhaps there is something else going on here.

> In our system there is an InitContainer requiring a kubectl exec on the Calico node container

Mind if I ask what this init container does?

**Comment by basvandenbrink** [comment]
Hi @caseydavenport, thanks for answered! I am a colleague of @gabrielericciardi.

Actually, it seems to be the readiness probe that's failing. This triggered us to dive into the Calico Node logs, which included a very long FIPS error:

```
May 10 14:52:00 node-1 kubelet[62528]: E0510 14:52:00.506020 62528 remote_runtime.go:704] "ExecSync cmd from runtime service failed" err="rpc error: code = Unknown desc = command error: crypto/fips/fips.c:154: OpenSSL internal error: FATAL FIPS SELFTEST FAILURE\nSIGABRT: abort\nPC=0x7f44c675737f m=0 sigcode=18446744073709551610\nsignal arrived during cgo execution\n\ngoroutine 1 [syscall, locked to thread]:\nruntime.cgocall(0x55a8385a3310, 0xc0001c5588)\n\t/usr/lib/golang/src/runtime/cgocall.go:156 +0x5c fp=0xc0001c5560 sp=0xc0001c5528 pc=0x55a8381d943c\ncrypto/internal/boring._Cfunc__goboringcrypto_DLOPEN_OPENSSL()\n\t_cgo_gotypes.go:284 +0x4d fp=0xc0001c5588 sp=0xc0001c5560 pc=0x55a8384033cd\ncrypto/internal/boring.init.0()\n\t/usr/lib/golang/src/crypto/internal/boring/boring.go:46 +0x45 fp=0xc0001c55c0 sp=0xc0001c5588 pc=0x55a838404205\nruntime.doInit(0x55a838c26600)\n\t/usr/lib/golang/src/runtime/proc.go:6498 +0x125 fp=0xc0001c56f8 sp=0xc0001c55c0 pc=0x55a838219125\nruntime.doInit(0x55a838c23960)\n\t/usr/lib/golang/src/runtime/proc.go:6475 +0x71 fp=0xc0001c5830 sp=0xc0001c56f8 pc=0x55a838219071\nruntime.doInit(0x55a838c27720)\n\t/usr/lib/golang/src/runtime/proc.go:6475 +0x71 fp=0xc0001c5968 sp=0xc0001c5830 pc=0x55a838219071\nruntime.doInit(0x55a838c285a0)\n\t/usr/lib/golang/src/runtime/proc.go:6475 +0x71 fp=0xc0001c5aa0 sp=0xc0001c5968 pc=0x55a838219071\nruntime.doInit(0x55a838c260c0)\n\t/usr/lib/golang/src/runtime/proc.go:6475 +0x71 fp=0xc0001c5bd8 sp=0xc0001c5aa0 pc=0x55a838219071\nruntime.doInit(0x55a838c266a0)\n\t/usr/lib/golang/src/runtime/proc.go:6475 +0x71 fp=0xc0001c5d10 sp=0xc0001c5bd8 pc=0x55a838219071\nruntime.doInit(0x55a838c2a460)\n\t/usr/lib/golang/src/runtime/proc.go:6475 +0x71 fp=0xc0001c5e48 sp=0xc0001c5d10 pc=0x55a838219071\nruntime.doInit(0x55a838c29c60)\n\t/usr/lib/golang/src/runtime/proc.go:6475 +0x71 fp=0xc0001c5f80 sp=0xc0001c5e48 pc=0x55a838219071\nruntime.main()\n\t/usr/lib/golang/src/runtime/proc.go:238 +0x1e6 fp=0xc0001c5fe0 sp=0xc0001c5f80 pc=0x55a83820bf06\nruntime.goexit()\n\t/usr/lib/golang/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0001c5fe8 sp=0xc0001c5fe0 pc=0x55a83823a021\n\ngoroutine 2 [force gc (idle)]:\nruntime.gopark(0x0, 0x0, 0x0, 0x0, 0x0)\n\t/usr/lib/golang/src/runtime/proc.go:366 +0xd6 fp=0xc000050fb0 sp=0xc000050f90 pc=0x55a83820c316\nruntime.goparkunlock(...)\n\t/usr/lib/golang/src/runtime/proc.go:372\nruntime.forcegchelper()\n\t/usr/lib/golang/src/runtime/proc.go:306 +0xad fp=0xc000050fe0 sp=0xc000050fb0 pc=0x55a83820c1ad\nruntime.goexit()\n\t/usr/lib/golang/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc000050fe8 sp=0xc000050fe0 pc=0x55a83823a021\ncreated by runtime.init.8\n\t/usr/lib/golang/src/runtime/proc.go:294 +0x25\n\ngoroutine 18 [GC sweep wait]:\nruntime.gopark(0x0, 0x0, 0x0, 0x0, 0x0)\n\t/usr/lib/golang/src/runtime/proc.go:366 +0xd6 fp=0xc00004c7b0 sp=0xc00004c790 pc=0x55a83820c316\nruntime.goparkunlock(...)\n\t/usr/lib/golang/src/runtime/proc.go:372\nruntime.bgsweep()\n\t/usr/lib/golang/src/runtime/mgcsweep.go:163 +0x88 fp=0xc00004c7e0 sp=0xc00004c7b0 pc=0x55a8381f8768\nruntime.goexit()\n\t/usr/lib/golang/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00004c7e8 sp=0xc00004c7e0 pc=0x55a83823a021\ncreated by runtime.gcenable\n\t/usr/lib/golang/src/runtime/mgc.go:181 +0x55\n\ngoroutine 19 [GC scavenge wait]:\nruntime.gopark(0x0, 0x0, 0x0, 0x0, 0x0)\n\t/usr/lib/golang/src/runtime/proc.go:366 +0xd6 fp=0xc00004cf80 sp=0xc00004cf60 pc=0x55a83820c316\nruntime.goparkunlock(...)\n\t/usr/lib/golang/src/runtime/proc.go:372\nruntime.bgscavenge()\n\t/usr/lib/golang/src/runtime/mgcscavenge.go:265 +0xcd fp=0xc00004cfe0 sp=0xc00004cf80 pc=0x55a8381f686d\nruntime.goexit()\n\t/usr/lib/golang/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00004cfe8 sp=0xc00004cfe0 pc=0x55a83823a021\ncreated by runtime.gcenable\n\t/usr/lib/golang/src/runtime/mgc.go:182 +0x65\n\ngoroutine 34 [finalizer wait]:\nruntime.gopark(0x55a838c3dd00, 0xc000050770, 0x71, 0x90, 0x55a838c21fe0)\n\t/usr/lib/golang/src/runtime/proc.go:366 +0xd6 fp=0xc000050630 sp=0xc000050610 pc=0x55a83820c316\nruntime.goparkunlock(...)\n\t/usr/lib/golang/src/runtime/proc.go:372\nruntime.runfinq()\n\t/usr/lib/golang/src/runtime/mfinal.go:177 +0xb3 fp=0xc0000507e0 sp=0xc000050630 pc=0x55a8381ee293\nruntime.goexit()\n\t/usr/lib/golang/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0000507e8 sp=0xc0000507e0 pc=0x55a83823a021\ncreated by runtime.createfing\n\t/usr/lib/golang/src/runtime/mfinal.go:157 +0x45\n\nrax 0x0\nrbx 0x6\nrcx 0x7f44c675737f\nrdx 0x0\nrdi 0x2\nrsi 0x7ffcf68dc6d0\nrbp 0x7ffcf68dc946\nrsp 0x7ffcf68dc6d0\nr8 0x0\nr9 0x7ffcf68dc6d0\nr10 0x8\nr11 0x246\nr12 0x7ffcf68dd0e8\nr13 0x7ffcf68dd100\nr14 0x7f449cb95c38\nr15 0x0\nrip 0x7f44c675737f\nrflags 0x246\ncs 0x33\nfs 0x0\ngs 0x0\n\n-----\n\nSIGQUIT: quit\nPC=0x55a83823bdc3 m=2 sigcode=0\n\ngoroutine 0 [idle]:\nruntime.futex()\n\t/usr/lib/golang/src/runtime/sys_linux_amd64.s:520 +0x23 fp=0x7f449fc0dd28 sp=0x7f449fc0dd20 pc=0x55a83823bdc3\nruntime.futexsleep(0xe56462b1ef2, 0xf68dcc4f, 0xc0000009c0)\n\t/usr/lib/golang/src/runtime/os_linux.go:50 +0xb1 fp=0x7f449fc0dd78 sp=0x7f449fc0dd28 pc=0x55a8382058f1\nruntime.notetsleep_internal(0x55a838c3f478, 0xdf8475800)\n\t/usr/lib/golang/src/runtime/lock_futex.go:202 +0xc5 fp=0x7f449fc0ddb8 sp=0x7f449fc0dd78 pc=0x55a8381e1745\nruntime.notetsleep(0xe56462b1ba5, 0x7f4400000002)\n\t/usr/lib/golang/src/runtime/lock_futex.go:225 +0x34 fp=0x7f449fc0ddd8 sp=0x7f449fc0ddb8 pc=0x55a8381e1894\nruntime.sysmon()\n\t/usr/lib/golang/src/runtime/proc.go:5374 +0x1db fp=0x7f449fc0de40 sp=0x7f449fc0ddd8 pc=0x55a83821727b\nruntime.mstart1()\n\t/usr/lib/golang/src/runtime/proc.go:1407 +0x95 fp=0x7f449fc0de68 sp=0x7f449fc0de40 pc=0x55a83820eb55\nruntime.mstart0()\n\t/usr/lib/golang/src/runtime/proc.go:1365 +0x79 fp=0x7f449fc0de98 sp=0x7f449fc0de68 pc=0x55a83820ea99\nruntime.mstart()\n\t/usr/lib/golang/src/runtime/asm_amd64.s:248 +0x5 fp=0x7f449fc0dea0 sp=0x7f449fc0de98 pc=0x55a838237ce5\nrax 0xfffffffffffffffc\nrbx 0x0\nrcx 0x55a83823bdc3\nrdx 0x0\nrdi 0x55a838c3f478\nrsi 0x80\nrbp 0x7f449fc0dd68\nrsp 0x7f449fc0dd20\nr8 0x0\nr9 0x0\nr10 0x7f449fc0dd58\nr11 0x246\nr12 0x7f449fc0dd58\nr13 0x7ffcf68dcc4f\nr14 0xc0000009c0\nr15 0x7f449fc0dfc0\nrip 0x55a83823bdc3\nrflags 0x246\ncs 0x33\nfs 0x0\ngs 0x0\n\n-----\n\nSIGQUIT: quit\nPC=0x55a83823bdc1 m=3 sigcode=0\n\ngoroutine 0 [idle]:\nruntime.futex()\n\t/usr/lib/golang/src/runtime/sys_linux_amd64.s:519 +0x21 fp=0x7f449f40cc38 sp=0x7f449f40cc30 pc=0x55a83823bdc1\nruntime.futexsleep(0xc000030800, 0x9f40cd18, 0x7f449f40cd30)\n\t/usr/lib/golang/src/runtime/os_linux.go:44 +0x36 fp=0x7f449f40cc88 sp=0x7f449f40cc38 pc=0x55a838205876\nruntime.notesleep(0xc000054950)\n\t/usr/lib/golang/src/runtime/lock_futex.go:160 +0x87 fp=0x7f449f40ccc0 sp=0x7f449f40cc88 pc=0x55a8381e1607\nruntime.mPark()\n\t/usr/lib/golang/src/runtime/proc.go:1441 +0x2a fp=0x7f449f40cce0 sp=0x7f449f40ccc0 pc=0x55a83820ec4a\nruntime.stopm()\n\t/usr/lib/golang/src/runtime/proc.go:2408 +0x78 fp=0x7f449f40cd08 sp=0x7f449f40cce0 pc=0x55a838210198\nruntime.findrunnable()\n\t/usr/lib/golang/src/runtime/proc.go:2984 +0x865 fp=0x7f449f40cdf8 sp=0x7f449f40cd08 pc=0x55a838211665\nruntime.schedule()\n\t/usr/lib/golang/src/runtime/proc.go:3367 +0x239 fp=0x7f449f40ce40 sp=0x7f449f40cdf8 pc=0x55a838212599\nruntime.mstart1()\n\t/usr/lib/golang/src/runtime/proc.go:1414 +0xcf fp=0x7f449f40ce68 sp=0x7f449f40ce40 pc=0x55a83820eb8f\nruntime.mstart0()\n\t/usr/lib/golang/src/runtime/proc.go:1365 +0x79 fp=0x7f449f40ce98 sp=0x7f449f40ce68 pc=0x55a83820ea99\nruntime.mstart()\n\t/usr/lib/golang/src/runtime/asm_amd64.s:248 +0x5 fp=0x7f449f40cea0 sp=0x7f449f40ce98 pc=0x55a838237ce5\nrax 0xca\nrbx 0x0\nrcx 0x55a83823bdc3\nrdx 0x0\nrdi 0xc000054950\nrsi 0x80\nrbp 0x7f449f40cc78\nrsp 0x7f449f40cc30\nr8 0x0\nr9 0x0\nr10 0x0\nr11 0x286\nr12 0xc000033000\nr13 0x203000\nr14 0xc000000ea0\nr15 0x7f449fd1311a\nrip 0x55a83823bdc1\nrflags 0x286\ncs 0x33\nfs 0x0\ngs 0x0\n\n-----\n\nSIGQUIT: quit\nPC=0x55a83823bdc1 m=4 sigcode=0\n\ngoroutine 0 [idle]:\nruntime.futex()\n\t/usr/lib/golang/src/runtime/sys_linux_amd64.s:519 +0x21 fp=0x7f449ec0bc28 sp=0x7f449ec0bc20 pc=0x55a83823bdc1\nruntime.futexsleep(0xc00002e000, 0x9ec0bd08, 0x7f449ec0bd20)\n\t/usr/lib/golang/src/runtime/os_linux.go:44 +0x36 fp=0x7f449ec0bc78 sp=0x7f449ec0bc28 pc=0x55a838205876\nruntime.notesleep(0xc000054d50)\n\t/usr/lib/golang/src/runtime/lock_futex.go:160 +0x87 fp=0x7f449ec0bcb0 sp=0x7f449ec0bc78 pc=0x55a8381e160, stdout: , stderr: , exit code -1" containerID="4a32680d8d62250d0d06c047cdafd9b07c9ab85d1279cb105ea58c5a62b2c167" cmd=[/bin/calico-node -bird-ready -felix-ready]
```
Note that we're deploying Calico using Kubespray.

We initially thought that runc is to blame, since the FIPS error is failing since we upgraded runc. However, after investigating the problem with Red Hat, as @gabrielericciardi stated, we gathered evidence that points towards the Calico container.

The readiness probe tries to execute `/bin/calico-node -bird-ready -felix-ready` in the container. Mimicking the readiness probe by executing `kubectl exec -t -n kube-system <calico_pod> -- /bin/calico-node -bird-ready -felix-ready` also triggers the fatal FIPS error. Actually, every `kubectl exec` on the Calico node pod triggers this FIPS error. Note that readiness and liveness probes of all other pods that are deployed complete successfully. The same goes for executing `kubectl exec` on other pods.

**Comment by caseydavenport** [comment]
Interesting, that certainly seems to suggest that there's a problem within Calico somehow. I'm surprised we haven't seen this sort of behavior in our own testing, so assuming this must be some combination of Calico and the environment triggering this scenario.

**Comment by basvandenbrink** [comment]
Could it be the case that the `clean-up-filesystem.sh` script deletes the hmac files during the container image build? Refer to https://github.com/projectcalico/calico/blob/master/node/Dockerfile.amd64#L217.

**Comment by jhamilton82** [comment]
We're also seeing this problem with Kubernetes 1.25.1, using kubeadm for install. Calico v3.24.1. CRI-O 1.25.0-6.4 for runtime engine

**Comment by caseydavenport** [comment]
Anyone interested in submitting a patch to clean-up-filesystem.sh and seeing if it works on their system? Would be great if someone experiencing this issue could confirm the fix.

**Comment by hjiawei** [comment]
I have a tentative fix in https://github.com/projectcalico/calico/pull/6852 to address the missing FIPS dependent files in calico-node image.

cc @caseydavenport

**Comment by jaredahamilton** [comment]
> Anyone interested in submitting a patch to clean-up-filesystem.sh and seeing if it works on their system? Would be great if someone experiencing this issue could confirm the fix.

I can test this build tomorrow at the latest and will try to report back

**Comment by jaredahamilton** [comment]
Looks like at a quick glance the fix is working. FIPS mode is enabled, RHEL 8.6, and calico-node is starting without issues.

**Comment by caseydavenport** [comment]
Fantastic, thanks much for the fix @hjiawei and for helping us validate it, @jaredahamilton!

Looks like it's merged now, so I'm going to close this issue.
