### ISSUE TITLE
Microk8s 1.24 on Ubuntu 22.04 64bit on Raspberry PI 4 repeatedly segfaulting

### ISSUE THREAD

**Issue by geekmarine72** [projectcalico/calico#6277]
## Expected Behavior
Calico should not suffer regular failures

## Current Behavior
Calico suffers multiple segfaults per minute, resulting in a lack of stability of the (7 node) Raspberry PI 4 microk8s on Ubuntu 22.04 cluster being unstable

## Possible Solution
Fix the code

## Steps to Reproduce (for bugs)
1. Acquire and wire up one or more Raspberry PI 4 (8gb version)
2. Flash ubuntu 22.04 onto sd cards using the Raspberry PI Imager, boot hosts, confirm connectivity
3. Using snap, install vanilla microk8s current (1.24) onto 
4. Monitor calico-node daemonset

## Context
1. Cannot continue experimentation and build out of my test K8S environment as instability in network results in inconsistent availability of hosted services
2.  MicroK8s cluster is running as close to bare minimum as possible.
3.  BT and WL disabled at firmware as a means to determine if it's impacting Calico (segfault occurs with and without wlan/bt enabled)

## Your Environment
* Calico version:  v3.21.4
* Orchestrator version: Ubuntu provided Microk8s (1.24)
* Operating System and version: Ubuntu 22.04 64-bit for ARM64

```
goroutine 92 [running]:
github.com/vishvananda/netlink.(*Handle).LinkList(0x0)
	/go/pkg/mod/github.com/vishvananda/netlink@v1.1.1-0.20210703095558-21f2c55a7727/link_linux.go:2008 +0x28
github.com/projectcalico/calico/felix/dataplane/linux.(*vxlanManager).getParentInterface(0x40001b4100, 0x4000c55a40)
	/go/src/github.com/projectcalico/calico/felix/dataplane/linux/vxlan_mgr.go:480 +0x3c
github.com/projectcalico/calico/felix/dataplane/linux.(*vxlanManager).getLocalVTEPParent(0x40001b4100)
	/go/src/github.com/projectcalico/calico/felix/dataplane/linux/vxlan_mgr.go:274 +0x34
github.com/projectcalico/calico/felix/dataplane/linux.(*vxlanManager).KeepVXLANDeviceInSync(0x40001b4100, 0x5aa, 0x0, 0x2540be400)
	/go/src/github.com/projectcalico/calico/felix/dataplane/linux/vxlan_mgr.go:449 +0x240
created by github.com/projectcalico/calico/felix/dataplane/linux.NewIntDataplaneDriver
	/go/src/github.com/projectcalico/calico/felix/dataplane/linux/int_dataplane.go:448 +0x1434
W0624 17:32:09.096759    7210 warnings.go:70] discovery.k8s.io/v1beta1 EndpointSlice is deprecated in v1.21+, unavailable in v1.25+; use discovery.k8s.io/v1 EndpointSlice
W0624 17:32:09.378806    7210 warnings.go:70] discovery.k8s.io/v1beta1 EndpointSlice is deprecated in v1.21+, unavailable in v1.25+; use discovery.k8s.io/v1 EndpointSlice
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1670b28]
goroutine 60 [running]:
github.com/vishvananda/netlink.(*Handle).LinkList(0x0)
	/go/pkg/mod/github.com/vishvananda/netlink@v1.1.1-0.20210703095558-21f2c55a7727/link_linux.go:2008 +0x28
github.com/projectcalico/calico/felix/dataplane/linux.(*vxlanManager).getParentInterface(0x4000053700, 0x4000806e40)
	/go/src/github.com/projectcalico/calico/felix/dataplane/linux/vxlan_mgr.go:480 +0x3c
github.com/projectcalico/calico/felix/dataplane/linux.(*vxlanManager).getLocalVTEPParent(0x4000053700)
	/go/src/github.com/projectcalico/calico/felix/dataplane/linux/vxlan_mgr.go:274 +0x34
github.com/projectcalico/calico/felix/dataplane/linux.(*vxlanManager).KeepVXLANDeviceInSync(0x4000053700, 0x5aa, 0x0, 0x2540be400)
	/go/src/github.com/projectcalico/calico/felix/dataplane/linux/vxlan_mgr.go:449 +0x240
created by github.com/projectcalico/calico/felix/dataplane/linux.NewIntDataplaneDriver
	/go/src/github.com/projectcalico/calico/felix/dataplane/linux/int_dataplane.go:448 +0x1434
W0624 17:32:11.079921    7243 warnings.go:70] discovery.k8s.io/v1beta1 EndpointSlice is deprecated in v1.21+, unavailable in v1.25+; use discovery.k8s.io/v1 EndpointSlice
W0624 17:32:11.566649    7243 warnings.go:70] discovery.k8s.io/v1beta1 EndpointSlice is deprecated in v1.21+, unavailable in v1.25+; use discovery.k8s.io/v1 EndpointSlice
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1670b28]
goroutine 90 [running]:
github.com/vishvananda/netlink.(*Handle).LinkList(0x0)
	/go/pkg/mod/github.com/vishvananda/netlink@v1.1.1-0.20210703095558-21f2c55a7727/link_linux.go:2008 +0x28
github.com/projectcalico/calico/felix/dataplane/linux.(*vxlanManager).getParentInterface(0x4000052c00, 0x4000a60540)
	/go/src/github.com/projectcalico/calico/felix/dataplane/linux/vxlan_mgr.go:480 +0x3c
github.com/projectcalico/calico/felix/dataplane/linux.(*vxlanManager).getLocalVTEPParent(0x4000052c00)
	/go/src/github.com/projectcalico/calico/felix/dataplane/linux/vxlan_mgr.go:274 +0x34
github.com/projectcalico/calico/felix/dataplane/linux.(*vxlanManager).KeepVXLANDeviceInSync(0x4000052c00, 0x5aa, 0x0, 0x2540be400)
	/go/src/github.com/projectcalico/calico/felix/dataplane/linux/vxlan_mgr.go:449 +0x240
created by github.com/projectcalico/calico/felix/dataplane/linux.NewIntDataplaneDriver
	/go/src/github.com/projectcalico/calico/felix/dataplane/linux/int_dataplane.go:448 +0x1434
W0624 17:32:15.166725    7302 warnings.go:70] discovery.k8s.io/v1beta1 EndpointSlice is deprecated in v1.21+, unavailable in v1.25+; use discovery.k8s.io/v1 EndpointSlice
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1670b28]
goroutine 93 [running]:
github.com/vishvananda/netlink.(*Handle).LinkList(0x0)
	/go/pkg/mod/github.com/vishvananda/netlink@v1.1.1-0.20210703095558-21f2c55a7727/link_linux.go:2008 +0x28
github.com/projectcalico/calico/felix/dataplane/linux.(*vxlanManager).getParentInterface(0x4000626000, 0x40007857c0)
	/go/src/github.com/projectcalico/calico/felix/dataplane/linux/vxlan_mgr.go:480 +0x3c
github.com/projectcalico/calico/felix/dataplane/linux.(*vxlanManager).getLocalVTEPParent(0x4000626000)
	/go/src/github.com/projectcalico/calico/felix/dataplane/linux/vxlan_mgr.go:274 +0x34
github.com/projectcalico/calico/felix/dataplane/linux.(*vxlanManager).KeepVXLANDeviceInSync(0x4000626000, 0x5aa, 0x0, 0x2540be400)
	/go/src/github.com/projectcalico/calico/felix/dataplane/linux/vxlan_mgr.go:449 +0x240
created by github.com/projectcalico/calico/felix/dataplane/linux.NewIntDataplaneDriver
	/go/src/github.com/projectcalico/calico/felix/dataplane/linux/int_dataplane.go:448 +0x1434
W0624 17:32:17.072296    7340 warnings.go:70] discovery.k8s.io/v1beta1 EndpointSlice is deprecated in v1.21+, unavailable in v1.25+; use discovery.k8s.io/v1 EndpointSlice
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1670b28]
goroutine 98 [running]:
github.com/vishvananda/netlink.(*Handle).LinkList(0x0)
	/go/pkg/mod/github.com/vishvananda/netlink@v1.1.1-0.20210703095558-21f2c55a7727/link_linux.go:2008 +0x28
github.com/projectcalico/calico/felix/dataplane/linux.(*vxlanManager).getParentInterface(0x40008ce000, 0x400085c440)
	/go/src/github.com/projectcalico/calico/felix/dataplane/linux/vxlan_mgr.go:480 +0x3c
github.com/projectcalico/calico/felix/dataplane/linux.(*vxlanManager).getLocalVTEPParent(0x40008ce000)
	/go/src/github.com/projectcalico/calico/felix/dataplane/linux/vxlan_mgr.go:274 +0x34
github.com/projectcalico/calico/felix/dataplane/linux.(*vxlanManager).KeepVXLANDeviceInSync(0x40008ce000, 0x5aa, 0x0, 0x2540be400)
	/go/src/github.com/projectcalico/calico/felix/dataplane/linux/vxlan_mgr.go:449 +0x240
created by github.com/projectcalico/calico/felix/dataplane/linux.NewIntDataplaneDriver
	/go/src/github.com/projectcalico/calico/felix/dataplane/linux/int_dataplane.go:448 +0x1434
W0624 17:32:18.971896    7373 warnings.go:70] discovery.k8s.io/v1beta1 EndpointSlice is deprecated in v1.21+, unavailable in v1.25+; use discovery.k8s.io/v1 EndpointSlice
W0624 17:32:19.272512    7373 warnings.go:70] discovery.k8s.io/v1beta1 EndpointSlice is deprecated in v1.21+, unavailable in v1.25+; use discovery.k8s.io/v1 EndpointSlice
2022-06-24 17:32:20.195 [ERROR][7373] felix/route_table.go 951: Failed to get link attributes error=interface not present ifaceRegex="^vxlan.calico$" ipVersion=0x4 tableIndex=0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1670b28]
goroutine 93 [running]:
github.com/vishvananda/netlink.(*Handle).LinkList(0x0)
	/go/pkg/mod/github.com/vishvananda/netlink@v1.1.1-0.20210703095558-21f2c55a7727/link_linux.go:2008 +0x28
github.com/projectcalico/calico/felix/dataplane/linux.(*vxlanManager).getParentInterface(0x40005ceb00, 0x40005990c0)
	/go/src/github.com/projectcalico/calico/felix/dataplane/linux/vxlan_mgr.go:480 +0x3c
github.com/projectcalico/calico/felix/dataplane/linux.(*vxlanManager).getLocalVTEPParent(0x40005ceb00)
	/go/src/github.com/projectcalico/calico/felix/dataplane/linux/vxlan_mgr.go:274 +0x34
github.com/projectcalico/calico/felix/dataplane/linux.(*vxlanManager).KeepVXLANDeviceInSync(0x40005ceb00, 0x5aa, 0x0, 0x2540be400)
	/go/src/github.com/projectcalico/calico/felix/dataplane/linux/vxlan_mgr.go:449 +0x240
created by github.com/projectcalico/calico/felix/dataplane/linux.NewIntDataplaneDriver
	/go/src/github.com/projectcalico/calico/felix/dataplane/linux/int_dataplane.go:448 +0x1434
Logs from Jun 24, 2022 to Jun 24, 2022 UTC
```

**Comment by geekmarine72** [comment]
Note, tested also Calico version: v3.23.2-arm64 which still has the same problematic netlink code.

**Comment by geekmarine72** [comment]
Note, the problem originates on line 2008 in an older version of the netlink code (07/03/2021): 
https://github.com/vishvananda/netlink/blob/21f2c55a7727da29b8e11aec300a6dff4543cb70/link_linux.go

This has been addressed in later versions

**Comment by caseydavenport** [comment]
@geekmarine72 thanks for raising - do you have a link to a fix PR I could look at? Or, do you know what version of vishvanada/netlink includes the fix?

**Comment by geekmarine72** [comment]
Reviewing the LinkList code in the link_linux.go appears to exist in all code revisions.  In the in use code, it's like 2008.  In later code including current appears at line 2099.  It is unclear best correction on code.  I am going to see if I can offer a PR to the netlink code to address their failure to detect nil linklist before attempting to append data msgs to it.

**Comment by penryu** [comment]
I had the same issue described above. Having tried all the other fixes to no avail, I found this issue:

https://github.com/canonical/microk8s/issues/3157

This fixed the issue for me.

HTH, Tim

**Comment by caseydavenport** [comment]
We've since updated the version of netlink we import: https://github.com/projectcalico/calico/pull/6295
