### ISSUE TITLE
3.23.3 calico-node status Init:CrashLoopBackOff

### ISSUE THREAD

**Issue by roger-gs** [projectcalico/calico#6715]
When the container starts, the container state is always Init:CrashLoopBackOff。which can be viewed through the kubectl describe command, and the following information is displayed：

root@master192 app]# kubectl describe pod -n kube-system calico-node-q75jq
Name:                 calico-node-q75jq
Namespace:            kube-system
Priority:             2000001000
Priority Class Name:  system-node-critical
Node:                 10.15.2.194/10.15.2.194
Start Time:           Thu, 15 Sep 2022 18:31:29 +0800
Labels:               controller-revision-hash=684bd4f6d9
                      k8s-app=calico-node
                      pod-template-generation=4
Annotations:          <none>
Status:               Pending
IP:                   10.15.2.194
IPs:
  IP:           10.15.2.194
Controlled By:  DaemonSet/calico-node
Init Containers:
  upgrade-ipam:
    Container ID:  docker://86ab5d8417a87f90a8af40bdad761b25649f7368ff2877ea06e638b42647c654
    Image:         docker.io/calico/cni:v3.23.2
    Image ID:      docker://sha256:a87d3f6f1b8fdc077e74ad6874301f57490f5b38cc731d5d6f5803f36837b4b1
    Port:          <none>
    Host Port:     <none>
    Command:
      /opt/cni/bin/calico-ipam
      -upgrade
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Thu, 15 Sep 2022 18:31:30 +0800
      Finished:     Thu, 15 Sep 2022 18:31:30 +0800
    Ready:          True
    Restart Count:  0
    Environment Variables from:
      kubernetes-services-endpoint  ConfigMap  Optional: true
    Environment:
      KUBERNETES_NODE_NAME:        (v1:spec.nodeName)
      CALICO_NETWORKING_BACKEND:  <set to the key 'calico_backend' of config map 'calico-config'>  Optional: false
    Mounts:
      /host/opt/cni/bin from cni-bin-dir (rw)
      /var/lib/cni/networks from host-local-net-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from calico-node-token-dt5w7 (ro)
  install-cni:
    Container ID:  docker://903de898bf462cb8ee956c946768832ecaf56325140ebc49b0006f1185a58e58
    Image:         docker.io/calico/cni:v3.23.2
    Image ID:      docker://sha256:a87d3f6f1b8fdc077e74ad6874301f57490f5b38cc731d5d6f5803f36837b4b1
    Port:          <none>
    Host Port:     <none>
    Command:
      /opt/cni/bin/install
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Thu, 15 Sep 2022 18:42:31 +0800
      Finished:     Thu, 15 Sep 2022 18:42:32 +0800
    Ready:          False
    Restart Count:  7
    Environment Variables from:
      kubernetes-services-endpoint  ConfigMap  Optional: true
    Environment:
      CNI_CONF_NAME:         10-calico.conflist
      CNI_NETWORK_CONFIG:    <set to the key 'cni_network_config' of config map 'calico-config'>  Optional: false
      KUBERNETES_NODE_NAME:   (v1:spec.nodeName)
      CNI_MTU:               <set to the key 'veth_mtu' of config map 'calico-config'>  Optional: false
      SLEEP:                 false
    Mounts:
      /host/etc/cni/net.d from cni-net-dir (rw)
      /host/opt/cni/bin from cni-bin-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from calico-node-token-dt5w7 (ro)
Containers:
  calico-node:
    Container ID:
    Image:          docker.io/calico/node:v3.23.2
    Image ID:
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:      250m
    Liveness:   exec [/bin/calico-node -felix-live -bird-live] delay=10s timeout=10s period=10s #success=1 #failure=6
    Readiness:  exec [/bin/calico-node -felix-ready -bird-ready] delay=0s timeout=10s period=10s #success=1 #failure=3
    Environment Variables from:
      kubernetes-services-endpoint  ConfigMap  Optional: true
    Environment:
      DATASTORE_TYPE:                     kubernetes
      WAIT_FOR_DATASTORE:                 true
      NODENAME:                            (v1:spec.nodeName)
      CALICO_NETWORKING_BACKEND:          <set to the key 'calico_backend' of config map 'calico-config'>  Optional: false
      CLUSTER_TYPE:                       k8s,bgp
      IP:                                 autodetect
      IP6:                                autodetect
      CALICO_IPV4POOL_IPIP:               Always
      CALICO_IPV4POOL_VXLAN:              Never
      CALICO_IPV6POOL_VXLAN:              Never
      FELIX_IPINIPMTU:                    <set to the key 'veth_mtu' of config map 'calico-config'>  Optional: false
      FELIX_VXLANMTU:                     <set to the key 'veth_mtu' of config map 'calico-config'>  Optional: false
      FELIX_WIREGUARDMTU:                 <set to the key 'veth_mtu' of config map 'calico-config'>  Optional: false
      CALICO_IPV4POOL_CIDR:               172.21.0.0/16
      CALICO_IPV6POOL_CIDR:               fc00::/48
      CALICO_DISABLE_FILE_LOGGING:        true
      FELIX_DEFAULTENDPOINTTOHOSTACTION:  ACCEPT
      FELIX_IPV6SUPPORT:                  true
      FELIX_HEALTHENABLED:                true
      IP_AUTODETECTION_METHOD:            can-reach=10.15.2.192
      IP6_AUTODETECTION_METHOD:           can-reach=2409:8c20:1831:503:100:2:b:1201
    Mounts:
      /host/etc/cni/net.d from cni-net-dir (rw)
      /lib/modules from lib-modules (ro)
      /run/xtables.lock from xtables-lock (rw)
      /sys/fs/ from sysfs (rw)
      /var/lib/calico from var-lib-calico (rw)
      /var/log/calico/cni from cni-log-dir (ro)
      /var/run/calico from var-run-calico (rw)
      /var/run/nodeagent from policysync (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from calico-node-token-dt5w7 (ro)
Conditions:
  Type              Status
  Initialized       False
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  lib-modules:
    Type:          HostPath (bare host directory volume)
    Path:          /lib/modules
    HostPathType:
  var-run-calico:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/calico
    HostPathType:
  var-lib-calico:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/calico
    HostPathType:
  xtables-lock:
    Type:          HostPath (bare host directory volume)
    Path:          /run/xtables.lock
    HostPathType:  FileOrCreate
  sysfs:
    Type:          HostPath (bare host directory volume)
    Path:          /sys/fs/
    HostPathType:  DirectoryOrCreate
  cni-bin-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /opt/kube/bin
    HostPathType:
  cni-net-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/cni/net.d
    HostPathType:
  cni-log-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /var/log/calico/cni
    HostPathType:
  host-local-net-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/cni/networks
    HostPathType:
  policysync:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/nodeagent
    HostPathType:  DirectoryOrCreate
  calico-node-token-dt5w7:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  calico-node-token-dt5w7
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  kubernetes.io/os=linux
Tolerations:     :NoScheduleop=Exists
                 :NoExecuteop=Exists
                 CriticalAddonsOnly op=Exists
                 node.kubernetes.io/disk-pressure:NoSchedule op=Exists
                 node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                 node.kubernetes.io/network-unavailable:NoSchedule op=Exists
                 node.kubernetes.io/not-ready:NoExecute op=Exists
                 node.kubernetes.io/pid-pressure:NoSchedule op=Exists
                 node.kubernetes.io/unreachable:NoExecute op=Exists
                 node.kubernetes.io/unschedulable:NoSchedule op=Exists
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  14m                   default-scheduler  Successfully assigned kube-system/calico-node-q75jq to 10.15.2.194
  Normal   Pulled     14m                   kubelet            Container image "docker.io/calico/cni:v3.23.2" already present on machine
  Normal   Created    14m                   kubelet            Created container upgrade-ipam
  Normal   Started    14m                   kubelet            Started container upgrade-ipam
  Normal   Started    13m (x4 over 14m)     kubelet            Started container install-cni
  Normal   Pulled     12m (x5 over 14m)     kubelet            Container image "docker.io/calico/cni:v3.23.2" already present on machine
  Normal   Created    12m (x5 over 14m)     kubelet            Created container install-cni
  Warning  BackOff    3m57s (x47 over 14m)  kubelet            Back-off restarting failed container

It shows that the install-cni container failed to start. View the log of the container through kubectl logs as follows:
[root@master192 app]# kubectl logs -n kube-system calico-node-q75jq -c install-cni
time="2022-09-15T10:47:43Z" level=info msg="Running as a Kubernetes pod" source="install.go:140"
2022-09-15 10:47:43.873 [INFO][1] cni-installer/<nil> <nil>: File is already up to date, skipping file="/host/opt/cni/bin/bandwidth"
2022-09-15 10:47:43.873 [INFO][1] cni-installer/<nil> <nil>: Installed /host/opt/cni/bin/bandwidth
2022-09-15 10:47:43.968 [INFO][1] cni-installer/<nil> <nil>: File is already up to date, skipping file="/host/opt/cni/bin/calico"
2022-09-15 10:47:43.968 [INFO][1] cni-installer/<nil> <nil>: Installed /host/opt/cni/bin/calico
2022-09-15 10:47:44.048 [INFO][1] cni-installer/<nil> <nil>: File is already up to date, skipping file="/host/opt/cni/bin/calico-ipam"
2022-09-15 10:47:44.048 [INFO][1] cni-installer/<nil> <nil>: Installed /host/opt/cni/bin/calico-ipam
2022-09-15 10:47:44.051 [INFO][1] cni-installer/<nil> <nil>: File is already up to date, skipping file="/host/opt/cni/bin/flannel"
2022-09-15 10:47:44.051 [INFO][1] cni-installer/<nil> <nil>: Installed /host/opt/cni/bin/flannel
2022-09-15 10:47:44.056 [INFO][1] cni-installer/<nil> <nil>: File is already up to date, skipping file="/host/opt/cni/bin/host-local"
2022-09-15 10:47:44.056 [INFO][1] cni-installer/<nil> <nil>: Installed /host/opt/cni/bin/host-local
2022-09-15 10:47:44.139 [INFO][1] cni-installer/<nil> <nil>: File is already up to date, skipping file="/host/opt/cni/bin/install"
2022-09-15 10:47:44.139 [INFO][1] cni-installer/<nil> <nil>: Installed /host/opt/cni/bin/install
2022-09-15 10:47:44.144 [INFO][1] cni-installer/<nil> <nil>: File is already up to date, skipping file="/host/opt/cni/bin/loopback"
2022-09-15 10:47:44.144 [INFO][1] cni-installer/<nil> <nil>: Installed /host/opt/cni/bin/loopback
2022-09-15 10:47:44.149 [INFO][1] cni-installer/<nil> <nil>: File is already up to date, skipping file="/host/opt/cni/bin/portmap"
2022-09-15 10:47:44.149 [INFO][1] cni-installer/<nil> <nil>: Installed /host/opt/cni/bin/portmap
2022-09-15 10:47:44.154 [INFO][1] cni-installer/<nil> <nil>: File is already up to date, skipping file="/host/opt/cni/bin/tuning"
2022-09-15 10:47:44.154 [INFO][1] cni-installer/<nil> <nil>: Installed /host/opt/cni/bin/tuning
2022-09-15 10:47:44.154 [INFO][1] cni-installer/<nil> <nil>: Wrote Calico CNI binaries to /host/opt/cni/bin

2022-09-15 10:47:44.186 [INFO][1] cni-installer/<nil> <nil>: CNI plugin version: v3.23.2

2022-09-15 10:47:44.186 [INFO][1] cni-installer/<nil> <nil>: /host/secondary-bin-dir is not writeable, skipping
W0915 10:47:44.186208       1 client_config.go:617] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
panic: interface conversion: interface {} is nil, not float64

goroutine 1 [running, locked to thread]:
github.com/projectcalico/calico/node/pkg/cni.tokenUpdateFromFile()
        /go/src/github.com/projectcalico/calico/node/pkg/cni/token_watch.go:209 +0x5d0
github.com/projectcalico/calico/node/pkg/cni.(*TokenRefresher).UpdateToken(0xc0008bfba0)
        /go/src/github.com/projectcalico/calico/node/pkg/cni/token_watch.go:102 +0x21c
github.com/projectcalico/calico/cni-plugin/pkg/install.writeKubeconfig(0xc0000b2900)
        /go/src/github.com/projectcalico/calico/cni-plugin/pkg/install/install.go:485 +0x1c6
github.com/projectcalico/calico/cni-plugin/pkg/install.Install()
        /go/src/github.com/projectcalico/calico/cni-plugin/pkg/install/install.go:243 +0xab1
main.main()
        /go/src/github.com/projectcalico/calico/cni-plugin/cmd/calico/calico.go:40 +0xf1

At the same time, I also tried to use version 3.23.2, the same error.

* Calico 3.23.3
* kubernetes 1.19.15
* CentOS 7.7

Is there anything I can try to fix it?

**Comment by felix0080** [comment]
我也遇到了，会不会是版本太低了？

**Comment by song-jiang** [comment]
@roger-gs This looks like a bug. Was it happening whenever you create a pod?

**Comment by hzhhong** [comment]
It should be caused by kubernetes version before v1.22. @roger-gs @song-jiang 

https://github.com/hzhhong/calico/blob/4ba921ee7be49b11f5edb3f89e8475809cedaed5/node/pkg/cni/token_watch.go#L101-L105

https://github.com/hzhhong/calico/blob/4ba921ee7be49b11f5edb3f89e8475809cedaed5/node/pkg/cni/token_watch.go#L180-L213

According to [Bound service account token volume mechanism ](https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#bound-service-account-token-volume), the token read from the file by the Kubernetes version before v1.22 will never expire, and there is no `exp` in cliamMap.
