### ISSUE TITLE
route_list not support in alpine pod

### ISSUE THREAD

**Issue by felix0080** [projectcalico/calico#6746]
when i run calico(3.23.1) in k8s(v1.23.0)

i get a error log 
 kubectl logs calico-node
```
2022-09-21 07:44:57.001 [ERROR][68] felix/route_rule.go 248: Failed to list routing rules, retrying... error=address family not supported by protocol ipVersion=4
2022-09-21 07:44:57.001 [WARNING][68] felix/int_dataplane.go 2000: Failed to synchronize routing table, will retry...
2022-09-21 07:44:57.108 [INFO][68] felix/wireguard.go 1701: Trying to connect to linkClient ipVersion=0x4
2022-09-21 07:44:57.108 [INFO][68] felix/route_rule.go 189: Trying to connect to netlink
2022-09-21 07:44:57.108 [ERROR][68] felix/route_rule.go 248: Failed to list routing rules, retrying... error=address family not supported by protocol ipVersion=4
2022-09-21 07:44:57.108 [WARNING][68] felix/int_dataplane.go 2000: Failed to synchronize routing table, will retry...
2022-09-21 07:44:57.215 [INFO][68] felix/wireguard.go 1701: Trying to connect to linkClient ipVersion=0x4
2022-09-21 07:44:57.215 [INFO][68] felix/route_rule.go 189: Trying to connect to netlink
2022-09-21 07:44:57.215 [ERROR][68] felix/route_rule.go 248: Failed to list routing rules, retrying... error=address family not supported by protocol ipVersion=4
2022-09-21 07:44:57.215 [WARNING][68] felix/int_dataplane.go 2000: Failed to synchronize routing table, will retry...
2022-09-21 07:44:57.325 [INFO][68] felix/wireguard.go 1701: Trying to connect to linkClient ipVersion=0x4
2022-09-21 07:44:57.325 [INFO][68] felix/route_rule.go 189: Trying to connect to netlin
```
but pod status is running
```
bash-5.1# kubectl get pod -A
NAMESPACE     NAME                                       READY   STATUS    RESTARTS   AGE
kube-system   calico-kube-controllers-66966888c4-84fsj   1/1     Running   0          19m
kube-system   calico-node-4b9bm                          1/1     Running   0          19m
kube-system   coredns-7996d76bb4-57p24                   1/1     Running   0          20m
```
k8s version:1.23.0
calico version 3.23.1
os: alpine 3.14 

What kind of question is that

**Comment by lwr20** [comment]
Can you change node OS to something more mainstream?  Perhaps flatcar linux?

**Comment by coutinhop** [comment]
Closing this as inactive. Feel free to reopen if you're still having issues...

**Comment by gwgrisk** [comment]
I have encountered a system issue on an embedded device with a customized kernel. I have resolved the issues with ipset, iptable XT_SET, and network policies, which seemed to have been resolved by enabling the corresponding kernel options. However, the Calico pod keeps crashing, and the logs show the following:

`2023-05-10 03:59:29.459 [INFO][442287] felix/wireguard.go 1664: Trying to connect to linkClient
2023-05-10 03:59:29.468 [INFO][442287] felix/route_rule.go 188: Trying to connect to netlink
2023-05-10 03:59:29.468 [ERROR][442287] felix/route_rule.go 248: Failed to list routing rules, retrying... error=address family not supported by protocol ipVersion=4
2023-05-10 03:59:29.469 [WARNING][442287] felix/int_dataplane.go 1905: Failed to synchronize routing table, will retry...
2023-05-10 03:59:29.475 [INFO][442287] felix/ipsets.go 785: Doing full IP set rewrite family="inet" numMembersInPendingReplace=1 setID="all-ipam-pools"
2023-05-10 03:59:29.476 [INFO][442287] felix/ipsets.go 785: Doing full IP set rewrite family="inet" numMembersInPendingReplace=1 setID="masq-ipam-pools"
2023-05-10 03:59:29.476 [INFO][442287] felix/ipsets.go 785: Doing full IP set rewrite family="inet" numMembersInPendingReplace=6 setID="this-host"
2023-05-10 03:59:29.477 [INFO][442287] felix/ipsets.go 785: Doing full IP set rewrite family="inet" numMembersInPendingReplace=2 setID="all-hosts-net"
2023-05-10 03:59:29.567 [WARNING][442287] felix/table.go 816: iptables save failed error=exit status 1
2023-05-10 03:59:29.567 [WARNING][442287] felix/table.go 765: iptables-legacy-save command failed error=exit status 1 ipVersion=0x4 stderr="" table="raw"
2023-05-10 03:59:29.681 [WARNING][442287] felix/table.go 816: iptables save failed error=exit status 1
2023-05-10 03:59:29.682 [WARNING][442287] felix/table.go 765: iptables-legacy-save command failed error=exit status 1 ipVersion=0x4 stderr="" table="raw"
2023-05-10 03:59:29.896 [WARNING][442287] felix/table.go 816: iptables save failed error=exit status 1
2023-05-10 03:59:29.896 [WARNING][442287] felix/table.go 765: iptables-legacy-save command failed error=exit status 1 ipVersion=0x4 stderr="" table="raw"
2023-05-10 03:59:30.311 [WARNING][442287] felix/table.go 816: iptables save failed error=exit status 1
2023-05-10 03:59:30.312 [WARNING][442287] felix/table.go 765: iptables-legacy-save command failed error=exit status 1 ipVersion=0x4 stderr="" table="raw"
2023-05-10 03:59:30.312 [PANIC][442287] felix/table.go 771: iptables-legacy-save command failed after retries ipVersion=0x4 table="raw"
panic: (*logrus.Entry) 0x40001702a0

goroutine 250 [running]:
github.com/sirupsen/logrus.(*Entry).log(0x40003e16c0, 0x0, {0x40009ec2c0, 0x31})
        /go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/entry.go:259 +0x2cc
github.com/sirupsen/logrus.(*Entry).Log(0x40003e16c0, 0x0, {0x4000b28a18, 0x1, 0x1})
        /go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/entry.go:293 +0x7c
github.com/sirupsen/logrus.(*Entry).Logf(0x40003e16c0, 0x0, {0x2bfe413, 0x1f}, {0x4000b28ae8, 0x1, 0x1})
        /go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/entry.go:338 +0xbc
github.com/sirupsen/logrus.(*Entry).Panicf(...)
        /go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/entry.go:376
github.com/projectcalico/calico/felix/iptables.(*Table).getHashesAndRulesFromDataplane(0x4000697200)
        /go/src/github.com/projectcalico/calico/felix/iptables/table.go:771 +0x3c8
github.com/projectcalico/calico/felix/iptables.(*Table).loadDataplaneState(0x4000697200)
        /go/src/github.com/projectcalico/calico/felix/iptables/table.go:608 +0x184
github.com/projectcalico/calico/felix/iptables.(*Table).Apply(0x4000697200)
        /go/src/github.com/projectcalico/calico/felix/iptables/table.go:992 +0x340
github.com/projectcalico/calico/felix/dataplane/linux.(*InternalDataplane).apply.func4(0x4000894060, 0x4000894068, 0x4000470a00, 0x4000894070, 0x4000697200)
        /go/src/github.com/projectcalico/calico/felix/dataplane/linux/int_dataplane.go:1939 +0x34
created by github.com/projectcalico/calico/felix/dataplane/linux.(*InternalDataplane).apply
        /go/src/github.com/projectcalico/calico/felix/dataplane/linux/int_dataplane.go:1938 +0x77c`

**Comment by czocher** [comment]
This is due to a missing RAW kernel module:

```
CONFIG_NETFILTER=y
CONFIG_NETFILTER_XTABLES=y
CONFIG_NETFILTER_XTABLES_RAW=y
CONFIG_IP6_NF_RAW=y
CONFIG_IP_NF_RAW=y     # For IPv4 raw table support
```
are missing from your kernel config.
