### ISSUE TITLE
docker install calico blocked by calico-node -felix

### ISSUE THREAD

**Issue by lw33** [projectcalico/calico#6859]
## Expected Behavior

install success
## Current Behavior

docker log is empy. 
calicoctl get node return empty.
## Possible Solution

run `calico-node -startup` in container calico will start.
## Steps to Reproduce (for bugs)

[Container install](https://projectcalico.docs.tigera.io/getting-started/bare-metal/installation/container)

## Your Environment

* Calico version v3.24.1
* etcd version {"etcdserver":"3.5.5","etcdcluster":"3.5.0"}
* Operating System and version: CentOS Linux release 7.9.2009 3.10.0-1160.45.1.el7.x86_64
* Link to your project (optional):

**Comment by lw33** [comment]
stack
`
Thread 7 (Thread 0x7f89fdc00700 (LWP 94962)):
#0  0x0000000000477e83 in runtime.futex.abi0 ()
#1  0x0000000000441076 in runtime.futexsleep ()
#2  0x000000c0003f4d48 in ?? ()
#3  0x0000000000000080 in ?? ()
#4  0x0000000000000000 in ?? ()
Thread 6 (Thread 0x7f89fe5a1700 (LWP 94961)):
#0  0x0000000000477e83 in runtime.futex.abi0 ()
#1  0x0000000000441076 in runtime.futexsleep ()
#2  0x00000000049bdb78 in runtime.newmHandoff ()
#3  0x0000000000000080 in ?? ()
#4  0x0000000000000000 in ?? ()
Thread 5 (Thread 0x7f89feda2700 (LWP 94960)):
#0  0x0000000000477e83 in runtime.futex.abi0 ()
#1  0x0000000000441076 in runtime.futexsleep ()
#2  0x000000c000077148 in ?? ()
#3  0x0000000000000080 in ?? ()
#4  0x0000000000000000 in ?? ()
Thread 4 (Thread 0x7f89ff5e3700 (LWP 94959)):
#0  0x0000000000477e83 in runtime.futex.abi0 ()
#1  0x0000000000441076 in runtime.futexsleep ()
#2  0x000000c000076d48 in ?? ()
#3  0x0000000000000080 in ?? ()
#4  0x0000000000000000 in ?? ()
Thread 3 (Thread 0x7f89ffde4700 (LWP 94958)):
#0  0x00000000004780a0 in runtime.epollwait.abi0 ()
#1  0x0000000000440d9c in runtime.netpoll ()
#2  0x0000000000000004 in ?? ()
#3  0x00007f89ffde36d0 in ?? ()
#4  0x000003e700000080 in ?? ()
#5  0x0000000000000000 in ?? ()
Thread 2 (Thread 0x7f8a00785700 (LWP 94957)):
#0  0x0000000000477e83 in runtime.futex.abi0 ()
#1  0x00000000004410ef in runtime.futexsleep ()
#2  0x000000000498d958 in runtime.sched ()
#3  0x0000000000000080 in ?? ()
#4  0x00007f8a00784d40 in ?? ()
#5  0x0000000000000000 in ?? ()
Thread 1 (Thread 0x7f8a27417c00 (LWP 94956)):
#0  0x0000000000477e83 in runtime.futex.abi0 ()
#1  0x0000000000441076 in runtime.futexsleep ()
#2  0x000000000498b568 in runtime.m0 ()
#3  0x0000000000000080 in ?? ()
#4  0x0000000000000000 in ?? ()
`

**Comment by lw33** [comment]
stack:
Thread 7 (Thread 0x7f89fdc00700 (LWP 94962)):
#0  0x0000000000477e83 in runtime.futex.abi0 ()
#1  0x0000000000441076 in runtime.futexsleep ()
#2  0x000000c0003f4d48 in ?? ()
#3  0x0000000000000080 in ?? ()
#4  0x0000000000000000 in ?? ()
Thread 6 (Thread 0x7f89fe5a1700 (LWP 94961)):
#0  0x0000000000477e83 in runtime.futex.abi0 ()
#1  0x0000000000441076 in runtime.futexsleep ()
#2  0x00000000049bdb78 in runtime.newmHandoff ()
#3  0x0000000000000080 in ?? ()
#4  0x0000000000000000 in ?? ()
Thread 5 (Thread 0x7f89feda2700 (LWP 94960)):
#0  0x0000000000477e83 in runtime.futex.abi0 ()
#1  0x0000000000441076 in runtime.futexsleep ()
#2  0x000000c000077148 in ?? ()
#3  0x0000000000000080 in ?? ()
#4  0x0000000000000000 in ?? ()
Thread 4 (Thread 0x7f89ff5e3700 (LWP 94959)):
#0  0x0000000000477e83 in runtime.futex.abi0 ()
#1  0x0000000000441076 in runtime.futexsleep ()
#2  0x000000c000076d48 in ?? ()
#3  0x0000000000000080 in ?? ()
#4  0x0000000000000000 in ?? ()
Thread 3 (Thread 0x7f89ffde4700 (LWP 94958)):
#0  0x00000000004780a0 in runtime.epollwait.abi0 ()
#1  0x0000000000440d9c in runtime.netpoll ()
#2  0x0000000000000004 in ?? ()
#3  0x00007f89ffde36d0 in ?? ()
#4  0x000003e700000080 in ?? ()
#5  0x0000000000000000 in ?? ()
Thread 2 (Thread 0x7f8a00785700 (LWP 94957)):
#0  0x0000000000477e83 in runtime.futex.abi0 ()
#1  0x00000000004410ef in runtime.futexsleep ()
#2  0x000000000498d958 in runtime.sched ()
#3  0x0000000000000080 in ?? ()
#4  0x00007f8a00784d40 in ?? ()
#5  0x0000000000000000 in ?? ()
Thread 1 (Thread 0x7f8a27417c00 (LWP 94956)):
#0  0x0000000000477e83 in runtime.futex.abi0 ()
#1  0x0000000000441076 in runtime.futexsleep ()
#2  0x000000000498b568 in runtime.m0 ()
#3  0x0000000000000080 in ?? ()
#4  0x0000000000000000 in ?? ()

**Comment by lw33** [comment]
anyone know how to debug this
