### ISSUE TITLE
Tigera operator unable to initialise in fresh EKS cluster

### ISSUE THREAD

**Issue by konck1** [projectcalico/calico#7004]
Below is a snippet of code which allows you to deploy Helm charts using Terraform into your K8s cluster, in this case its EKS. During deployment of tigera operator for calico, If you set `installation.kubernetesProvider` to `EKS`, the deployment fails. If you remove this value completely, the deployment succeeds.

```
resource "helm_release" "tigera_calico" {
  name             = "tigera-calico-release"
  repository       = "https://projectcalico.docs.tigera.io/charts"
  chart            = "tigera-operator"
  cleanup_on_fail  = false
  create_namespace = true
  max_history      = 5
  namespace        = "tigera-operator"
  timeout          = 300
  version          = "3.24.5"

  set {
    name  = "installation.kubernetesProvider"
    value = "EKS"
  }
}
```

Documentation https://projectcalico.docs.tigera.io/reference/installation/api#operator.tigera.io/v1.Installation, mentions something about being `default` but does not go into details what should be `default`.

I have attempted by specifying these Helm values as well, with the same result:
```
  set {
    name  = "installation.kubernetesProvider"
    value = "EKS"
  }

  set {
    name  = "installation.cni.type"
    value = "Calico"
  }

  set {
    name  = "installation.cni.ipam.type"
    value = "Calico"
  }
```

## Expected Behavior

Successful deployment of tigera operator and calico node using Terraform Helm charts.

## Current Behavior

tigera-operator
```
{"level":"error","ts":1668610270.9678032,"msg":"Reconciler error","controller":"apiserver-controller","object":{"name":"calico-apiserver-certs","namespace":"tigera-operator"},"namespace":"tigera-operator","name":"calico-apiserver-certs","reconcileID":"ec608129-247f-4218-b31a-c5ced1cb06cd","error":"Installation.operator.tigera.io \"default\" not found","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234"}
```

calico-apiserver
```
F1116 17:21:58.585724 1 server.go:73] error running server (unable to load configmap based request-header-client-ca-file: Get "https://172.20.0.1:443/api/v1/namespaces/kube-system/configmaps/extension-apiserver-authentication": dial tcp 172.20.0.1:443: i/o timeout)
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0x1)
 /go/pkg/mod/k8s.io/klog/v2@v2.60.1/klog.go:860 +0x8a
k8s.io/klog/v2.(*loggingT).output(0x38bb740, 0x3, 0x0, 0xc0008527e0, 0x1, {0x2d42bba?, 0x1?}, 0xc000510000?, 0x0)
 /go/pkg/mod/k8s.io/klog/v2@v2.60.1/klog.go:825 +0x686
...
...
...
goroutine 97 [select]:
k8s.io/client-go/util/workqueue.(*delayingType).waitingLoop(0xc0000cf2c0)
 /go/pkg/mod/k8s.io/client-go@v0.24.0/util/workqueue/delaying_queue.go:233 +0x305
created by k8s.io/client-go/util/workqueue.newDelayingQueue
 /go/pkg/mod/k8s.io/client-go@v0.24.0/util/workqueue/delaying_queue.go:70 +0x24f
```

## Steps to Reproduce (for bugs)

1. Create terraform code with the above snippet code
2. run `terraform apply` to deploy into your EKS cluster.
3. check logs
4.

## Your Environment

* Calico version 3.24.5
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by mgleung** [comment]
Hi @konck1 , are the helm charts you are referencing the ones from the EKS documentation? I believe that we do not maintain those helm charts so that might be the root cause of your issue. Have you tried following our docs to install here: https://projectcalico.docs.tigera.io/getting-started/kubernetes/managed-public-cloud/eks ?

**Comment by caseydavenport** [comment]
> , are the helm charts you are referencing the ones from the EKS documentation? I believe that we do not maintain those helm charts so that might be the root cause of your issue.

The helm charts in the EKS documentation are our helm charts, so yes we do maintain them :grin: 

> https://projectcalico.docs.tigera.io/charts"

And from the description, our chart is being used. 

What does this command return?

```
kubectl get installations
```

**Comment by lwr20** [comment]
Closing due to inactivity, please reopen once you have the answer to @caseydavenport 's question.

**Comment by BMonsalvatge** [comment]
I am running into the same issue and i get the following:

```
> kubectl get installations
No resources found
```
