### ISSUE TITLE
calico v3.22.1 typha restarts, the status of container is crashloopbackoff,cluster is unavailable

### ISSUE THREAD

**Issue by BearDare** [projectcalico/calico#7553]
Calico cluster crashes after running for a while, calico-typha containers is as follows
```
[FATAL][6] daemon.go 450: Received SIGTERM, shutting down
```
Rebuild the typha container, the status of the typha container is crashloopbackoff.  there is no typha instance, the calico node is restarting, cluster is unavailable

Screenshots of monitoring when calico crashed
**master** 
![YMiSFLECYT](https://user-images.githubusercontent.com/19593951/231972464-b7eb96ab-03d0-4d9e-b2ea-adf322051148.jpg)
**node2**
![YMiSFLECYT](https://user-images.githubusercontent.com/19593951/231972518-a30677e5-de73-4ab4-a5d8-7044f3e3ae2c.jpg)
**node3*
![YMiSFLECYT](https://user-images.githubusercontent.com/19593951/231972404-a1dcd2ac-0d5d-4d8a-a45e-212dbf09e075.jpg)，

Similar to other nodes，When the problem occurs, the main abnormality is in the network traffic, other cpu, memory have no obvious abnormality

## Expected Behavior

Expect calico components to work fine

## Current Behavior
the status of typha  container  is crashloopbackoff

## Possible Solution
Follow the documentation to upgrade calico v3.22.1 to v3.25.1, however  calico-typha  container state is still ContainerNotReady
calico-typha logs is as folloews 
```
[INFO][6] health.go 172: Health of component changed name="felix-cache" newReport="live,ready" oldReport="live,non-ready"

[WARNING][6] rebalance.go 54: Failed to get number of Typhas error=<nil> numTyphas=0 thread="k8s-poll"

[WARNING][6] daemon.go 459: Received SIGTERM, shutting down

[INFO][6] sync_server.go 651: Starting graceful shutdown...
 panic: runtime error: integer divide by zero

 goroutine 172 [running]:

 github.com/projectcalico/calico/typha/pkg/syncserver.(*Server).handleGracefulShutDown(0xc0004ce000, {0x20ee610, 0xc0004d7f40}, 0xc000039960)

 	/go/src/github.com/projectcalico/calico/typha/pkg/syncserver/sync_server.go:576 +0x878

 created by github.com/projectcalico/calico/typha/pkg/syncserver.(*Server).Start

 	/go/src/github.com/projectcalico/calico/typha/pkg/syncserver/sync_server.go:312 +0x1ac
```

##  Environment

* Calico version v3.22.1
* Orchestrator version :kubernetes:v1.21.14 1 master 4 node
* Operating System and version:CentOS 7.9

**Comment by sridhartigera** [comment]
@fasaxc Any idea on this?

**Comment by sridhartigera** [comment]
@fasaxc Any idea on this?

**Comment by BearDare** [comment]
ok, thanks for the reply, the cluster has been re-deployed, and the event cannot be viewed, this issue can be closed。The following is typha's log

```
2023-04-18 05:40:39.759 [INFO][6] watchercache.go 273: Sending synced update ListRoot="/calico/resources/v3/projectcalico.org/caliconodestatuses"
2023-04-18 05:40:39.760 [INFO][6] watchercache.go 273: Sending synced update ListRoot="/calico/resources/v3/projectcalico.org/kubernetesnetworkpolicies"
2023-04-18 05:40:39.760 [INFO][6] watchercache.go 273: Sending synced update ListRoot="/calico/resources/v3/projectcalico.org/bgpconfigurations"
2023-04-18 05:40:39.760 [INFO][6] watchersyncer.go 209: Received InSync event from one of the watcher caches
2023-04-18 05:40:39.760 [INFO][6] watchersyncer.go 209: Received InSync event from one of the watcher caches
2023-04-18 05:40:39.760 [INFO][6] watchersyncer.go 127: Sending status update Status=resync
2023-04-18 05:40:39.760 [INFO][6] watchersyncer.go 221: All watchers have sync'd data - sending data and final sync
2023-04-18 05:40:39.760 [INFO][6] watchersyncer.go 127: Sending status update Status=in-sync
2023-04-18 05:40:39.760 [INFO][6] cache.go 243: Received status update message from datastore. status=resync
2023-04-18 05:40:39.760 [INFO][6] cache.go 243: Received status update message from datastore. status=in-sync
2023-04-18 05:40:39.760 [INFO][6] watchercache.go 273: Sending synced update ListRoot="/calico/resources/v3/projectcalico.org/felixconfigurations"
2023-04-18 05:40:39.760 [INFO][6] health.go 133: Health of component changed lastReport=health.HealthReport{Live:true, Ready:false} name="node-status" newReport=&health.HealthReport{Live:true, Ready:true}
2023-04-18 05:40:39.761 [INFO][6] watchersyncer.go 209: Received InSync event from one of the watcher caches
2023-04-18 05:40:39.761 [INFO][6] watchersyncer.go 209: Received InSync event from one of the watcher caches
W0418 05:40:39.763628       6 warnings.go:70] discovery.k8s.io/v1beta1 EndpointSlice is deprecated in v1.21+, unavailable in v1.25+; use discovery.k8s.io/v1 EndpointSlice
2023-04-18 05:40:39.764 [INFO][6] watchercache.go 273: Sending synced update ListRoot="/calico/resources/v3/projectcalico.org/nodes"
2023-04-18 05:40:39.764 [INFO][6] watchersyncer.go 209: Received InSync event from one of the watcher caches
2023-04-18 05:40:39.764 [INFO][6] watchercache.go 273: Sending synced update ListRoot="/calico/resources/v3/projectcalico.org/nodes"
2023-04-18 05:40:39.764 [INFO][6] watchersyncer.go 209: Received InSync event from one of the watcher caches
2023-04-18 05:40:39.764 [INFO][6] watchersyncer.go 221: All watchers have sync'd data - sending data and final sync
2023-04-18 05:40:39.764 [INFO][6] watchersyncer.go 127: Sending status update Status=in-sync
2023-04-18 05:40:39.764 [INFO][6] cache.go 243: Received status update message from datastore. status=in-sync
2023-04-18 05:40:39.764 [INFO][6] health.go 133: Health of component changed lastReport=health.HealthReport{Live:true, Ready:false} name="tunnel-ip-allocation" newReport=&health.HealthReport{Live:true, Ready:true}
2023-04-18 05:40:39.768 [INFO][6] watchercache.go 273: Sending synced update ListRoot="/calico/resources/v3/projectcalico.org/nodes"
2023-04-18 05:40:39.768 [INFO][6] watchersyncer.go 209: Received InSync event from one of the watcher caches
2023-04-18 05:40:39.768 [INFO][6] watchersyncer.go 221: All watchers have sync'd data - sending data and final sync
2023-04-18 05:40:39.768 [INFO][6] watchersyncer.go 127: Sending status update Status=in-sync
2023-04-18 05:40:39.769 [INFO][6] cache.go 243: Received status update message from datastore. status=in-sync
2023-04-18 05:40:39.769 [INFO][6] health.go 133: Health of component changed lastReport=health.HealthReport{Live:true, Ready:false} name="bgp" newReport=&health.HealthReport{Live:true, Ready:true}
2023-04-18 05:40:39.770 [INFO][6] watchercache.go 273: Sending synced update ListRoot="/calico/resources/v3/projectcalico.org/profiles"
2023-04-18 05:40:39.770 [INFO][6] watchersyncer.go 209: Received InSync event from one of the watcher caches
2023-04-18 05:40:39.771 [INFO][6] watchercache.go 273: Sending synced update ListRoot="/calico/resources/v3/projectcalico.org/kubernetesendpointslices"
2023-04-18 05:40:39.772 [INFO][6] watchersyncer.go 209: Received InSync event from one of the watcher caches
W0418 05:40:39.772303       6 warnings.go:70] discovery.k8s.io/v1beta1 EndpointSlice is deprecated in v1.21+, unavailable in v1.25+; use discovery.k8s.io/v1 EndpointSlice
2023-04-18 05:40:39.802 [INFO][6] watchercache.go 273: Sending synced update ListRoot="/calico/resources/v3/projectcalico.org/workloadendpoints"
2023-04-18 05:40:39.803 [INFO][6] watchersyncer.go 209: Received InSync event from one of the watcher caches
2023-04-18 05:40:39.803 [INFO][6] watchersyncer.go 221: All watchers have sync'd data - sending data and final sync
2023-04-18 05:40:39.803 [INFO][6] watchersyncer.go 127: Sending status update Status=in-sync
2023-04-18 05:40:39.804 [INFO][6] cache.go 243: Received status update message from datastore. status=in-sync
2023-04-18 05:40:39.804 [INFO][6] health.go 133: Health of component changed lastReport=health.HealthReport{Live:true, Ready:false} name="felix" newReport=&health.HealthReport{Live:true, Ready:true}
2023-04-18 05:41:10.315 [WARNING][6] rebalance.go 54: Failed to get number of Typhas error=<nil> numTyphas=0 thread="k8s-poll"
2023-04-18 05:41:19.332 [FATAL][6] daemon.go 450: Received SIGTERM, shutting down
```
