### ISSUE TITLE
t_etcd uses wrong import for oslo_config

### ISSUE THREAD

**Issue by flashvoid** [projectcalico/calico#772]
Hi

I tried to install devstack plugin and it failed with 
```
2015-08-19 09:51:48.831 16278 ERROR stevedore.extension [-] Could not load 'calico': No module named config
2015-08-19 09:51:48.831 16278 ERROR stevedore.extension [-] No module named config
2015-08-19 09:51:48.831 16278 ERROR stevedore.extension Traceback (most recent call last):
2015-08-19 09:51:48.831 16278 ERROR stevedore.extension   File "/usr/local/lib/python2.7/dist-packages/stevedore/extension.py", line 162, in _load_plugins
2015-08-19 09:51:48.831 16278 ERROR stevedore.extension     verify_requirements,
2015-08-19 09:51:48.831 16278 ERROR stevedore.extension   File "/usr/local/lib/python2.7/dist-packages/stevedore/named.py", line 123, in _load_one_plugin
2015-08-19 09:51:48.831 16278 ERROR stevedore.extension     verify_requirements,
2015-08-19 09:51:48.831 16278 ERROR stevedore.extension   File "/usr/local/lib/python2.7/dist-packages/stevedore/extension.py", line 183, in _load_one_plugin
2015-08-19 09:51:48.831 16278 ERROR stevedore.extension     plugin = ep.resolve()
2015-08-19 09:51:48.831 16278 ERROR stevedore.extension   File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2361, in resolve
2015-08-19 09:51:48.831 16278 ERROR stevedore.extension     module = __import__(self.module_name, fromlist=['__name__'], level=0)
2015-08-19 09:51:48.831 16278 ERROR stevedore.extension   File "/usr/local/lib/python2.7/dist-packages/calico/openstack/mech_calico.py", line 51, in <module>
2015-08-19 09:51:48.831 16278 ERROR stevedore.extension     from calico.openstack.t_etcd import (
2015-08-19 09:51:48.831 16278 ERROR stevedore.extension   File "/usr/local/lib/python2.7/dist-packages/calico/openstack/t_etcd.py", line 30, in <module>
2015-08-19 09:51:48.831 16278 ERROR stevedore.extension     from oslo.config import cfg
2015-08-19 09:51:48.831 16278 ERROR stevedore.extension ImportError: No module named config
```

Fixed by replacing "from oslo.config" to "from oslo_config".

**Comment by Lukasa** [comment]
@flashvoid Hmm. Last I checked, oslo.config is where the package should go if the package has been installed, rather than being used directly from GitHub. @neiljerram did you ever bump into this with your devstack usage?

**Comment by neiljerram** [comment]
No, I haven't seen this myself yet.  But there has been a general oslo naming change in the pipeline, and I can believe that it is biting now.

@Lukasa, @flashvoid  So that we keep working with older OpenStack releases too, would the following work?

    try:
        from oslo.config import cfg
    except ImportError:
        from oslo_config import cfg

**Comment by Lukasa** [comment]
That would be fine by me.

**Comment by alexwlchan** [comment]
We only have one other oslo import: oslo_log (in t_etcd and mech_calico). We already seem to have covered the name change for that module:

```python
try:  # Icehouse, Juno
    from neutron.openstack.common import log
except ImportError:  # Kilo
    from oslo_log import log
```

So I think this is the only oslo rename that will affect us.
