### ISSUE TITLE
Dodgy looking election logs from plugin

### ISSUE THREAD

**Issue by DaveLangridge** [projectcalico/calico#775]
Running on a deployment with 1 ha proxy, 10 control an 500 computes. 10,000 VMs up, and churn running, doing a create + delete every 2s. These are spread across 500 security groups. I was also running a script to add an SG dependent rule to each sg, so a fairly extreme test. 

In server.log (I did collect diags, but they don't contain server.log!):
```
2015-08-13 16:17:28.251 26827 WARNING calico.election [-] Failed to become elected master - key /calico/openstack/v1/neutron_election: EtcdAlreadyExist('Key already exists : /calico/openstack/v1/neutron_election',)
2015-08-13 16:17:28.661 26825 WARNING calico.election [-] Failed to become elected master - key /calico/openstack/v1/neutron_election: EtcdAlreadyExist('Key already exists : /calico/openstack/v1/neutron_election',)
2015-08-13 16:17:31.957 26829 ERROR calico.openstack.t_etcd [-] Request to etcd failed. This will cause the current API call to fail.
2015-08-13 16:17:31.957 26829 TRACE calico.openstack.t_etcd Traceback (most recent call last):
2015-08-13 16:17:31.957 26829 TRACE calico.openstack.t_etcd   File "/usr/lib/python2.7/dist-packages/calico/openstack/t_etcd.py", line 103, in wrapped
2015-08-13 16:17:31.957 26829 TRACE calico.openstack.t_etcd     return fn(self, *args, **kwargs)
2015-08-13 16:17:31.957 26829 TRACE calico.openstack.t_etcd   File "/usr/lib/python2.7/dist-packages/calico/openstack/t_etcd.py", line 290, in get_endpoint_data
2015-08-13 16:17:31.957 26829 TRACE calico.openstack.t_etcd     result = self.client.read(endpoint.key, timeout=ETCD_TIMEOUT)
2015-08-13 16:17:31.957 26829 TRACE calico.openstack.t_etcd   File "/usr/lib/python2.7/dist-packages/etcd/client.py", line 356, in read
2015-08-13 16:17:31.957 26829 TRACE calico.openstack.t_etcd     timeout=timeout)
2015-08-13 16:17:31.957 26829 TRACE calico.openstack.t_etcd   File "/usr/lib/python2.7/dist-packages/etcd/client.py", line 612, in api_execute
2015-08-13 16:17:31.957 26829 TRACE calico.openstack.t_etcd     return self._handle_server_response(response)
2015-08-13 16:17:31.957 26829 TRACE calico.openstack.t_etcd   File "/usr/lib/python2.7/dist-packages/etcd/client.py", line 643, in _handle_server_response
2015-08-13 16:17:31.957 26829 TRACE calico.openstack.t_etcd     etcd.EtcdError.handle(**r)
2015-08-13 16:17:31.957 26829 TRACE calico.openstack.t_etcd   File "/usr/lib/python2.7/dist-packages/etcd/__init__.py", line 193, in handle
2015-08-13 16:17:31.957 26829 TRACE calico.openstack.t_etcd     raise exc(msg, payload)
2015-08-13 16:17:31.957 26829 TRACE calico.openstack.t_etcd EtcdKeyNotFound: Key not found : /calico/v1/host/dl-compute474/workload/openstack/79039fd8-31f0-4c31-aa57-637f71b12420
2015-08-13 16:17:31.957 26829 TRACE calico.openstack.t_etcd
2015-08-13 16:17:31.958 26829 WARNING calico.openstack.t_etcd [-] Request to etcd failed, reinitialising our connection.
2015-08-13 16:17:31.958 26829 WARNING calico.openstack.t_etcd [-] There was already an elector, shutting it down.
2015-08-13 16:17:31.959 26829 ERROR calico.election [-] Failed to step down as master.  Ignoring.
2015-08-13 16:17:31.959 26829 TRACE calico.election Traceback (most recent call last):
2015-08-13 16:17:31.959 26829 TRACE calico.election   File "/usr/lib/python2.7/dist-packages/calico/election.py", line 242, in _attempt_step_down
2015-08-13 16:17:31.959 26829 TRACE calico.election     timeout=self._interval)
2015-08-13 16:17:31.959 26829 TRACE calico.election   File "/usr/lib/python2.7/dist-packages/etcd/client.py", line 401, in delete
2015-08-13 16:17:31.959 26829 TRACE calico.election     self.key_endpoint + key, self._MDELETE, params=kwds)
2015-08-13 16:17:31.959 26829 TRACE calico.election   File "/usr/lib/python2.7/dist-packages/etcd/client.py", line 612, in api_execute
2015-08-13 16:17:31.959 26829 TRACE calico.election     return self._handle_server_response(response)
2015-08-13 16:17:31.959 26829 TRACE calico.election   File "/usr/lib/python2.7/dist-packages/etcd/client.py", line 643, in _handle_server_response
2015-08-13 16:17:31.959 26829 TRACE calico.election     etcd.EtcdError.handle(**r)
2015-08-13 16:17:31.959 26829 TRACE calico.election   File "/usr/lib/python2.7/dist-packages/etcd/__init__.py", line 195, in handle
2015-08-13 16:17:31.959 26829 TRACE calico.election     raise exc(msg)
2015-08-13 16:17:31.959 26829 TRACE calico.election ValueError: Compare failed : [dl-control01:26829 != dl-control06:19893]
2015-08-13 16:17:31.959 26829 TRACE calico.election
2015-08-13 16:17:31.978 26829 WARNING urllib3.connectionpool [-] HttpConnectionPool is full, discarding connection: localhost
2015-08-13 16:17:34.628 26833 WARNING calico.election [-] Failed to become elected master - key /calico/openstack/v1/neutron_election: EtcdAlreadyExist('Key already exists : /calico/openstack/v1/neutron_election',)
2015-08-13 16:17:34.637 26833 WARNING urllib3.connectionpool [req-cbd648e5-ba78-47c6-b0be-c66df1407178 ] HttpConnectionPool is full, discarding connection: localhost
```

**Comment by fasaxc** [comment]
@DaveLangridge I think we tracked this down to the mysql deadlock, and more recently, we've further beefed up the elector initialisation.  Think we can close this?

**Comment by DaveLangridge** [comment]
Yes. Not seen this recently.
