### ISSUE TITLE
Getting `panic: template: get:2:111: executing "get" at <config "asnumber">:`

### ISSUE THREAD

**Issue by kanitaly** [projectcalico/calico#7755]
## Expected Behavior

No Panic
## Current Behavior

Getting Panic Error as shown below,

```
$ calicoctl get nodes -o wide --allow-version-mismatch
panic: template: get:2:111: executing "get" at <config "asnumber">: error calling config: runtime error: invalid memory address or nil pointer dereference

goroutine 1 [running]:
github.com/projectcalico/calico/calicoctl/calicoctl/commands/common.ResourcePrinterTable.Print({{0x0?, 0x1ec2780?, 0xc0004e2980?}, 0xb8?, 0xfd?}, {0x22e7620, 0xc0004c2780}, {0xc000493f70, 0x1, 0x1})
	/go/src/github.com/projectcalico/calico/calicoctl/calicoctl/commands/common/printer.go:139 +0x597
github.com/projectcalico/calico/calicoctl/calicoctl/commands.Get({0xc0006599a0, 0x5, 0x5})
	/go/src/github.com/projectcalico/calico/calicoctl/calicoctl/commands/get.go:210 +0x876
main.main()
	/go/src/github.com/projectcalico/calico/calicoctl/calicoctl/calicoctl.go:126 +0x5df
```
## Steps to Reproduce (for bugs)

just typed the command 
```
calicoctl get nodes -o wide --allow-version-mismatch
```

## Your Environment

```
calicoctl version
Client Version:    v3.26.0
Git commit:        8b103f46f
Cluster Version:   v3.25.1
Cluster Type:      typha,kdd,k8s,bgp
```

**Comment by cyclinder** [comment]
Can you show you a version of Calico and Calicoctl?

**Comment by sridhartigera** [comment]
@kanitaly Can you please run the command with debug turned on. ```calicoctl --log-level=debug get nodes -o wide --allow-version-mismatch``` and share the output.
