### ISSUE TITLE
tigera-operator v1.30.4 (3.26.1) crashlooping on EKS 1.27

### ISSUE THREAD

**Issue by rubroboletus** [projectcalico/calico#7886]
On a test cluster, we have upgraded EKS from 1.26 to 1.27 and Calico to 3.26.1 from 3.25.1. After worker nodes upgrade, tigera-operator starts crashlooping on amd64 and also on arm64.

## Expected Behavior

Start, run.

## Current Behavior

```
2023/07/27 11:10:26 [INFO] Version: v1.30.4
2023/07/27 11:10:26 [INFO] Go Version: go1.20.4
2023/07/27 11:10:26 [INFO] Go OS/Arch: linux/arm64
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe2f048]

goroutine 1 [running]:
k8s.io/client-go/discovery.convertAPIResource(...)
    /go/pkg/mod/k8s.io/client-go@v0.26.3/discovery/aggregated_discovery.go:114
k8s.io/client-go/discovery.convertAPIGroup({{{0x0, 0x0}, {0x0, 0x0}}, {{0x400052b038, 0x15}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...})
    /go/pkg/mod/k8s.io/client-go@v0.26.3/discovery/aggregated_discovery.go:95 +0x558
k8s.io/client-go/discovery.SplitGroupsAndResources({{{0x40000efbf0, 0x15}, {0x400050df80, 0x1b}}, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...})
    /go/pkg/mod/k8s.io/client-go@v0.26.3/discovery/aggregated_discovery.go:49 +0x104
k8s.io/client-go/discovery.(*DiscoveryClient).downloadAPIs(0x4000826ec8?)
    /go/pkg/mod/k8s.io/client-go@v0.26.3/discovery/discovery_client.go:328 +0x314
k8s.io/client-go/discovery.(*DiscoveryClient).GroupsAndMaybeResources(0x28?)
    /go/pkg/mod/k8s.io/client-go@v0.26.3/discovery/discovery_client.go:203 +0x48
k8s.io/client-go/discovery.ServerGroupsAndResources({0x24353d0, 0x40004f12c0})
    /go/pkg/mod/k8s.io/client-go@v0.26.3/discovery/discovery_client.go:413 +0x4c
k8s.io/client-go/discovery.(*DiscoveryClient).ServerGroupsAndResources.func1()
    /go/pkg/mod/k8s.io/client-go@v0.26.3/discovery/discovery_client.go:376 +0x28
k8s.io/client-go/discovery.withRetries(0x2, 0x4000827378)
    /go/pkg/mod/k8s.io/client-go@v0.26.3/discovery/discovery_client.go:651 +0x90
k8s.io/client-go/discovery.(*DiscoveryClient).ServerGroupsAndResources(0x4f?)
    /go/pkg/mod/k8s.io/client-go@v0.26.3/discovery/discovery_client.go:375 +0x38
k8s.io/client-go/restmapper.GetAPIGroupResources({0x24353d0?, 0x40004f12c0?})
    /go/pkg/mod/k8s.io/client-go@v0.26.3/restmapper/discovery.go:148 +0x34
sigs.k8s.io/controller-runtime/pkg/client/apiutil.NewDynamicRESTMapper.func1()
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/client/apiutil/dynamicrestmapper.go:94 +0x28
sigs.k8s.io/controller-runtime/pkg/client/apiutil.(*dynamicRESTMapper).setStaticMapper(...)
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/client/apiutil/dynamicrestmapper.go:130
sigs.k8s.io/controller-runtime/pkg/client/apiutil.NewDynamicRESTMapper(0x40004e2480?, {0x0, 0x0, 0x1c9f438?})
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/client/apiutil/dynamicrestmapper.go:110 +0x188
sigs.k8s.io/controller-runtime/pkg/client.newClient(0x40004e2480?, {0x0?, {0x0?, 0x0?}, {0xb?, 0x0?}})
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/client/client.go:109 +0x178
sigs.k8s.io/controller-runtime/pkg/client.New(...)
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/client/client.go:77
main.main()
    /go/src/github.com/tigera/operator/main.go:172 +0x87c
````

## Steps to Reproduce (for bugs)

1. install EKS 1.27
2. install tigera operator 1.30.4
3. see crashloops
4. may be connected / similar to issue https://github.com/aws/amazon-vpc-cni-k8s/issues/2393

## Your Environment

* Calico version 2.36.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): EKS 1.27
* Operating System and version: Bottlerocket OS 1.14.2

**Comment by rubroboletus** [comment]
Confirmed the similarity with issue mentioned in step 4. When prometheus-adapter is temporarily turned off, tigera-operator starts correctly and operates without any problem. But any restart of pod, when prometheus-adapter is active ends with crashloop.

**Comment by mazdakn** [comment]
@tmjd please take a look at this one too.

**Comment by caseydavenport** [comment]
@mazdakn from a quick look at the linked issue, it seems pretty clear this is just a go.mod issue.

I've submitted a PR for this one here: https://github.com/tigera/operator/pull/2901
