### ISSUE TITLE
Exception hit intermittently when deleting VMs

### ISSUE THREAD

**Issue by lwr20** [projectcalico/calico#815]
Sometimes when I delete a VM, I see this exception:
```
calico.openstack.t_etcd [-] Request to etcd failed. This will cause the current API call to fail.
calico.openstack.t_etcd Traceback (most recent call last):
calico.openstack.t_etcd   File "/usr/lib/python2.7/dist-packages/calico/openstack/t_etcd.py", line 106, in wrapped
calico.openstack.t_etcd     return fn(self, *args, **kwargs)
calico.openstack.t_etcd   File "/usr/lib/python2.7/dist-packages/calico/openstack/t_etcd.py", line 293, in get_endpoint_data
calico.openstack.t_etcd     result = self.client.read(endpoint.key, timeout=ETCD_TIMEOUT)
calico.openstack.t_etcd   File "/usr/lib/python2.7/dist-packages/etcd/client.py", line 356, in read
calico.openstack.t_etcd     timeout=timeout)
calico.openstack.t_etcd   File "/usr/lib/python2.7/dist-packages/etcd/client.py", line 612, in api_execute
calico.openstack.t_etcd     return self._handle_server_response(response)
calico.openstack.t_etcd   File "/usr/lib/python2.7/dist-packages/etcd/client.py", line 643, in _handle_server_response
calico.openstack.t_etcd     etcd.EtcdError.handle(**r)
calico.openstack.t_etcd   File "/usr/lib/python2.7/dist-packages/etcd/__init__.py", line 193, in handle
calico.openstack.t_etcd     raise exc(msg, payload)
calico.openstack.t_etcd EtcdKeyNotFound: Key not found : /calico/v1/host/calico-st04/workload/openstack/42916f9b-ec59-448b-8848-5f03a964244f
calico.openstack.t_etcd
```
Seems benign, but its obviously log spam.

**Comment by fasaxc** [comment]
Looks like it's already deleted?  Could be that a periodic resync cleaned it up before the explicit delete?

**Comment by fasaxc** [comment]
Fixed by #824

**Comment by fasaxc** [comment]
@lwr20 I rolled a fix for this into the PR above, please can you keep an eye out.  It was always log spam; the exception was caught at one level higher up the stack but by then it had already been logged.

You should now get a warning log: "Expected etcd error, re-raising" instead.

**Comment by lwr20** [comment]
Now happy to close - not seen this since Sept 11.
