### ISSUE TITLE
Deadlock during allocateip on rke2-canal

### ISSUE THREAD

**Issue by TJonesy** [projectcalico/calico#8406]
## Expected Behavior
Not crashlooping

## Current Behavior
Crashlooping during the allocateip process. My pods do seem to be able to get ips still but this log flooding is very frustrating.

```
rke2-canal-lsbdt calico-node W0111 20:22:41.119876    5904 feature_gate.go:241] Setting GA feature gate ServiceInternalTrafficPolicy=true. It will be removed in a future release.
rke2-canal-lsbdt calico-node 2024-01-11 20:22:41.138 [INFO][5904] tunnel-ip-allocator/env_var_loader.go 40: Found felix environment variable: "prometheusmetricsenabled"="true"
rke2-canal-lsbdt calico-node 2024-01-11 20:22:41.138 [INFO][5904] tunnel-ip-allocator/env_var_loader.go 40: Found felix environment variable: "failsafeoutboundhostports"=""
rke2-canal-lsbdt calico-node 2024-01-11 20:22:41.139 [INFO][5904] tunnel-ip-allocator/env_var_loader.go 40: Found felix environment variable: "healthenabled"="true"
rke2-canal-lsbdt calico-node 2024-01-11 20:22:41.139 [INFO][5904] tunnel-ip-allocator/env_var_loader.go 40: Found felix environment variable: "failsafeinboundhostports"=""
rke2-canal-lsbdt calico-node 2024-01-11 20:22:41.139 [INFO][5904] tunnel-ip-allocator/env_var_loader.go 40: Found felix environment variable: "iptablesrefreshinterval"="60"
rke2-canal-lsbdt calico-node 2024-01-11 20:22:41.139 [INFO][5904] tunnel-ip-allocator/env_var_loader.go 40: Found felix environment variable: "defaultendpointtohostaction"="ACCEPT"
rke2-canal-lsbdt calico-node 2024-01-11 20:22:41.139 [INFO][5904] tunnel-ip-allocator/env_var_loader.go 40: Found felix environment variable: "logseverityscreen"="info"
rke2-canal-lsbdt calico-node 2024-01-11 20:22:41.139 [INFO][5904] tunnel-ip-allocator/env_var_loader.go 40: Found felix environment variable: "iptablesbackend"="auto"
rke2-canal-lsbdt calico-node 2024-01-11 20:22:41.139 [INFO][5904] tunnel-ip-allocator/env_var_loader.go 40: Found felix environment variable: "ipv6support"="false"
rke2-canal-lsbdt calico-node 2024-01-11 20:22:41.139 [INFO][5904] tunnel-ip-allocator/env_var_loader.go 40: Found felix environment variable: "xdpenabled"="false"
rke2-canal-lsbdt calico-node 2024-01-11 20:22:41.140 [INFO][5904] tunnel-ip-allocator/config_params.go 481: Merging in config from environment variable: map[defaultendpointtohostaction:ACCEPT failsafeinboundhostports: failsafeoutboundhostports: healthenabled:true iptablesbackend:auto iptablesrefreshinterval:60 ipv6support:false logseverityscreen:info prometheusmetricsenabled:true xdpenabled:false]
rke2-canal-lsbdt calico-node 2024-01-11 20:22:41.140 [INFO][5904] tunnel-ip-allocator/config_params.go 490: Ignoring empty configuration parameter. Use value 'none' if your intention is to explicitly disable the default value. name="failsafeoutboundhostports" source=environment variable
rke2-canal-lsbdt calico-node 2024-01-11 20:22:41.140 [INFO][5904] tunnel-ip-allocator/config_params.go 490: Ignoring empty configuration parameter. Use value 'none' if your intention is to explicitly disable the default value. name="failsafeinboundhostports" source=environment variable
rke2-canal-lsbdt calico-node 2024-01-11 20:22:41.141 [INFO][5904] tunnel-ip-allocator/config_params.go 612: Parsing value for PrometheusMetricsEnabled: true (from environment variable)
rke2-canal-lsbdt calico-node 2024-01-11 20:22:41.141 [INFO][5904] tunnel-ip-allocator/config_params.go 648: Parsed value for PrometheusMetricsEnabled: true (from environment variable)
rke2-canal-lsbdt calico-node 2024-01-11 20:22:41.141 [INFO][5904] tunnel-ip-allocator/config_params.go 612: Parsing value for IptablesBackend: auto (from environment variable)
rke2-canal-lsbdt calico-node 2024-01-11 20:22:41.142 [INFO][5904] tunnel-ip-allocator/config_params.go 648: Parsed value for IptablesBackend: auto (from environment variable)
rke2-canal-lsbdt calico-node 2024-01-11 20:22:41.142 [INFO][5904] tunnel-ip-allocator/config_params.go 612: Parsing value for Ipv6Support: false (from environment variable)
rke2-canal-lsbdt calico-node 2024-01-11 20:22:41.142 [INFO][5904] tunnel-ip-allocator/config_params.go 648: Parsed value for Ipv6Support: false (from environment variable)
rke2-canal-lsbdt calico-node 2024-01-11 20:22:41.142 [INFO][5904] tunnel-ip-allocator/config_params.go 612: Parsing value for XDPEnabled: false (from environment variable)
rke2-canal-lsbdt calico-node 2024-01-11 20:22:41.142 [INFO][5904] tunnel-ip-allocator/config_params.go 648: Parsed value for XDPEnabled: false (from environment variable)
rke2-canal-lsbdt calico-node 2024-01-11 20:22:41.142 [INFO][5904] tunnel-ip-allocator/config_params.go 612: Parsing value for HealthEnabled: true (from environment variable)
rke2-canal-lsbdt calico-node 2024-01-11 20:22:41.143 [INFO][5904] tunnel-ip-allocator/config_params.go 648: Parsed value for HealthEnabled: true (from environment variable)
rke2-canal-lsbdt calico-node 2024-01-11 20:22:41.143 [INFO][5904] tunnel-ip-allocator/config_params.go 612: Parsing value for DefaultEndpointToHostAction: ACCEPT (from environment variable)
rke2-canal-lsbdt calico-node 2024-01-11 20:22:41.143 [INFO][5904] tunnel-ip-allocator/config_params.go 648: Parsed value for DefaultEndpointToHostAction: ACCEPT (from environment variable)
rke2-canal-lsbdt calico-node 2024-01-11 20:22:41.143 [INFO][5904] tunnel-ip-allocator/config_params.go 612: Parsing value for LogSeverityScreen: info (from environment variable)
rke2-canal-lsbdt calico-node 2024-01-11 20:22:41.143 [INFO][5904] tunnel-ip-allocator/config_params.go 648: Parsed value for LogSeverityScreen: INFO (from environment variable)
rke2-canal-lsbdt calico-node 2024-01-11 20:22:41.144 [INFO][5904] tunnel-ip-allocator/config_params.go 612: Parsing value for IptablesRefreshInterval: 60 (from environment variable)
rke2-canal-lsbdt calico-node 2024-01-11 20:22:41.144 [INFO][5904] tunnel-ip-allocator/config_params.go 648: Parsed value for IptablesRefreshInterval: 1m0s (from environment variable)
rke2-canal-lsbdt calico-node fatal error: all goroutines are asleep - deadlock!
rke2-canal-lsbdt calico-node
rke2-canal-lsbdt calico-node goroutine 1 [chan receive]:
rke2-canal-lsbdt calico-node github.com/projectcalico/calico/node/pkg/allocateip.run({0x4000052069?, 0x8?}, 0x60?, {0x306da80?, 0x40007a9400?}, 0x0?, 0x4000180180)
rke2-canal-lsbdt calico-node    /go/src/github.com/projectcalico/calico/node/pkg/allocateip/allocateip.go:86 +0x39c
rke2-canal-lsbdt calico-node github.com/projectcalico/calico/node/pkg/allocateip.Run(0x400061a300?)
rke2-canal-lsbdt calico-node    /go/src/github.com/projectcalico/calico/node/pkg/allocateip/allocateip.go:73 +0x9c
rke2-canal-lsbdt calico-node main.main()
rke2-canal-lsbdt calico-node    github.com/projectcalico/calico/node/cmd/calico-node/main.go:175 +0x528
rke2-canal-lsbdt calico-node
rke2-canal-lsbdt calico-node goroutine 35 [select, locked to thread]:
rke2-canal-lsbdt calico-node github.com/mdlayher/netlink.newLockedNetNSGoroutine.func1()
rke2-canal-lsbdt calico-node    /go/pkg/mod/github.com/mdlayher/netlink@v1.1.0/conn_linux.go:738 +0x2a8
rke2-canal-lsbdt calico-node created by github.com/mdlayher/netlink.newLockedNetNSGoroutine
rke2-canal-lsbdt calico-node    /go/pkg/mod/github.com/mdlayher/netlink@v1.1.0/conn_linux.go:669 +0x1cc
```

## Steps to Reproduce (for bugs)
Unknown

## Context
I believe this is causing delays in podinitialization, intermittent networking issues, and is producing a massive amount of logs,

## Your Environment
Client Version:    v3.26.3
Git commit:        bdb7878af
Cluster Version:   v3.26.3
Cluster Type:      k8s,canal,kdd

[rke2-charts/rke2-canal:v3.26.3-build20231109](https://github.com/rancher/rke2-charts/tree/main/charts/rke2-canal/rke2-canal/v3.26.3-build2023110900)
```
# values.yaml
global:
  clusterCIDR: 10.42.0.0/16
  clusterCIDRv4: 10.42.0.0/16
  clusterDNS: 10.43.0.10
  clusterDomain: cluster.local
  rke2DataDir: /var/lib/rancher/rke2
  serviceCIDR: 10.43.0.0/16
```
[rancher/hardened-calico:v3.26.3-build20231109](https://github.com/rancher/image-build-calico/blob/v3.26.3-build20231109/Dockerfile)
RKE2 v1.28.4 +rke2r1
Ubuntu 22.04 aarch64
Linux 5.15.0-1044-raspi #47-Ubuntu aarch64 aarch64 aarch64 GNU/Linux
Using networkd
6x RaspberryPI CM4

**Comment by caseydavenport** [comment]
Hmmm, this is a new one

First thing that jumps out at me is that RKE seems to be deploying a modified Calico image, not sourced from the Calico team or a Calico release. I am not sure what modifications they have made but it could be related.

The other interesting thing is that the line of code called out in the crash is just a wait on a channel read, meant to be executed when bypassing allocateip logic: https://github.com/projectcalico/calico/blob/bdb7878af3d67c690ef83ea3d008ef0498568f43/node/pkg/allocateip/allocateip.go#L83-L86

Can you confirm whether or not your calico-node DaemonSet has the env var `K8S_USE_POD_CIDR` set to true?

My suspicion is that this has something to do with how RKE has re-compiled Calico, because the particular place that it is complaining is actually intended to be an indefinite `sleep` - might be worth raising this one against RKE as well.

**Comment by TJonesy** [comment]
I ended up deciding to deploy calico directly instead of rke2-canal and I am no longer having that issue so I guess we can close this. Unfortunately I don't have a spare cluster to keep playing with this issue. Thanks for taking the time to look into it.

**Comment by ChickenIQ** [comment]
I believe i am experiencing the same issue, but over on k3s.
Everything seems to be working fine, but I keep getting the same error as above.
I am working on debugging this.

K3S Version: v1.28.5+k3s1
Canal Version: v3.27.0

**Comment by ChickenIQ** [comment]
Resetting iptables seems to have resolved the issue

**Comment by ChickenIQ** [comment]
> I believe i am experiencing the same issue, but over on k3s. Everything seems to be working fine, but I keep getting the same error as above. I am working on debugging this.
> 
> K3S Version: v1.28.5+k3s1 Canal Version: v3.27.0

Weirdly enough, the problem came back on v3.27.0, but does not happen on v3.26.4
