### ISSUE TITLE
Unexpected vif_type=tap breaking all tests

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico#868]
My most recent PR FV run  (Icehouse) failed with these errors in the nova-scheduler log:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nova/compute/manager.py", line 1388, in _build_instance
    set_access_ip=set_access_ip)
  File "/usr/lib/python2.7/dist-packages/nova/compute/manager.py", line 414, in decorated_function
    return function(self, context, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/nova/compute/manager.py", line 1806, in _spawn
    LOG.exception(_('Instance failed to spawn'), instance=instance)
  File "/usr/lib/python2.7/dist-packages/nova/openstack/common/excutils.py", line 68, in __exit__
    six.reraise(self.type_, self.value, self.tb)
  File "/usr/lib/python2.7/dist-packages/nova/compute/manager.py", line 1803, in _spawn
    block_device_info)
  File "/usr/lib/python2.7/dist-packages/nova/virt/libvirt/driver.py", line 2370, in spawn
    write_to_disk=True)
  File "/usr/lib/python2.7/dist-packages/nova/virt/libvirt/driver.py", line 3572, in to_xml
    disk_info, rescue, block_device_info)
  File "/usr/lib/python2.7/dist-packages/nova/virt/libvirt/driver.py", line 3378, in get_guest_config
    flavor)
  File "/usr/lib/python2.7/dist-packages/nova/virt/libvirt/vif.py", line 384, in get_config
    _("Unexpected vif_type=%s") % vif_type)
NovaException: Unexpected vif_type=tap
```
Sounds similar to #297; maybe they've revved the package.

This was run-fv-tests-pr-req build 129.

**Comment by fasaxc** [comment]
Looks like nova has been revved to `1:2014.1.5-0ubuntu1.4` upstream, replacing our `1:2014.1.5-0ubuntu1.3calico1.0.0+1`.

**Comment by matthewdupre** [comment]
Pins should prevent this.

**Comment by fasaxc** [comment]
@matthewdupre is there anything left to do on this now you've fixed the pins?

**Comment by matthewdupre** [comment]
Not on this particular issue (or this particular upstream release).

If anybody hits this symptom, please check your apt preferences (or RPM priorities).  The install instructions should lead you through setting them up.  If you can't use a pin / priority for some reason, please let us know on slack / IRC / ..., and we'll try and prioritize the rebase.
