### ISSUE TITLE
Deadlock between eventlet and mysql driver in neutron plugin

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico#869]
Juno FV test run number 104 hit this exception:
```
calico.openstack.mech_calico [-] Failed to update port status for 86ad7895-4d3e-4c18-8368-07005e2b891d. Giving up.
calico.openstack.mech_calico Traceback (most recent call last):
calico.openstack.mech_calico   File "/usr/lib/python2.7/dist-packages/calico/openstack/mech_calico.py", line 303, in on_port_status_changed
calico.openstack.mech_calico     filter(models_v2.Port.id.startswith(port_id)).
calico.openstack.mech_calico   File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2369, in one
calico.openstack.mech_calico     ret = list(self)
calico.openstack.mech_calico   File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2412, in __iter__
calico.openstack.mech_calico     return self._execute_and_instances(context)
calico.openstack.mech_calico   File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2427, in _execute_and_instances
calico.openstack.mech_calico     result = conn.execute(querycontext.statement, self._params)
calico.openstack.mech_calico   File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 729, in execute
calico.openstack.mech_calico     return meth(self, multiparams, params)
calico.openstack.mech_calico   File "/usr/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 321, in _execute_on_connection
calico.openstack.mech_calico     return connection._execute_clauseelement(self, multiparams, params)
calico.openstack.mech_calico   File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 826, in _execute_clauseelement
calico.openstack.mech_calico     compiled_sql, distilled_params
calico.openstack.mech_calico   File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
calico.openstack.mech_calico     context)
calico.openstack.mech_calico   File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1156, in _handle_dbapi_exception
calico.openstack.mech_calico     util.raise_from_cause(newraise, exc_info)
calico.openstack.mech_calico   File "/usr/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
calico.openstack.mech_calico     reraise(type(exception), exception, tb=exc_tb)
calico.openstack.mech_calico   File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
calico.openstack.mech_calico     context)
calico.openstack.mech_calico   File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 436, in do_execute
calico.openstack.mech_calico     cursor.execute(statement, parameters)
calico.openstack.mech_calico   File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
calico.openstack.mech_calico     self.errorhandler(self, exc, value)
calico.openstack.mech_calico   File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
calico.openstack.mech_calico     raise errorclass, errorvalue
calico.openstack.mech_calico OperationalError: (OperationalError) (1205, 'Lock wait timeout exceeded; try restarting transaction') "SELECT ports.tenant_id AS ports_tenant_id, ports.id AS ports_id, ports.name AS ports_name, ports.network_id AS ports_network_id, ports.mac_address AS ports_mac_address, ports.admin_state_up AS ports_admin_state_up, ports.status AS ports_status, ports.device_id AS ports_device_id, ports.device_owner AS ports_device_owner, ipallocations_1.port_id AS ipallocations_1_port_id, ipallocations_1.ip_address AS ipallocations_1_ip_address, ipallocations_1.subnet_id AS ipallocations_1_subnet_id, ipallocations_1.network_id AS ipallocations_1_network_id, securitygroupportbindings_1.port_id AS securitygroupportbindings_1_port_id, securitygroupportbindings_1.security_group_id AS securitygroupportbindings_1_security_group_id, ml2_dvr_port_bindings_1.port_id AS ml2_dvr_port_bindings_1_port_id, ml2_dvr_port_bindings_1.host AS ml2_dvr_port_bindings_1_host, ml2_dvr_port_bindings_1.router_id AS ml2_dvr_port_bindings_1_router_id, ml2_dvr_port_bindings_1.vif_type AS ml2_dvr_port_bindings_1_vif_type, ml2_dvr_port_bindings_1.vif_details AS ml2_dvr_port_bindings_1_vif_details, ml2_dvr_port_bindings_1.vnic_type AS ml2_dvr_port_bindings_1_vnic_type, ml2_dvr_port_bindings_1.profile AS ml2_dvr_port_bindings_1_profile, ml2_dvr_port_bindings_1.cap_port_filter AS ml2_dvr_port_bindings_1_cap_port_filter, ml2_dvr_port_bindings_1.driver AS ml2_dvr_port_bindings_1_driver, ml2_dvr_port_bindings_1.segment AS ml2_dvr_port_bindings_1_segment, ml2_dvr_port_bindings_1.status AS ml2_dvr_port_bindings_1_status, extradhcpopts_1.id AS extradhcpopts_1_id, extradhcpopts_1.port_id AS extradhcpopts_1_port_id, extradhcpopts_1.opt_name AS extradhcpopts_1_opt_name, extradhcpopts_1.opt_value AS extradhcpopts_1_opt_value, ml2_port_bindings_1.port_id AS ml2_port_bindings_1_port_id, ml2_port_bindings_1.host AS ml2_port_bindings_1_host, ml2_port_bindings_1.vnic_type AS ml2_port_bindings_1_vnic_type, ml2_port_bindings_1.profile AS ml2_port_bindings_1_profile, ml2_port_bindings_1.vif_type AS ml2_port_bindings_1_vif_type, ml2_port_bindings_1.vif_details AS ml2_port_bindings_1_vif_details, ml2_port_bindings_1.driver AS ml2_port_bindings_1_driver, ml2_port_bindings_1.segment AS ml2_port_bindings_1_segment, allowedaddresspairs_1.port_id AS allowedaddresspairs_1_port_id, allowedaddresspairs_1.mac_address AS allowedaddresspairs_1_mac_address, allowedaddresspairs_1.ip_address AS allowedaddresspairs_1_ip_address \nFROM ports LEFT OUTER JOIN ipallocations AS ipallocations_1 ON ports.id = ipallocations_1.port_id LEFT OUTER JOIN securitygroupportbindings AS securitygroupportbindings_1 ON ports.id = securitygroupportbindings_1.port_id LEFT OUTER JOIN ml2_dvr_port_bindings AS ml2_dvr_port_bindings_1 ON ports.id = ml2_dvr_port_bindings_1.port_id LEFT OUTER JOIN extradhcpopts AS extradhcpopts_1 ON ports.id = extradhcpopts_1.port_id LEFT OUTER JOIN ml2_port_bindings AS ml2_port_bindings_1 ON ports.id = ml2_port_bindings_1.port_id LEFT OUTER JOIN allowedaddresspairs AS allowedaddresspairs_1 ON ports.id = allowedaddresspairs_1.port_id \nWHERE (ports.id LIKE concat(%s, '%%')) FOR UPDATE" ('86ad7895-4d3e-4c18-8368-07005e2b891d',)
calico.openstack.mech_calico
```
Looks like something else had the port locked and we timed out waiting to acquire it.

**Comment by fasaxc** [comment]
Looks like we had 2 status-reporting threads running in different processes both trying to update the same port
```
$ grep 86ad7895-4d3e-4c18-8368-07005e2b891d server.log  | grep -E 'Updating|Failed'
2015-11-06 06:20:43.311 24801 WARNING neutron.plugins.ml2.managers [req-9502df02-d7a7-458d-b53b-7f1eb26971f9 None] Failed to bind port 86ad7895-4d3e-4c18-8368-07005e2b891d on host calico-ci03
2015-11-06 06:20:45.661 24801 INFO calico.openstack.mech_calico [-] Updating port 86ad7895-4d3e-4c18-8368-07005e2b891d status to DOWN
2015-11-06 06:21:26.610 24808 INFO calico.openstack.mech_calico [-] Updating port 86ad7895-4d3e-4c18-8368-07005e2b891d status to DOWN
2015-11-06 06:21:36.082 24801 ERROR calico.openstack.mech_calico [-] Failed to update port status for 86ad7895-4d3e-4c18-8368-07005e2b891d. Giving up.
2015-11-06 06:21:36.132 24801 INFO calico.openstack.mech_calico [-] Updating port 86ad7895-4d3e-4c18-8368-07005e2b891d status to DOWN
2015-11-06 06:21:36.195 24808 INFO calico.openstack.mech_calico [-] Updating port 86ad7895-4d3e-4c18-8368-07005e2b891d status to ERROR
2015-11-06 06:21:36.318 24801 INFO calico.openstack.mech_calico [-] Updating port 86ad7895-4d3e-4c18-8368-07005e2b891d status to ERROR
```

**Comment by fasaxc** [comment]
The electors are fighting and the leadership is bouncing around:
```
2015-11-06 05:10:44.555 24787 DEBUG calico.election [-] Try to become the master - key not found _vote /usr/lib/python2.7/dist-packages/calico/election.py:119
2015-11-06 05:10:44.558 24787 INFO calico.election [-] Successfully become master - key /calico/openstack/v1/neutron_election, value calico-ci01:24787
2015-11-06 05:14:53.406 24801 DEBUG calico.election [-] ID of elected master is : calico-ci01:24787 _vote /usr/lib/python2.7/dist-packages/calico/election.py:127
2015-11-06 05:15:54.925 24802 DEBUG calico.election [-] ID of elected master is : calico-ci01:24787 _vote /usr/lib/python2.7/dist-packages/calico/election.py:127
2015-11-06 05:15:56.318 24807 DEBUG calico.election [-] ID of elected master is : calico-ci01:24787 _vote /usr/lib/python2.7/dist-packages/calico/election.py:127
2015-11-06 05:15:56.338 24808 DEBUG calico.election [-] ID of elected master is : calico-ci01:24787 _vote /usr/lib/python2.7/dist-packages/calico/election.py:127
2015-11-06 06:18:25.440 24808 INFO calico.election [-] Leader etcd key went away, attempting to become the elected master
2015-11-06 06:18:25.440 24801 INFO calico.election [-] Leader etcd key went away, attempting to become the elected master
2015-11-06 06:18:25.440 24802 INFO calico.election [-] Leader etcd key went away, attempting to become the elected master
2015-11-06 06:18:25.441 24807 INFO calico.election [-] Leader etcd key went away, attempting to become the elected master
2015-11-06 06:18:25.441 24801 INFO calico.election [-] Successfully become master - key /calico/openstack/v1/neutron_election, value calico-ci01:24801
2015-11-06 06:18:25.442 24808 WARNING calico.election [-] Failed to become elected master - key /calico/openstack/v1/neutron_election: EtcdAlreadyExist('Key already exists : /calico/openstack/v1/neutron_election',)
2015-11-06 06:18:25.444 24808 INFO calico.election [-] Retrying leader election in 3.8 seconds
2015-11-06 06:18:25.444 24802 WARNING calico.election [-] Failed to become elected master - key /calico/openstack/v1/neutron_election: EtcdAlreadyExist('Key already exists : /calico/openstack/v1/neutron_election',)
2015-11-06 06:18:25.445 24807 WARNING calico.election [-] Failed to become elected master - key /calico/openstack/v1/neutron_election: EtcdAlreadyExist('Key already exists : /calico/openstack/v1/neutron_election',)
2015-11-06 06:18:25.445 24802 INFO calico.election [-] Retrying leader election in 5.0 seconds
2015-11-06 06:18:25.445 24807 INFO calico.election [-] Retrying leader election in 5.8 seconds
2015-11-06 06:18:29.218 24808 DEBUG calico.election [-] ID of elected master is : calico-ci01:24801 _vote /usr/lib/python2.7/dist-packages/calico/election.py:127
2015-11-06 06:18:30.412 24802 DEBUG calico.election [-] ID of elected master is : calico-ci01:24801 _vote /usr/lib/python2.7/dist-packages/calico/election.py:127
2015-11-06 06:18:31.209 24807 DEBUG calico.election [-] ID of elected master is : calico-ci01:24801 _vote /usr/lib/python2.7/dist-packages/calico/election.py:127
2015-11-06 06:18:45.091 24787 WARNING calico.election [-] Failed to renew master role - key /calico/openstack/v1/neutron_election: EtcdCompareFailed('Compare failed : [calico-ci01:24787 != calico-ci01:24801]',)
2015-11-06 06:18:45.091 24787 INFO calico.election [-] Retrying leader election in 1.4 seconds
2015-11-06 06:18:46.456 24787 DEBUG calico.election [-] ID of elected master is : calico-ci01:24801 _vote /usr/lib/python2.7/dist-packages/calico/election.py:127
2015-11-06 06:21:25.854 24808 INFO calico.election [-] Leader etcd key went away, attempting to become the elected master
2015-11-06 06:21:25.854 24807 INFO calico.election [-] Leader etcd key went away, attempting to become the elected master
2015-11-06 06:21:25.854 24802 INFO calico.election [-] Leader etcd key went away, attempting to become the elected master
2015-11-06 06:21:25.855 24787 INFO calico.election [-] Leader etcd key went away, attempting to become the elected master
2015-11-06 06:21:25.857 24807 WARNING calico.election [-] Failed to become elected master - key /calico/openstack/v1/neutron_election: EtcdAlreadyExist('Key already exists : /calico/openstack/v1/neutron_election',)
2015-11-06 06:21:25.857 24808 INFO calico.election [-] Successfully become master - key /calico/openstack/v1/neutron_election, value calico-ci01:24808
2015-11-06 06:21:25.857 24807 INFO calico.election [-] Retrying leader election in 5.2 seconds
2015-11-06 06:21:25.857 24787 WARNING calico.election [-] Failed to become elected master - key /calico/openstack/v1/neutron_election: EtcdAlreadyExist('Key already exists : /calico/openstack/v1/neutron_election',)
2015-11-06 06:21:25.858 24787 INFO calico.election [-] Retrying leader election in 5.6 seconds
2015-11-06 06:21:25.859 24802 WARNING calico.election [-] Failed to become elected master - key /calico/openstack/v1/neutron_election: EtcdAlreadyExist('Key already exists : /calico/openstack/v1/neutron_election',)
2015-11-06 06:21:25.859 24802 INFO calico.election [-] Retrying leader election in 6.0 seconds
2015-11-06 06:21:31.098 24807 DEBUG calico.election [-] ID of elected master is : calico-ci01:24808 _vote /usr/lib/python2.7/dist-packages/calico/election.py:127
2015-11-06 06:21:31.447 24787 DEBUG calico.election [-] ID of elected master is : calico-ci01:24808 _vote /usr/lib/python2.7/dist-packages/calico/election.py:127
2015-11-06 06:21:31.849 24802 DEBUG calico.election [-] ID of elected master is : calico-ci01:24808 _vote /usr/lib/python2.7/dist-packages/calico/election.py:127
2015-11-06 06:21:36.156 24801 WARNING calico.election [-] Failed to renew master role - key /calico/openstack/v1/neutron_election: EtcdCompareFailed('Compare failed : [calico-ci01:24801 != calico-ci01:24808]',)
2015-11-06 06:21:36.156 24801 INFO calico.election [-] Retrying leader election in 2.7 seconds
2015-11-06 06:21:38.907 24801 DEBUG calico.election [-] ID of elected master is : calico-ci01:24808 _vote /usr/lib/python2.7/dist-packages/calico/election.py:127
```

**Comment by fasaxc** [comment]
There's also a periodic resync going on.  We may be deadlocking between the status reporting and periodic resync threads?

**Comment by fasaxc** [comment]
This OpenStack issue appears to track the root cause of the Lock wait timeouts.  I suspect that we're not honouring the relevant lock that they added so we deadlock in the same way that Neutron used to: https://bugs.launchpad.net/neutron/+bug/1283522

**Comment by fasaxc** [comment]
And a better description of the underlying cause: https://bugs.launchpad.net/oslo.db/+bug/1350149

**Comment by fasaxc** [comment]
In liberty, OpenStack switched to a pure python mysql driver so the problem shouldn't occur there.

**Comment by fasaxc** [comment]
Since we now know that there's a deadlock between eventlet and mysql, that may explain #775 too.
