### ISSUE TITLE
In RPM, calico-felix incorrectly depends on our neutron deps

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico#875]
Installing only the calico-felix RPM on to a fresh Centos7 system, calico-felix fails with 
```
# calico-felix 
Traceback (most recent call last):
  File "/usr/bin/calico-felix", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 3007, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 728, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 626, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: eventlet
```
It appears that it wasn't built with the `CALICODEPS` environment variable, which ensures that felix gets built with only its own dependencies.

**Comment by fasaxc** [comment]
@neiljerram Maybe this will be fixed by your upcoming work under the Neutron refactoring work?

**Comment by fasaxc** [comment]
This is fixed by moving the OpenStack code out of the main repo.
