### ISSUE TITLE
 Calico incompatible ipset protocol version

### ISSUE THREAD

**Issue by arana198** [projectcalico/calico#8776]
## Expected Behavior

Calico's use of ipset should be as broadly compatible as possible.

## Current Behavior
Calico v3.27.3 crashloops on Alpine and Ubuntu Server hosts now:

```
2024-04-30 12:40:40.998 [INFO][11817] felix/int_dataplane.go 1387: Linux interface state changed. ifIndex=924 ifaceName="calico_tmp_B" state=""
2024-04-30 12:40:40.998 [INFO][11817] felix/int_dataplane.go 1431: Linux interface addrs changed. addrs=<nil> ifaceName="calico_tmp_B"
2024-04-30 12:40:40.999 [ERROR][11817] felix/ipsets.go 656: Bad return code from 'ipset list cali40this-host'. error=exit status 1 family="inet" stderr="ipset v7.11: Kernel and userspace incompatible: settype hash:ip with revision 6 not supported by userspace.\n"
2024-04-30 12:40:41.000 [ERROR][11817] felix/ipsets.go 415: Failed to parse ipset cali40this-host error=exit status 1 family="inet"
2024-04-30 12:40:41.000 [WARNING][11817] felix/ipsets.go 346: Failed to resync with dataplane error=exit status 1 family="inet"
2024-04-30 12:40:41.016 [INFO][11817] felix/ipsets.go 337: Retrying after an ipsets update failure... family="inet"
```

This is similar to an issue that happened a few years ago (https://github.com/projectcalico/calico/issues/5011) and few months ago (https://github.com/projectcalico/calico/issues/8372)

## Possible Solution

All k0s nodes have the following:

```
ipset --version
ipset v7.19, protocol version: 7
```

kube-proxy:

```
k -n kube-system exec -it kube-proxy-vdhv7 -- ipset --version                                                                 
ipset v7.19, protocol version: 7
```

## Your Environment

* Calico version: v3.27.3
* Orchestrator version: k0s 1.29
* Operating System and version: RPI 5 running Alpine and Intel NUC running Ubuntu Server
* Kernel: 6.6.14-0-rpi on RPI and 6.5.0-28-generic on ubuntu server
* kube-proxy IPVS mode

**Comment by arana198** [comment]
I'm installing calico using the official helm chart. I haven't tried in any other mode yet

**Comment by arana198** [comment]
Thanks for looking into this and for the prompt response.
Alpine version is 3.19
Ipset is shipped inside kube-proxy

PS: I downgraded the calico version to V3.26.0 and it works.

**Comment by mazdakn** [comment]
@fasaxc the fix went into v3.27.2: https://github.com/projectcalico/calico/blob/v3.27.3/release-notes/v3.27.2-release-notes.md

@fasaxc I'm not much familiar with the implementation of IPVS mode. Is there any shared ipset between Calico and kube-proxy?

**Comment by fasaxc** [comment]
>Is there any shared ipset between Calico and kube-proxy?

No, there shouldn't be

**Comment by matthewdupre** [comment]
@arana198 Did you manage to try out 3.27.2 or greater?

**Comment by mazdakn** [comment]
@arana198 do you still have the issue?

**Comment by arana198** [comment]
Closing this issue as I don't remember what I did to resolve this

**Comment by mazdakn** [comment]
Thanks @arana198 . Feel free to re-open or open a new one when you remembered.

**Comment by michael-chikoba** [comment]
Hey I am working a a three node active active cluster. am using calico, I have used helm chart as well as calico official download site. now am having the below errors and one calico node is woprking wile two are faling with the felix and ipset mismatch and I have tried different tries. would appreciate if someone that has had this issue before to assist. Thank you

kubectl -n calico-system get pods -o wide
NAME                                       READY   STATUS    RESTARTS   AGE   IP                NODE                   NOMINATED NODE   READINESS GATES
calico-kube-controllers-68856b4548-hgxbz   1/1     Running   0          42m   192.168.130.195   k3s-payments           <none>           <none>
calico-node-5d2pb                          0/1     Running   0          39s   xxxxxxxxxx    payments-ka       <none>           <none>
calico-node-l2hhr                          1/1     Running   0          39s   xxxxxxxxx     k3s-payments           <none>           <none>
calico-node-mh6z2                          0/1     Running   0          39s   xxxxxxxx     payments   <none>           <none>
calico-typha-58f7d9dbb-gm5gc               1/1     Running   0          63m   xxxxxx     k3s-payments           <none>           <none>
calico-typha-58f7d9dbb-tvswt               1/1     Running   0          63m   116.203.77.69     payments-etcd-unique   <none>           <none>
csi-node-driver-2q9lm                      2/2     Running   0          63m   192.168.170.74    payments-ka       <none>           <none>
csi-node-driver-4cwqb                      2/2     Running   0          63m   192.168.118.64    payments   <none>           <none>
csi-node-driver-n94rb                      2/2     Running   0          63m   192.168.130.193   k3s-payments           <none>           <none>
goldmane-5f56496f4c-89qb6                  1/1     Running   0          63m   192.168.170.69    payments-ka      <none>           <none>
whisker-6cc5d659cd-x68qt                   2/2     Running   0          63m   192.168.118.66    payments  <none>           <none>
2025-08-25 11:07:59.137 [INFO][16531] felix/ipsets.go 1057: Type: hash:net family="inet"
2025-08-25 11:07:59.137 [INFO][16531] felix/ipsets.go 1057: Revision: 7 family="inet"
2025-08-25 11:07:59.137 [INFO][16531] felix/ipsets.go 1057: Header: family inet hashsize 1024 maxelem 1048576 bucketsize 12 initval 0x326505fc family="inet"
2025-08-25 11:07:59.137 [INFO][16531] felix/ipsets.go 1057: Size in memory: 504 family="inet"
2025-08-25 11:07:59.137 [INFO][16531] felix/ipsets.go 1057: References: 0 family="inet"
2025-08-25 11:07:59.137 [INFO][16531] felix/ipsets.go 1057: Number of entries: 1 family="inet"
2025-08-25 11:07:59.137 [INFO][16531] felix/ipsets.go 1057: Members: family="inet"
2025-08-25 11:07:59.137 [INFO][16531] felix/ipsets.go 1057: 192.168.0.0/16 family="inet"
2025-08-25 11:07:59.137 [INFO][16531] felix/ipsets.go 1042: Dumping IP set cali40all-vxlan-net. family="inet"
2025-08-25 11:07:59.138 [INFO][16531] felix/ipsets.go 1057: Name: cali40all-vxlan-net family="inet"
2025-08-25 11:07:59.138 [INFO][16531] felix/ipsets.go 1057: Type: hash:net family="inet"
2025-08-25 11:07:59.138 [INFO][16531] felix/ipsets.go 1057: Revision: 7 family="inet"
2025-08-25 11:07:59.138 [INFO][16531] felix/ipsets.go 1057: Header: family inet hashsize 1024 maxelem 1048576 bucketsize 12 initval 0xbfc47ffb family="inet"
2025-08-25 11:07:59.138 [INFO][16531] felix/ipsets.go 1057: Size in memory: 552 family="inet"
2025-08-25 11:07:59.138 [INFO][16531] felix/ipsets.go 1057: References: 0 family="inet"
2025-08-25 11:07:59.138 [INFO][16531] felix/ipsets.go 1057: Number of entries: 2 family="inet"
2025-08-25 11:07:59.138 [INFO][16531] felix/ipsets.go 1057: Members: family="inet"
2025-08-25 11:07:59.138 [INFO][16531] felix/ipsets.go 1057: 10.0.0.8 family="inet"
2025-08-25 11:07:59.138 [INFO][16531] felix/ipsets.go 1057: 10.0.0.9 family="inet"
2025-08-25 11:07:59.138 [PANIC][16531] felix/ipsets.go 379: Failed to update IP sets after multiple retries. family="inet"
panic: (*logrus.Entry) 0xc0005c4b60

goroutine 336 [running]:
github.com/sirupsen/logrus.(*Entry).log(0xc0005fce00, 0x0, {0xc001442ed0, 0x30})
        /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:260 +0x485
github.com/sirupsen/logrus.(*Entry).Log(0xc0005fce00, 0x0, {0xc000085988?, 0x5?, 0x0?})
        /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:304 +0x48
github.com/sirupsen/logrus.(*Entry).Panic(...)
        /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:342
github.com/projectcalico/calico/felix/ipsets.(*IPSets).ApplyUpdates(0xc000445d00)
        /go/src/github.com/projectcalico/calico/felix/ipsets/ipsets.go:379 +0x5b9
github.com/projectcalico/calico/felix/dataplane/linux.(*InternalDataplane).apply.func1({0x50bf4d0?, 0xc000445d00?})
        /go/src/github.com/projectcalico/calico/felix/dataplane/linux/int_dataplane.go:2457 +0x37
created by github.com/projectcalico/calico/felix/dataplane/linux.(*InternalDataplane).apply in goroutine 252
        /go/src/github.com/projectcalico/calico/felix/dataplane/linux/int_dataplane.go:2456 +0xb4c

**Comment by fasaxc** [comment]
@michael-chikoba please open a fresh issue and include the requested by the issue template.  Worth trying the latest Calico version to make sure this isn't fixed already.
