### ISSUE TITLE
Felix dying when caliXXXX interface  not present

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico#899]
I see Felix falling over when attempting to update iptables chains on an interface that doesn't exist.

The log:
```
2015-11-17 20:43:28,449 [INFO][3192/8] calico.felix.fiptables 219: iptables update to chains ['felix-p-_6b8e4fa4bb3707b-i', 'felix-p-_6b8e4fa4bb3707b-o']
2015-11-17 20:43:28,572 [ERROR][3192/18] calico.felix.actor 320: _finish_msg_batch failed.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/calico/felix/actor.py", line 307, in _step
    self._finish_msg_batch(batch, results)
  File "/usr/lib/python2.7/site-packages/calico/felix/endpoint.py", line 329, in _finish_msg_batch
    self._configure_interface()
  File "/usr/lib/python2.7/site-packages/calico/felix/endpoint.py", line 526, in _configure_interface
    if not devices.interface_exists(self._iface_name):
  File "/usr/lib/python2.7/site-packages/calico/felix/devices.py", line 91, in interface_exists
    futils.check_call(["ip", "link", "list", interface])
  File "/usr/lib/python2.7/site-packages/calico/felix/futils.py", line 340, in check_call
    args, retcode, stdout, stderr, input=input_str)
FailedSystemCall: Failed system call (retcode : 1, args : ('ip', 'link', 'list', u'cali20150aac8d6'))
  stdout  :
  stderr  : ip: can't find device 'cali20150aac8d6'

  input  : None

TrackedAsyncResult ('<disabled>', '<disabled>', 'LocalEndpoint(20150aac8d6311e594f2080027d3597e(IPv4))', 'on_endpoint_update') was leaked with exception FailedSystemCall('ip', 'link', 'list', u'cali20150aac8d6').  Dying.
2015-11-17 20:43:28,962 [INFO][3248/1] calico.common 298: Logging initialized
```

It looks like the code tries to handle this case, but uses stderr incorrectly to determine the cause of the problem - it's looking fir "does not exist" in the output, but stderr actually says "can't find device".
```
def interface_exists(interface):
    """ 
    Checks if an interface exists.
    :param str interface: Interface name
    :returns: True if interface device exists
    :raises: FailedSystemCall if ip link list fails.

    We could check under /sys/class/net here, but there's a window where
    /sys/class/net/<iface> might still exist for a link that is in the process
    of being deleted, so we use ip link list instead.
    """
    try:
        futils.check_call(["ip", "link", "list", interface])
        return True
    except futils.FailedSystemCall as fsc:
        if fsc.stderr.count("does not exist") != 0:
            return False
        else:
            # An error other than does not exist; just pass on up
            raise
```

This is causing Felix to cyclically restart and fail to program endpoints that do actually exist.

I'm running on Ubuntu 15.04, 3.19.0-15-generic using https://github.com/projectcalico/calico/releases/tag/1.2.0 via the calico/node container.

**Comment by alexwlchan** [comment]
Which version of Felix are you using? (I'm guessing master.)

Can you repro with the v1.2.1 release? (I'm guessing not.)

**Comment by alexwlchan** [comment]
Looks like Alpine is the culprit here:

Ubuntu 14.04, 3.13.0-24-generic:<br/>Ubuntu 15.04, 3.19.0-26-generic:

```
# ip link list thisdoesnotexist
Device "thisdoesnotexist" does not exist.
```

Alpine 3.2.3, 4.2.0-16-generic (running inside a container):

```
# ip link list thisdoesnotexist
ip: can't find device 'thisdoesnotexist'
```

I'll put up a fix shortly.

**Comment by alexwlchan** [comment]
@caseydavenport Please could you review the proposed fix?

**Comment by plwhite** [comment]
@alexwlchan Fix looks good to me. If you put in a PR, and if @caseydavenport can test it, then I am happy for it to be merged (or we could even merge prior to test so long as we have agreement to test afterwards and the UTs run).

**Comment by alexwlchan** [comment]
@plwhite Fix is in PR 902
