### ISSUE TITLE
We should document our YAJL dependency

### ISSUE THREAD

**Issue by alexwlchan** [projectcalico/calico#901]
Just tried to run UTs; got this error:

```======================================================================
ERROR: Failure: YAJLImportError (YAJL shared object not found.)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/alexwlchan/calico/.tox/py27/local/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/alexwlchan/calico/.tox/py27/local/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/alexwlchan/calico/.tox/py27/local/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/alexwlchan/calico/calico/etcddriver/test/test_driver.py", line 34, in <module>
    from calico.etcddriver import driver
  File "/home/alexwlchan/calico/calico/etcddriver/driver.py", line 50, in <module>
    from ijson.backends import yajl2 as ijson
  File "/home/alexwlchan/calico/.tox/py27/local/lib/python2.7/site-packages/ijson/backends/yajl2.py", line 14, in <module>
    yajl = backends.find_yajl(2)
  File "/home/alexwlchan/calico/.tox/py27/local/lib/python2.7/site-packages/ijson/backends/__init__.py", line 19, in find_yajl
    raise YAJLImportError('YAJL shared object not found.')
YAJLImportError: YAJL shared object not found.
```

Fix was to run `apt-get install libyajl2`, but that's not documented anywhere in our install or UT instructions. We should fix that.

**Comment by fasaxc** [comment]
Our debs and RPMs should depend on it and install it automatically.  Do we have any developer instructions to update?

**Comment by alexwlchan** [comment]
I know of the UT instructions in the README; just wanted to double-check there's nothing else I haven't thought of.
