### ISSUE TITLE
Changes to log level are not being picked up after changing etcd config

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/calico#903]
If you change the log level in etcd (I'm changing /calico/v1/config/LogSeverityScreen), I'm not seeing any updates to the logs.

Previously felix would restart and pick up the log level change if the etcd data was updated.

Easy enough to repro on my system.  Set log level to info, start felix, set log level to debug.  Still only getting info logs and no indication in the logs that the level has been updated.

**Comment by alexwlchan** [comment]
Global etcd config is the last place we look for config values. I assume there’s nothing setting the log level before we check global etcd?

**Comment by robbrockbank** [comment]
Well yes, we initially set the log level to info, and then in my ST I only set it to debug _after_ felix has started.

I verified the value was correct in etcd.

And, if I stop and restart felix, it then picks up the correct value.  So the issue seems to be it's not getting dynamic updates like it used to.

I think this might be related to why my felix is not working too (see #900).  I'm about to add a note to that issue.

**Comment by alexwlchan** [comment]
Huh, that’s weird. Do you know when you last saw it working? I was working on a fork of v1.2.1 last week, and I definitely saw dynamic updates based on global etcd config (although I was twiddling something other than the log levels, which might be significant).

**Comment by robbrockbank** [comment]
This is on the latest HEAD of master

**Comment by alexwlchan** [comment]
Yep. Probably the best person to handle this is @fasaxc. He’s back in the office tomorrow, but I know he’s got a lot of backlogged stuff after DockerCon. I might have a quick poke around to see if I can find anything.

**Comment by fasaxc** [comment]
Hmm, thought I'd manually tested this.  I'll give it a spin here.

**Comment by fasaxc** [comment]
Works for me:

In one console:
```
./etcdctl set /calico/v1/config/LogSeverityScreen INFO
INFO
```
In felix's output:
```
2015-11-19 14:16:36,930 [CRITICAL][27749/3] calico.felix.fetcd 651: Global config value LogSeverityScreen updated.  Felix must be restarted.
2015-11-19 14:16:38,940 [ERROR][27755/139641672222464] calico.etcddriver.protocol 168: Socket closed by other end.
2015-11-19 14:16:38,941 [ERROR][27755/139641672222464] calico.etcddriver.driver 180: Reader thread shutting down, triggering stop event
(env27)root@smc-ubuntu:/home/gulfstream/git/calico# Exception in thread reader-thread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "calico/etcddriver/driver.py", line 165, in _read_from_socket
    for msg_type, msg in self._msg_reader.new_messages(timeout=1):
  File "calico/etcddriver/protocol.py", line 169, in new_messages
    raise SocketClosed()
SocketClosed

2015-11-19 14:16:40,946 [CRITICAL][27755/139641735104320] __main__ 56: Process adopted, assuming felix has died
2015-11-19 14:16:40,946 [CRITICAL][27755/139641735104320] __main__ 59: Driver shutting down.
```

**Comment by fasaxc** [comment]
@robbrockbank I tried the above on master commit ba1cc829b29953d6b36ac06912929a4db02f1dbf.  I also tried setting the per-host value in etcd with the same result.
