### ISSUE TITLE
Periodic resync thread doesn't handle concurrent deletion

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico#914]
Caught by PR FV run 177; looks like we get an EtcdKeyNotFound but we're only expecting EtcdCompareFailed
```
calico.openstack.mech_calico [req-678cf762-201e-4117-81e5-6f41ee9062fe None] Error in periodic resync thread.
calico.openstack.mech_calico Traceback (most recent call last):
calico.openstack.mech_calico   File "/usr/lib/python2.7/dist-packages/calico/openstack/mech_calico.py", line 678, in periodic_resync_thread
calico.openstack.mech_calico     self.resync_endpoints(context)
calico.openstack.mech_calico   File "/usr/lib/python2.7/dist-packages/calico/openstack/mech_calico.py", line 770, in resync_endpoints
calico.openstack.mech_calico     self._resync_changed_ports(context, common_endpoints)
calico.openstack.mech_calico   File "/usr/lib/python2.7/dist-packages/calico/openstack/mech_calico.py", line 855, in _resync_changed_ports
calico.openstack.mech_calico     port, prev_index=endpoint.modified_index
calico.openstack.mech_calico   File "/usr/lib/python2.7/dist-packages/calico/openstack/t_etcd.py", line 107, in wrapped
calico.openstack.mech_calico     return fn(self, *args, **kwargs)
calico.openstack.mech_calico   File "/usr/lib/python2.7/dist-packages/calico/openstack/t_etcd.py", line 254, in write_port_to_etcd
calico.openstack.mech_calico     port_etcd_key(port), json.dumps(data), **kwargs
calico.openstack.mech_calico   File "/usr/lib/python2.7/dist-packages/etcd/client.py", line 406, in write
calico.openstack.mech_calico     response = self.api_execute(path, method, params=params)
calico.openstack.mech_calico   File "/usr/lib/python2.7/dist-packages/etcd/client.py", line 814, in api_execute
calico.openstack.mech_calico     return self._handle_server_response(response)
calico.openstack.mech_calico   File "/usr/lib/python2.7/dist-packages/etcd/client.py", line 849, in _handle_server_response
calico.openstack.mech_calico     etcd.EtcdError.handle(r)
calico.openstack.mech_calico   File "/usr/lib/python2.7/dist-packages/etcd/__init__.py", line 289, in handle
calico.openstack.mech_calico     raise exc(msg, payload)
calico.openstack.mech_calico EtcdKeyNotFound: Key not found : /calico/v1/host/calico-ci02/workload/openstack/255f5da4-ed77-4b4c-8153-5b51c0e303f0
calico.openstack.mech_calico
```

**Comment by neiljerram** [comment]
The merging of the fix for this overlapped with the mech driver move, so fix now needs to be reapplied in networking-calico.  That is tracked by https://bugs.launchpad.net/networking-calico/+bug/1519795.

**Comment by fasaxc** [comment]
We were expecting EtcdCompareFailed (which is what we see if the key was changed under us) if the key had been deleted.  However, we get an EtcdKeyNotFound instead so we don't catch the exception.
