### ISSUE TITLE
File exists error seen while adding tunnel device

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico#928]
Saw this in a scale test.  It killed felix and felix was restarted normally:
```
2015-12-01 09:28:50,456 [ERROR][36/4] calico.felix.felix 200: Exception killing main greenlet
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/calico/felix/felix.py", line 163, in _main_greenlet
    v4_nat_updater, v6_raw_updater)
  File "/usr/lib/python2.7/site-packages/calico/felix/frules.py", line 192, in install_global_rules
    "mode", "ipip"])
  File "/usr/lib/python2.7/site-packages/calico/felix/futils.py", line 340, in check_call
    args, retcode, stdout, stderr, input=input_str)
FailedSystemCall: Failed system call (retcode : 1, args : ('ip', 'tunnel', 'add', 'tunl0', 'mode', 'ipip'))
  stdout  : 
  stderr  : ip: ioctl 0x89f1 failed: File exists

  input  : None

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/site-packages/calico/felix/felix.py", line 163, in _main_greenlet
    v4_nat_updater, v6_raw_updater)
  File "/usr/lib/python2.7/site-packages/calico/felix/frules.py", line 192, in install_global_rules
    "mode", "ipip"])
  File "/usr/lib/python2.7/site-packages/calico/felix/futils.py", line 340, in check_call
    args, retcode, stdout, stderr, input=input_str)
FailedSystemCall: Failed system call (retcode : 1, args : ('ip', 'tunnel', 'add', 'tunl0', 'mode', 'ipip'))
  stdout  : 
  stderr  : ip: ioctl 0x89f1 failed: File exists

  input  : None

<Greenlet at 0x7fdb71801eb0: _main_greenlet(<calico.felix.config.Config object at 0x7fdb7111e8)> failed with FailedSystemCall

```

**Comment by fasaxc** [comment]
Looks like a race with the kernel creating that device concurrently.  Probably worth adding a retry to the codepath.
