### ISSUE TITLE
Old setuptools versions incorrectly reject our python-etcd version number

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico#962]
```
2016-01-18 13:23:54,238 [ERROR][12256/1] calico.felix.felix 243: Exception loading configuration
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/calico/felix/felix.py", line 227, in main
    config = Config(options.config_file)
  File "/usr/lib/python2.7/dist-packages/calico/felix/config.py", line 255, in __init__
    self.IPTABLES_GENERATOR_PLUGIN
  File "/usr/lib/python2.7/dist-packages/calico/felix/config.py", line 614, in _load_plugin
    entry_point = v.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2354, in load
    self.require(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2371, in require
    items = working_set.resolve(reqs, env, installer)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 844, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
VersionConflict: (python-etcd 0.4.2-calico.1 (/usr/lib/python2.7/dist-packages), Requirement.parse('python-etcd>=0.4.1'))
 in my 
```
`0.4.2-calico.1` should be > `0.4.1`; even though it's actually mis-parsing the real version number `0.4.2+calico.1` however, that's not what Ed saw above!

**Comment by fasaxc** [comment]
@eepyaich tried doing an `apt-get upgrade` before the instal but it looks like there wasn't a new-enough version of setuptools (to fix the version comparison) in Ubuntu's repo.

Note: testing this is awkward because the parsing is done at install time of python-etcd so it's the version of setuptools that's installed at that point that matters.

Now python-etcd have accepted our patches upstream, the fix may be as simple as building a vanilla upstream package for 0.4.3, say.

**Comment by fasaxc** [comment]
@matthewdupre I think you're working on this one.

**Comment by fasaxc** [comment]
@matthewdupre I think we resolved this by revving python-etcd, please can you confirm/close?
