### ISSUE TITLE
Calico - facing issues with multiple etcd nodes

### ISSUE THREAD

**Issue by madhurranjan** [projectcalico/calico#975]
"ETCD_AUTHORITY": "10.0.1.193:2379,10.0.1.215:2379,10.0.1.17:2379"
}
2016-02-04 17:02:47,679 27792 [kube-system/kube-dns-v9-viogj] INFO Starting Calico CNI plugin execution
2016-02-04 17:02:47,679 27792 [kube-system/kube-dns-v9-viogj] ERROR Unhandled Exception killed plugin
I'd like ETCD_AUTHORITY to point to multiple etcd nodes. Currently it fails with the following error. Can you take a look please? 

Traceback (most recent call last):
  File "<string>", line 585, in main
  File "<string>", line 47, in __init__
  File "/code/build/calico/out00-PYZ.pyz/pycalico.datastore", line 182, in __init__
ValueError: invalid literal for int() with base 10: '2379,10.0.1.215:2379,10.0.1.17:2379'
2016-02-04 17:02:47,679 27792 [kube-system/kube-dns-v9-viogj] ERROR CNI Error:
{
  "msg": "Unhandled Exception killed plugin",
  "cniVersion": "0.1.0",
  "code": 100,
  "details": null
}

**Comment by fasaxc** [comment]
@madhurranjan Calico doesn't support specifying multiple etcd servers.  We recommend using a local etcd proxy on each host as per [these instructions](https://coreos.com/etcd/docs/2.2.2/proxy.html).  The proxy is a lightweight process that only serves to redirect Calico's requests to a live member of the cluster.
